### PR TITLE
use digest instead of a tag while signing

### LINKED ISSUE #2135: `Sign()` should receive the digest from `Push()`
https://github.com/containerd/nerdctl/blob/8a1f2278ac4b1615625b1099367b4b6900c9d969/pkg/cmd/image/push.go#L151

>> not related to this PR. Just notice when pushing an image, sign (line 152) happens **after** push (line 133-150). Is this expected?

> IIUC signing after pushing is ok (for cosign, at least), but the current implementation is wrong anyway; the `Sign()` function should receive the digest from the `Push()` function to prohibit TOCTOU.
>
> (I'm mentioning this bug publicly because the cosign integration is still experimental for nerdctl)

_Originally posted by @AkihiroSuda in https://github.com/containerd/nerdctl/pull/2132#discussion_r1150932060_

### PR DESCRIPTION
**Pull request by developer-guy**
fixes #2135 

PTAL @AkihiroSuda 

Screen Shot 2023-03-29 at 12 18 18 AM

### CODE REVIEW

File: pkg/cmd/image/push.go [hunk 1]
```diff
@@ -149,10 +150,16 @@ func Push(ctx context.Context, client *containerd.Client, rawRef string, options
 		return err
 	}
 
-	if err = signutil.Sign(rawRef, options.GOptions.Experimental, options.SignOptions); err != nil {
+	if img, err := client.ImageService().Get(ctx, ref); err != nil {
 		return err
+	} else {
+		if err = signutil.Sign(fmt.Sprintf("%s@%s", strings.SplitN(ref, ":", 2)[0],
```
Comment (AkihiroSuda) [inline pkg/cmd/image/push.go:156]: Doesn't seem to work when the ref contains a registry port number

Comment (developer-guy) [reply pkg/cmd/image/push.go:156]: How to fix this 🤔

Comment (AkihiroSuda) [reply pkg/cmd/image/push.go:156]: https://pkg.go.dev/github.com/containerd/containerd/reference#Parse

Comment (developer-guy) [reply pkg/cmd/image/push.go]: thank you, it seems that everything is fine.

File: pkg/cmd/image/push.go [hunk 2]
```diff
@@ -149,10 +150,21 @@ func Push(ctx context.Context, client *containerd.Client, rawRef string, options
...
 
-	if err = signutil.Sign(rawRef, options.GOptions.Experimental, options.SignOptions); err != nil {
+	if img, err := client.ImageService().Get(ctx, ref); err != nil {
 		return err
+	} else {
+		refSpec, err := reference.Parse(ref)
+		if err != nil {
+			return err
+		}
+		signRef := fmt.Sprintf("%s@%s", refSpec.String(), img.Target.Digest.String())
```
Comment (AkihiroSuda) [inline pkg/cmd/image/push.go:160]: ref may already contain the digest?

File: pkg/cmd/image/push.go [hunk 3]
```diff
@@ -149,10 +150,21 @@ func Push(ctx context.Context, client *containerd.Client, rawRef string, options
 		return err
 	}
 
-	if err = signutil.Sign(rawRef, options.GOptions.Experimental, options.SignOptions); err != nil {
+	if img, err := client.ImageService().Get(ctx, ref); err != nil {
 		return err
+	} else {
```
Comment (AkihiroSuda) [inline pkg/cmd/image/push.go:155]: lint is failing

File: pkg/cmd/image/push.go (hunk 2 above)
Comment (developer-guy) [reply pkg/cmd/image/push.go:160]: how? AFAIK, the digest will be created after the image is pushed, so people can't give a digest to the reference.

Comment (AkihiroSuda) [reply pkg/cmd/image/push.go:160]: The local images have digests too

Comment (developer-guy) [reply pkg/cmd/image/push.go:160]: I tried to use ref that contains digest and got the following error while pushing it:
```shell
$ COSIGN_PASSWORD="" _output/nerdctl push --sign cosign --cosign-key cosign.key developerguy/melange:latest@sha256:be956ef9dfe313806ec655e7eaffbc9333522c3560acc56a2dc833575c51cd6a
FATA[0000] failed to create a tmp single-platform image "docker.io/developerguy/melange@sha256:be956ef9dfe313806ec655e7eaffbc9333522c3560acc56a2dc833575c51cd6a-tmp-reduced-platform": image "
docker.io/developerguy/melange@sha256:be956ef9dfe313806ec655e7eaffbc9333522c3560acc56a2dc833575c51cd6a": not found
```

but I do have that image:

```shell
lima@lima-nerdctl:/Users/batuhan.apaydin/workspace/projects/personal/poc/nerdctl$ _output/nerdctl images --digests
REPOSITORY              TAG       DIGEST                                                                     IMAGE ID        CREATED         PLATFORM       SIZE        BLOB SIZE
developerguy/melange    latest    sha256:be956ef9dfe313806ec655e7eaffbc9333522c3560acc56a2dc833575c51cd6a    be956ef9dfe3    16 hours ago    linux/amd64    52.6 MiB    23.3 MiB
```

File: pkg/cmd/image/push.go (hunk 3 above)
Comment (developer-guy) [reply pkg/cmd/image/push.go:155]: I can't see the details 🤔

File: pkg/cmd/image/push.go (hunk 2 above)
Comment (AkihiroSuda) [reply pkg/cmd/image/push.go:160]: This is a bug, and it has to be eventually supported

Comment (developer-guy) [reply pkg/cmd/image/push.go:160]: so, is this a blocker thing against merging this PR?

Comment (AkihiroSuda) [reply pkg/cmd/image/push.go:160]: No

**Comment by AkihiroSuda** [comment]
> [developer-guy](https://github.com/developer-guy) requested a review from [AkihiroSuda](https://github.com/AkihiroSuda) [5 hours ago](https://github.com/containerd/nerdctl/pull/2136#event-8906905495)

CI is still failing

**Comment by developer-guy** [comment]
> > [developer-guy](https://github.com/developer-guy) requested a review from [AkihiroSuda](https://github.com/AkihiroSuda) [5 hours ago](https://github.com/containerd/nerdctl/pull/2136#event-8906905495)
> 
> CI is still failing

fixed, thank you.

File: pkg/cmd/image/push.go [hunk 4]
```diff
@@ -149,10 +150,21 @@ func Push(ctx context.Context, client *containerd.Client, rawRef string, options
...
+	img, err := client.ImageService().Get(ctx, ref)
+	if err != nil {
+		return err
+	}
+	refSpec, err := reference.Parse(ref)
+	if err != nil {
+		return err
+	}
+	signRef := fmt.Sprintf("%s@%s", refSpec.String(), img.Target.Digest.String())
+	logrus.Infof("signing %s", signRef)
```
Comment (djdongjin) [inline pkg/cmd/image/push.go:162]: nit: maybe move the log into `signutil.Sign`, and only log if `Provider != none`. Otherwise when sign is not enabled (i.e., `none`) we will only have a single log `signing xxx@xxx` which indicates we're signing something but no further info (in fact the signing is skipped).

Comment (developer-guy) [reply pkg/cmd/image/push.go:162]: upps! I just added this for debugging purposes, let's remove this, thank you.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
