### PR TITLE
Login & authentication rework, part 1: credentials management and URL parsing 

### LINKED ISSUE #3245: Login to docker.io failed. (`expected acArg to be "docker.io", got "registry-1.docker.io"`)
### Description

I tried to use nerdctl to login to docker.io, but got:
```
nerdctl login docker.io --debug
Enter Username: lingdie
Enter Password:
DEBU[0005] Found hosts dir "/etc/containerd/certs.d"
DEBU[0005] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0005] len(regHosts)=1
ERRO[0007] failed to call tryLoginWithRegHost            error="failed to call rh.Authorizer.AddResponses: expected acArg to be \"docker.io\", got \"registry-1.docker.io\"" i=0
FATA[0007] failed to call rh.Authorizer.AddResponses: expected acArg to be "docker.io", got "registry-1.docker.io"
```

however, this works:
```
nerdctl login --debug
DEBU[0000] Found hosts dir "/etc/containerd/certs.d"
DEBU[0000] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0000] len(regHosts)=1
DEBU[0001] no scope specified for token auth challenge   host=index.docker.io
WARNING: Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
---
nerdctl login https://index.docker.io/v1 --debug
DEBU[0000] Found hosts dir "/etc/containerd/certs.d"
DEBU[0000] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0000] len(regHosts)=1
DEBU[0001] no scope specified for token auth challenge   host=index.docker.io
WARNING: Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

whats the differance betwen these commands? Is this a bug?

I need to ues nerdctl sdk to login and push images to registries, what should I do if I don't want to write hard codes for `docker.io`.

### Steps to reproduce the issue

1. nertctl login docker.io
2. nertctl login
3. nertctl login https://index.docker.io/v1

### Describe the results you received and expected

`nertctl login docker.io` should works as well.

### What version of nerdctl are you using?

nerdctl version
Client:
 Version:	v1.5.0
 OS/Arch:	linux/amd64
 Git commit:	b33a58f288bc42351404a016e694190b897cd252
 buildctl:
  Version:	

Server:
 containerd:
  Version:	v1.7.15
  GitCommit:	926c9586fe4a6236699318391cd44976a98e31f1
 runc:
  Version:	1.1.12
  GitCommit:	v1.1.12-0-g51d5e946

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
This is a breakout of #3249 and first part of fixing our credentials management / login issues (see 3249 for details about issues, including #3072 which is the reason a significant rewrite is warranted IMHO).

The focus is this PR is solely:
- providing a CredentialsStore abstraction that takes care of any magic / legacy identifiers
- handling all registry url parsing & scheme / url monkeying in one place (RegistryURL) 

This does:
- fix #3245 and a number of other oddities (now enshrined in tests)
- significantly increase testing (+~1000 lines is just tests), both unit testing for `CredentialsStore` and `RegistryURL` parsing, and integration testing, which should hopefully give us a much firmer understanding of what is supposed to happen when
- reduce code duplication
- greatly simplify handling of registry urls
- allows fixing further login issues as a follow-up, on better grounds
- allows for future implementation of namespaced hosts login

What this does NOT:
- does not try to solve #3265 (that will come later)
- does not do anything for hosts.toml resolution (ditto)
- does not add Harbor testing (ditto)

### CODE REVIEW

**Comment by apostasie** [comment]
@fahedouch @AkihiroSuda PTAL at your convenience

File: cmd/nerdctl/login_linux_test.go [hunk 1]
```diff
@@ -14,32 +14,28 @@
...
+	"gotest.tools/v3/icmd"
+
+	"github.com/containerd/nerdctl/v2/pkg/imgutil/dockerconfigresolver"
 	"github.com/containerd/nerdctl/v2/pkg/testutil"
 	"github.com/containerd/nerdctl/v2/pkg/testutil/testca"
 	"github.com/containerd/nerdctl/v2/pkg/testutil/testregistry"
-	"gotest.tools/v3/icmd"
 )
 
-func safeRandomString(n int) string {
```
Comment (apostasie) [inline cmd/nerdctl/login_linux_test.go:34]: Moved to test_registry

File: pkg/imgutil/dockerconfigresolver/credentialsstore.go [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+		} else {
+			returnedCredentials.ServerAddress = registryURL.Host
+		}
+	}()
+
+	if !checkCredStore {
+		return returnedCredentials, nil
+	}
+
+	log.L.Debugf("retrieving credentials from store for %s", registryURL.CanonicalIdentifier())
```
Comment (apostasie) [inline pkg/imgutil/dockerconfigresolver/credentialsstore.go:141]: This is all fairly generous with debug statements.

LMK if you want a lot of that out or if they should stay.

File: pkg/imgutil/dockerconfigresolver/credentialsstore_test.go [hunk 3]
```diff
@@ -0,0 +1,384 @@
...
+				tmpDir := createTempDir(t, 0700)
+				err := os.Mkdir(filepath.Join(tmpDir, "config.json"), 0600)
+				if err != nil {
+					t.Fatal(err)
+				}
+				return tmpDir
+			},
+			errorNew: ErrUnableToInstantiate,
+		},
+		// FIXME: this test works in Lima, but does not work on github action
```
Comment (apostasie) [inline pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:125]: Mystery for the ages.

Comment (AkihiroSuda) [reply pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:125]: What is the error on GHA?

Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:125]: So, in the test conditions, which are: `DOCKER_CONFIG=/directoryxyz`, and directoryxyz contains a config.json file that is a dangling symlink.


Here is what actually happen on LIMA:

```
unable to store credentials
                rename /tmp/TestBrokenCredentialsStore705218110/008/docker-config2430087685/config.json2911426040 doesnotexist: invalid cross-device link
```

On GHA, things just work with no error.

The test assumes an error, so, locally the test "succeeds", but on GHA it "fails".

My guess to what is happening is that the docker lib finds the broken `config.json` and moves it over to create a new file. 
On GHA, the command succeeds (which is probably the expected behavior after all...), but then not on LIMA...

@AkihiroSuda do you understand why?
`invalid cross-device link` suggests this is about hard link, but this here is a symlink...

Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:125]: (I am using virtio FWIW)

Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:125]: -> https://github.com/docker/cli/blob/master/cli/config/configfile/file.go#L170-L178 <-

**Comment by apostasie** [comment]
Conflict is likely trivial. Will rebase after review, in case there are any comments or concerns to address.

**Comment by apostasie** [comment]
@AkihiroSuda we have regular network related failures on Ubuntu 20.04 / v1.6.

Symptom being `no route to host`:
```
time="2024-08-15T17:33:19Z" level=error msg="failed to call tryLoginWithRegHost" error="failed to call rh.Authorizer.Authorize: failed to fetch oauth token: Post \"[http://10.4.0.1:5000/auth\](http://10.4.0.1:5000/auth/)": dial tcp 10.4.0.1:5000: connect: no route to host" i=0
        time="2024-08-15T17:33:19Z" level=fatal msg="failed to call rh.Authorizer.Authorize: failed to fetch oauth token: Post \"[http://10.4.0.1:5000/auth\](http://10.4.0.1:5000/auth/)": dial tcp 10.4.0.1:5000: connect: no route to host"
```

We could retry on login for that condition - but I am more interested in fixing the root issue.

Do you think this is something in rootlesskit or bypass4netns?

**Comment by AkihiroSuda** [comment]
> Do you think this is something in rootlesskit or bypass4netns?

No, this seems rootful
https://github.com/containerd/nerdctl/actions/runs/10407628383/job/28823319574?pr=3293

**Comment by apostasie** [comment]
> > Do you think this is something in rootlesskit or bypass4netns?
> 
> No, this seems rootful https://github.com/containerd/nerdctl/actions/runs/10407628383/job/28823319574?pr=3293

Yes, you are right.

So, I guess when under pressure (starting / stopping many containers), networking is breaking down or is slow to converge?

File: pkg/imgutil/dockerconfigresolver/credentialsstore_test.go [hunk 4]
```diff
@@ -0,0 +1,384 @@
...
+		{
+			description: "Reading credentials from `auth` using canonical identifier",
+			username:    "username",
+			password:    "password",
+			setup: func() string {
+				content := `{
+				"auths": {
+					"someregistry:443": {
+						"auth": "dXNlcm5hbWU6cGFzc3dvcmQ="
+					}
```
Comment (AkihiroSuda) [inline pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:226]: Maybe this should be directly encoded in the test?
I wonder if some credential leakage detection tool may report a false positive for this.

File: pkg/imgutil/dockerconfigresolver/credentialsstore_test.go [hunk 5]
```diff
@@ -0,0 +1,384 @@
...
+		cs, err := NewCredentialsStore(dir)
+		if err != nil {
+			t.Fatal(err)
+		}
+
+		var af *Credentials
+		af, err = cs.Retrieve(registryURL, true)
+		assert.ErrorIs(t, err, nil)
+		assert.Equal(t, af.Username, "username")
+		assert.Equal(t, af.ServerAddress, "somehost.com:443/path?ns=someregistry.com")
```
Comment (AkihiroSuda) [inline pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:381]: `example.com` is recommended
https://www.iana.org/help/example-domains

File: pkg/testutil/testregistry/testregistry_linux.go [hunk 6]
```diff
@@ -468,3 +478,12 @@ func NewWithBasicAuth(base *testutil.Base, user, pass string, port int, tls bool
 	}
 	return NewRegistry(base, ca, port, auth, nil)
 }
+
+func SafeRandomString(n int) string {
+	b := make([]byte, n)
+	_, _ = rand.Read(b)
```
Comment (AkihiroSuda) [inline pkg/testutil/testregistry/testregistry_linux.go:484]: Should panic on err?

File: pkg/testutil/testregistry/testregistry_linux.go [hunk 7]
```diff
@@ -468,3 +478,12 @@ func NewWithBasicAuth(base *testutil.Base, user, pass string, port int, tls bool
...
+	// XXX WARNING there is something in the registry (or more likely in the way we generate htpasswd files)
+	// that is broken and does not resist truly random strings
+	// return string(b)
```
Comment (AkihiroSuda) [inline pkg/testutil/testregistry/testregistry_linux.go:487]: This comment should be removed?

File: pkg/testutil/testregistry/testregistry_linux.go (hunk 6 above)
Comment (apostasie) [reply pkg/testutil/testregistry/testregistry_linux.go:484]: Yep. Will do.

File: pkg/testutil/testregistry/testregistry_linux.go (hunk 7 above)
Comment (apostasie) [reply pkg/testutil/testregistry/testregistry_linux.go:487]: You mean, just line 487, right?
Will do.

File: pkg/imgutil/dockerconfigresolver/credentialsstore_test.go (hunk 5 above)
Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:381]: Will do.

File: pkg/imgutil/dockerconfigresolver/credentialsstore_test.go (hunk 4 above)
Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:226]: Interesting...

File: cmd/nerdctl/logout.go [hunk 8]
```diff
@@ -17,16 +17,15 @@
...
 import (
-	"fmt"
-
-	dockercliconfig "github.com/docker/cli/cli/config"
 	"github.com/spf13/cobra"
 
-	"github.com/containerd/nerdctl/v2/pkg/imgutil/dockerconfigresolver"
+	"github.com/containerd/log"
+
+	"github.com/containerd/nerdctl/v2/pkg/cmd/logout"
```
Comment (djdongjin) [inline cmd/nerdctl/logout.go:24]: containerd deps can be merged into one block?

File: pkg/testutil/testregistry/testregistry_linux.go [hunk 9]
```diff
@@ -468,3 +478,17 @@ func NewWithBasicAuth(base *testutil.Base, user, pass string, port int, tls bool
...
+	b := make([]byte, n)
+	l, err := rand.Read(b)
+	if err != nil {
+		panic(err)
+	}
+	if l != n {
+		panic(fmt.Errorf("expected %d bytes, got %d bytes", n, l))
+	}
+	// XXX WARNING there is something in the registry (or more likely in the way we generate htpasswd files)
+	// that is broken and does not resist truly random strings
```
Comment (djdongjin) [inline pkg/testutil/testregistry/testregistry_linux.go:492]: what does this mean? what does this break?

File: cmd/nerdctl/login_linux_test.go [hunk 10]
```diff
@@ -57,269 +52,485 @@ func (ag *Client) WithHostsDir(hostDirs string) *Client {
...
+		{
+			"basic",
+		},
+		{
+			"token",
+		},
+	}
+
+	for _, tc := range testCases {
+		t.Run(fmt.Sprintf("Server %s", tc.auth), func(t *testing.T) {
```
Comment (djdongjin) [inline cmd/nerdctl/login_linux_test.go:108]: I think you need to add a `tc := tc` between 107 and 108 to make sure different tests use separated tc.

File: cmd/nerdctl/login_linux_test.go [hunk 11]
```diff
@@ -57,269 +52,485 @@ func (ag *Client) WithHostsDir(hostDirs string) *Client {
...
+
+			nc.Run(base, fmt.Sprintf("localhost:%d", reg.Port)).
+				AssertOK()
+		})
+	}
+}
+
+/*
+func TestAgainstNoAuth(t *testing.T) {
+	base := testutil.NewBase(t)
```
Comment (djdongjin) [inline cmd/nerdctl/login_linux_test.go:172]: is this WIP?

File: pkg/imgutil/dockerconfigresolver/credentialsstore.go [hunk 12]
```diff
@@ -0,0 +1,182 @@
...
+	"strings"
+
+	"github.com/docker/cli/cli/config"
+	"github.com/docker/cli/cli/config/configfile"
+	"github.com/docker/cli/cli/config/types"
+
+	"github.com/containerd/log"
+)
+
+type Credentials = types.AuthConfig
```
Comment (djdongjin) [inline pkg/imgutil/dockerconfigresolver/credentialsstore.go:31]: Suggest change to `type AuthConfig = types.AuthConfig`. If we want to have a type alias we should keep the name the same.

File: pkg/imgutil/dockerconfigresolver/credentialsstore.go [hunk 13]
```diff
@@ -0,0 +1,182 @@
...
+	// Iterate through and delete them one by one
+	errs := make(map[string]error)
+	for _, serverAddress := range logoutList {
+		if err := cs.dockerConfigFile.GetCredentialsStore(serverAddress).Erase(serverAddress); err != nil {
+			errs[serverAddress] = err
+		}
+	}
+
+	// If we succeeded removing at least one, it is a success.
+	// The only error condition is if we failed removing *everything* - meaning there was no such credential information
```
Comment (djdongjin) [inline pkg/imgutil/dockerconfigresolver/credentialsstore.go:69]: nit: everything -> anything

File: pkg/imgutil/dockerconfigresolver/credentialsstore.go [hunk 14]
```diff
@@ -0,0 +1,182 @@
...
+
+	// Iterate through and delete them one by one
+	errs := make(map[string]error)
+	for _, serverAddress := range logoutList {
+		if err := cs.dockerConfigFile.GetCredentialsStore(serverAddress).Erase(serverAddress); err != nil {
+			errs[serverAddress] = err
+		}
+	}
+
+	// If we succeeded removing at least one, it is a success.
```
Comment (djdongjin) [inline pkg/imgutil/dockerconfigresolver/credentialsstore.go:68]: what's the current behavior if the removal partially succeeds (some are removed and some causes errors)?

Comment (djdongjin) [reply pkg/imgutil/dockerconfigresolver/credentialsstore.go:68]: Also if some are left un-removed. We should at least log those failed cases for awareness.

File: pkg/imgutil/dockerconfigresolver/credentialsstore.go [hunk 15]
```diff
@@ -0,0 +1,182 @@
...
+	}
+
+	return returnedCredentials, err
+}
+
+// isFileStore is an internal mock interface purely meant to help identify that the docker credential backend is a filesystem one
+type isFileStore interface {
+	IsFileStore() bool
+	GetFilename() string
+}
```
Comment (djdongjin) [inline pkg/imgutil/dockerconfigresolver/credentialsstore.go:182]: interface should be moved to the begining of the file, or at least before the implementation.

File: pkg/imgutil/dockerconfigresolver/defaults.go [hunk 16]
```diff
@@ -0,0 +1,51 @@
...
+	ErrUnableToErase       = errors.New("unable to erase credentials")
+	ErrUnableToStore       = errors.New("unable to store credentials")
+	ErrUnableToRetrieve    = errors.New("unable to retrieve credentials")
+)
+
+// Errors returned by `Parse`
+var (
+	ErrUnparsableURL     = errors.New("unparsable registry URL")
+	ErrUnsupportedScheme = errors.New("unsupported scheme in registry URL")
+)
```
Comment (djdongjin) [inline pkg/imgutil/dockerconfigresolver/defaults.go:51]: nit: are they used widely in nerdctl or by downstream? if not I prefer just returning a `errors.New(...)` directly when needed instead of predefining them.

**Review by djdongjin — COMMENTED** [review]
Left some early comments. Still have some changes left to be reviewed. thanks

File: cmd/nerdctl/logout.go (hunk 8 above)
Comment (apostasie) [reply cmd/nerdctl/logout.go:24]: The way we currently enforce linting forimports does separate `nerdctl` deps and `containerd` deps in two sections:

https://github.com/containerd/nerdctl/blob/main/Makefile#L75-L79

https://github.com/containerd/nerdctl/blob/main/hack/lint-imports.sh#L27

We can revise this of course if this is not what we prefer, but maybe in a separate PR?

File: pkg/testutil/testregistry/testregistry_linux.go (hunk 9 above)
Comment (apostasie) [reply pkg/testutil/testregistry/testregistry_linux.go:492]: Moved from another file.

Last I checked, either https://github.com/containerd/nerdctl/blob/3c7de2a7cadf0f15d2e2dbadac9475276824d74f/pkg/testutil/testregistry/testregistry_linux.go#L233-L236 was not happy with random strings, or the registry in basic auth mode was not - the end result being that authentication is failing (which is why we base64 encode the string).

File: cmd/nerdctl/login_linux_test.go (hunk 11 above)
Comment (apostasie) [reply cmd/nerdctl/login_linux_test.go:172]: Follow-up PR to this will introduce no-auth registry testing once I fix the login logic on top of this PR.

I can remove this for now if this is preferable.

LMK your preference.

File: pkg/imgutil/dockerconfigresolver/credentialsstore.go (hunk 12 above)
Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore.go:31]: Ok.
I guess I do not like `AuthConfig` as a name, but that's fine, let's keep it the same.

File: pkg/imgutil/dockerconfigresolver/credentialsstore.go (hunk 13 above)
Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore.go:69]: Yep.

File: pkg/imgutil/dockerconfigresolver/credentialsstore.go (hunk 15 above)
Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore.go:182]: It is private and only used internally in this file - there is no implementation, as it is used solely to cast docker credentials store.

In that context, do you feel it should still be moved up? (no strong opinion on my side)

File: pkg/imgutil/dockerconfigresolver/defaults.go (hunk 16 above)
Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/defaults.go:51]: > nit: are they used widely in nerdctl or by downstream?

Not yet.

The reason I like them is that they allow downstream code to actually test (`errors.Is(err, ErrXYZ)`) the error (instead of matching strings, which I find abhorrent...), and allows providing more refined user feedback based on these (or decide to ignore certain errors in certain circumstances).

This of course applies to testing as well (as a nice benefit, where we can actually verify what error is being returned in integration testing without having to duplicate strings again).

LMK if you feel strongly about these and of course open to amending.

**Comment by apostasie** [comment]
> Left some early comments. Still have some changes left to be reviewed. thanks

Thanks a lot @djdongjin 
Really appreciate the review.
I answered you in the comments - addressed some with the latest push - provided clarification on others - so, let me know in there how you feel, and I will look for further comments from you when you will be done reviewing.

File: pkg/imgutil/dockerconfigresolver/defaults.go (hunk 16 above)
Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/defaults.go:51]: Overall motivation for me is that our error-ing is not great right now (see #3302 for example), and that is generally in the codebase.

We tend to just bubble-up system errors that are meaningless or even misleading for the user (#3197) - and at best, makes it hard to pinpoint for us when reading bug reports.

This is obviously a very large endeavor to change this situation overall, and it might take a few iterations to come up with a reasonable set of errors and informative enough wrapping, but I believe it is essential.

**Comment by apostasie** [comment]
Failure are unrelated:
- ComposeUp random fail
- networking fluke: `dial tcp 10.4.0.1:5000: connect: no route to host" i=0`
- docker inability to pull an image (might be for the same reason as ^)

File: pkg/imgutil/dockerconfigresolver/credentialsstore.go (hunk 14 above)
Comment (djdongjin) [reply pkg/imgutil/dockerconfigresolver/credentialsstore.go:68]: I think it's okay as long as it doesn't regress existing behaviors

Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore.go:68]: Agreed. I do trust our current testing (to some extent). 
I will make sure to further extend testing for these things when I will move to part 2 (some work in progress in there: - not ready for review at all, but that gives an idea -> #3249)

**Review by djdongjin — COMMENTED** [review]
I probably need more time to review some of the changes, as it's a bit difficut to identify which are logic changes, and which are refactors/code relocation/etc.

Also some suggestions on reducing PR size:

- Add UTs first in a separate PR or commit if UT itself has a lot of changes. If you're trying to fix something and the UT helps reproduce it, you can add and skip that UT (or just add it in a later PR).
- Do refactor or move code around in a separate PR: it's difficult to identify a small change if it's mixed with a refactor.
- You can use tools like https://github.com/modularml/stack-pr to make small PRs and make a big change incrementally.

**Comment by apostasie** [comment]
> I probably need more time to review some of the changes, as it's a bit difficut to identify which are logic changes, and which are refactors/code relocation/etc.

That is fine.
I do appreciate my latest PRs are more sizable - and certainly understand reviewing these things is significant work - really grateful for that @djdongjin.

> 
> Also some suggestions on reducing PR size:
> 
> * Add UTs first in a separate PR or commit if UT itself has a lot of changes. If you're trying to fix something and the UT helps reproduce it, you can add and skip that UT (or just add it in a later PR).
> * Do refactor or move code around in a separate PR: it's difficult to identify a small change if it's mixed with a refactor.
> * You can use tools like https://github.com/modularml/stack-pr to make small PRs and make a big change incrementally.

Will definitely look into stack-pr - great tips, thanks.

Let me see if I can massage my two other "big-ish" PRs into something more amenable to review.

Meanwhile, we can just stay focused on this one - and also #3362 would be nice to get if you have a minute <- it is a small one! Pinky swear! :-)

**Comment by apostasie** [comment]
Latest CI fail is the usual `TestIPFSComposeUp` - this one fails more often that it succeeds.

Unfortunately, I couldn't figure out so far (#3305) - it is a massive PITA.

Anyone familiar with IPFS around?

**Comment by AkihiroSuda** [comment]
> IPFS

cc @ktock

**Comment by apostasie** [comment]
@AkihiroSuda could you poke the CI for the flaky IPFS 20.04/1.6 run?

File: pkg/imgutil/dockerconfigresolver/credentialsstore.go (hunk 12 above)
Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore.go:31]: Actually, do you mind if we keep `Credentials`?
`AuthConfig` is really a bad name... If anything, it does evoke https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/system-level_authentication_guide/authconfig-install#authconfig-install instead of what it really is... just credentials...

It also "makes sense" that the `CredentialsStore` would store `Credentials`.

**Comment by apostasie** [comment]
Rebased. Pending green CI.

File: cmd/nerdctl/login/login_linux_test.go [hunk 17]
```diff
@@ -14,11 +14,13 @@
    limitations under the License.
 */
 
+// https://docs.docker.com/reference/cli/dockerd/#insecure-registries
+// Local registries, whose IP address falls in the 127.0.0.0/8 range, are automatically marked as insecure as of Docker 1.3.2.
+// It isn't recommended to rely on this, as it may change in the future.
+// "--insecure" means that either the certificates are untrusted, or that the protocol is plain http
 package login
```
Comment (AkihiroSuda) [inline cmd/nerdctl/login/login_linux_test.go:21]: The godoc comment should start with "Package login ..."

File: pkg/imgutil/dockerconfigresolver/credentialsstore_test.go (hunk 3 above)
Comment (AkihiroSuda) [reply pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:127]: Could you add the error to the code comments?

File: pkg/imgutil/dockerconfigresolver/registryurl.go [hunk 18]
```diff
@@ -0,0 +1,147 @@
...
+		address = dockerIndexServer
+	}
+	// If it has no scheme, slap one just so we can parse
+	if !strings.Contains(address, "://") {
+		address = fmt.Sprintf("%s://%s", schemeHTTPS, address)
+	}
+	// Parse it
+	u, err := url.Parse(address)
+	if err != nil {
+		log.L.Debug("unparsable - giving up")
```
Comment (AkihiroSuda) [inline pkg/imgutil/dockerconfigresolver/registryurl.go:45]:
```suggestion
		log.L.WithError(err).Debug("unparsable - giving up")
```

File: pkg/imgutil/dockerconfigresolver/registryurl.go [hunk 19]
```diff
@@ -0,0 +1,147 @@
...
+	if rn.Scheme == string(schemeHTTPS) && rn.Hostname() == "index.docker.io" && rn.Path == "/v1/" && rn.Port() == standardHTTPSPort ||
+		rn.URL.String() == dockerIndexServer {
+		log.L.Debugf("assimilated to docker %q", dockerIndexServer)
+		return dockerIndexServer
+	}
+	// Otherwise, for anything else, we use the hostname+port part
+	identifier := rn.Host
+	// If this is a namespaced entry, wrap it, and slap the path as well, as hosts are allowed to be non-compliant
+	if rn.Namespace != nil {
+		log.L.Debug("namespaced identifier")
```
Comment (AkihiroSuda) [inline pkg/imgutil/dockerconfigresolver/registryurl.go:96]: Do we still need these debug logs? Maybe too verbose.

Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/registryurl.go:96]: https://github.com/containerd/nerdctl/pull/3293#discussion_r1713121552

We can remove most of them.
Let me do that asap.

**Comment by apostasie** [comment]
Rebased.
Debug statement removed.
Pending CI.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

File: pkg/imgutil/dockerconfigresolver/credentialsstore_test.go (hunk 3 above)
Comment (apostasie) [reply pkg/imgutil/dockerconfigresolver/credentialsstore_test.go:127]: Update: testing again with latest Lima (using your fork, actually) on Ubuntu 24.04, and it just works...

Unclear to me what that was - maybe older ubuntu, or maybe something in Lima fixed this.

Will enable the test then.

**Review by djdongjin — APPROVED** [review]
LGTM, thanks
