### PR TITLE
Fix bash completion of volume rm

### LINKED ISSUE #2474: Bash completion doesn't work for `nerdctl volume rm <TAB>`

### PR DESCRIPTION
**Pull request by yankay**
Support the bash completion when there are not flag of `size` to fix #2474

### CODE REVIEW

File: cmd/nerdctl/volume_list.go [hunk 1]
```diff
@@ -87,7 +87,7 @@ func volumeLsAction(cmd *cobra.Command, args []string) error {
 func getVolumes(cmd *cobra.Command, globalOptions types.GlobalCommandOptions) (map[string]native.Volume, error) {
 	volumeSize, err := cmd.Flags().GetBool("size")
 	if err != nil {
-		return nil, err
+		volumeSize = false
```
Comment (AkihiroSuda) [inline cmd/nerdctl/volume_list.go:90]: Could you add a comment line to explain this?

Comment (yankay) [reply cmd/nerdctl/volume_list.go:91]: Thanks @AkihiroSuda 
The comment line has been added.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
