### PR TITLE
Fix block issue for `stats -a` command when there is dead container

### LINKED ISSUE #1415: -a for stats command is not working when there is an exited container
### Description

When using `stats` command with -a, no output is generated and the terminal stuck there forever.

```
~/Desktop ✓ ➭ ./_output/lima/bin/limactl shell default
[user@lima-default default]$
```

```
[user@lima-default default]$ nerdctl ps -a
CONTAINER ID    IMAGE                              COMMAND                CREATED         STATUS                     PORTS    NAMES
371ecb033c10    docker.io/library/alpine:latest    "sh -c nc -l -p 80"    34 hours ago    Up                                  alpine-371ec
a091b2be8eb0    docker.io/library/alpine:latest    "/bin/sh"              34 hours ago    Exited (0) 34 hours ago             alpine-a091b
```

`[user@lima-default default]$ nerdctl stats -a`

### Steps to reproduce the issue

1. create and shell into lima instance (Fedora).
2. run nerdctl stats -a.
3. The terminal stuck there and doesn't generate any output.

### Describe the results you received and expected

Received: no output is generated and terminal stuck forever.

Expected: Able to see the usage statistics for all the containers.

### What version of nerdctl are you using?

```
[user@lima-default default]$ nerdctl -v
nerdctl version 0.22.0
```

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

_No response_

### Host information

```
~/Desktop ✓ ➭ uname -a
Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
```

### PR DESCRIPTION
**Pull request by Zheaoli**
Fix #1415 

Signed-off-by: Zheao.Li <me@manjusaka.me>

### CODE REVIEW

File: cmd/nerdctl/stats.go [hunk 1]
```diff
@@ -465,8 +468,10 @@ func collect(cmd *cobra.Command, s *statsutil.Stats, waitFirst *sync.WaitGroup,
 			}
 		case err := <-u:
 			if err != nil {
-				s.SetError(err)
-				continue
+				if !strings.Contains(err.Error(), "no running task found") {
+					s.SetError(err)
+					continue
+				}
```
Comment (fahedouch) [inline cmd/nerdctl/stats.go:474]: this should not happen, because container are removed once received the delete event: https://github.com/containerd/nerdctl/blob/master/cmd/nerdctl/stats.go#L229-L245

Comment (Zheaoli) [reply cmd/nerdctl/stats.go:474]: Nope, the origin code is not cover the existing exited container if we do not handle this, there will be infinite loop here

Comment (fahedouch) [reply cmd/nerdctl/stats.go:474]: in this case we should handle exist event https://pkg.go.dev/github.com/containerd/containerd/api/events#TaskExit 
May be pause event too

File: cmd/nerdctl/stats.go [hunk 2]
```diff
@@ -318,6 +318,9 @@ func statsAction(cmd *cobra.Command, args []string) error {
 		}
 
 		for _, c := range ccstats {
+			if c.ID == "" {
```
Comment (fahedouch) [inline cmd/nerdctl/stats.go:321]: is it possible to have empty id ?

Comment (Zheaoli) [reply cmd/nerdctl/stats.go:321]: container with empty id is useless here, I guess

File: cmd/nerdctl/stats.go (hunk 1 above)
Comment (fahedouch) [reply cmd/nerdctl/stats.go:474]: we are dealing with container fetched through containerd API,  I believe that we can catch these events

Comment (fahedouch) [reply cmd/nerdctl/stats.go:474]: - Already exited container should not be added to the `cStats ` 
- When container exits it should be removed from `cStats` using the callback event

Comment (Zheaoli) [reply cmd/nerdctl/stats.go:474]: > * Already exited container should not be added to the `cStats`

this is a little bit different with Docker, Docker will list all exited container metric with nil or 0 in `docker stats -a`

Comment (fahedouch) [reply cmd/nerdctl/stats.go:474]: I don't see any benefit behind leaving nil entries. We know in advance that exited containers have nil entry values

Comment (Zheaoli) [reply cmd/nerdctl/stats.go:474]: @AkihiroSuda @fahedouch

Comment (fahedouch) [reply cmd/nerdctl/stats.go:474]: I am ok with being compatible with docker and displaying entries with nil values for exited containers and without displaying  error message `no running task found`

File: cmd/nerdctl/stats_linux_test.go [hunk 3]
```diff
@@ -32,9 +33,13 @@ func TestStats(t *testing.T) {
 		t.Skip("test skipped for rootless containers on cgroup v1")
 	}
 	testContainerName := testutil.Identifier(t)
+	randomTestContainerName := fmt.Sprintf("%s-random", testContainerName)
```
Comment (AkihiroSuda) [inline cmd/nerdctl/stats_linux_test.go:36]: What does "random" mean in this context?

File: cmd/nerdctl/stats.go (hunk 1 above)
Comment (AkihiroSuda) [reply cmd/nerdctl/stats.go:474]: Docker-compatible behavior is preferable, but if it is difficult we can just document it and call it a day

File: cmd/nerdctl/stats.go (hunk 2 above)
Comment (fahedouch) [reply cmd/nerdctl/stats.go:321]: We cannot have an empty ID.
But it looks like `c.ID`  is useless in the `StatsEntry` struct . It looks like this two fields are the same :
`Container` : https://github.com/containerd/nerdctl/blob/master/pkg/statsutil/stats.go#L31
`ID` : https://github.com/containerd/nerdctl/blob/master/pkg/statsutil/stats.go#L29

we may keep only one identifier no need to have a duplicate identifier field

File: cmd/nerdctl/stats_linux_test.go (hunk 3 above)
Comment (Zheaoli) [reply cmd/nerdctl/stats_linux_test.go:36]: Just typo, I will fix it

File: cmd/nerdctl/stats_linux_test.go [hunk 4]
```diff
@@ -32,9 +33,13 @@ func TestStats(t *testing.T) {
...
 
 	base := testutil.NewBase(t)
 	defer base.Cmd("rm", "-f", testContainerName).Run()
+	defer base.Cmd("rm", "-f", randomTestContainerName).Run()
+	base.Cmd("run", "-d", "--name", randomTestContainerName, testutil.NginxAlpineImage).AssertOK()
+	base.Cmd("kill", randomTestContainerName).AssertOK()
```
Comment (fahedouch) [inline cmd/nerdctl/stats_linux_test.go]: no need to kill this will automatically exit https://github.com/containerd/nerdctl/pull/1416/files#diff-c1ea01872000c1855f6cfc8180843ee41c96d0f5d54cc479681a96956caf6a58R41

File: cmd/nerdctl/stats.go (hunk 2 above)
Comment (Zheaoli) [reply cmd/nerdctl/stats.go:321]: > we may keep only one identifier no need to have a duplicate identifier field. This can be in other PR

Yes!



> We cannot have an empty ID.

Nope, after https://github.com/containerd/nerdctl/pull/1416/files#diff-8541fa08e70d092bb039071593918dac552c3cbf1088d15e71d0f6117ad4b249R471-R474, we may get empty ID here because of https://github.com/containerd/nerdctl/blob/master/cmd/nerdctl/stats.go#L408-L409

File: cmd/nerdctl/stats_linux_test.go [hunk 5]
```diff
@@ -32,9 +33,13 @@ func TestStats(t *testing.T) {
 		t.Skip("test skipped for rootless containers on cgroup v1")
 	}
 	testContainerName := testutil.Identifier(t)
+	exitedTestContainerName := fmt.Sprintf("%s-exited", testContainerName)
 
 	base := testutil.NewBase(t)
 	defer base.Cmd("rm", "-f", testContainerName).Run()
+	defer base.Cmd("rm", "-f", exitedTestContainerName).Run()
+	base.Cmd("run", "--name", exitedTestContainerName, testutil.AlpineImage, "echo", "'exited'").AssertOK()
+	base.Cmd("kill", exitedTestContainerName).AssertOK()
```
Comment (fahedouch) [inline cmd/nerdctl/stats_linux_test.go:42]: no need to kill this container is already exited https://github.com/containerd/nerdctl/pull/1416/files#diff-c1ea01872000c1855f6cfc8180843ee41c96d0f5d54cc479681a96956caf6a58R41

File: cmd/nerdctl/stats.go [hunk 6]
```diff
@@ -465,8 +468,10 @@ func collect(cmd *cobra.Command, s *statsutil.Stats, waitFirst *sync.WaitGroup,
 			}
 		case err := <-u:
 			if err != nil {
-				s.SetError(err)
-				continue
+				if !strings.Contains(err.Error(), "no running task found") {
```
Comment (fahedouch) [inline cmd/nerdctl/stats.go:471]: plz use `errdefs.IsNotFound(err)` from  `github.com/containerd/containerd/errdefs`

File: cmd/nerdctl/stats_linux_test.go [hunk 7]
```diff
@@ -32,9 +33,12 @@ func TestStats(t *testing.T) {
 		t.Skip("test skipped for rootless containers on cgroup v1")
 	}
 	testContainerName := testutil.Identifier(t)
+	exitedTestContainerName := fmt.Sprintf("%s-exited", testContainerName)
 
 	base := testutil.NewBase(t)
 	defer base.Cmd("rm", "-f", testContainerName).Run()
+	defer base.Cmd("rm", "-f", exitedTestContainerName).Run()
+	base.Cmd("run", "--name", exitedTestContainerName, testutil.AlpineImage, "echo", "'exited'").AssertOK()
```
Comment (fahedouch) [inline cmd/nerdctl/stats_linux_test.go:41]: can you plz check that  `nerdctl stats` is a generating  some output when a container exist ?

**Comment by fahedouch** [comment]
@Zheaoli test is failing 
```=== CONT  TestStats
    stats_linux_test.go:44: assertion failed: 
        Command:  /usr/local/bin/nerdctl --namespace=nerdctl-test stats --no-stream
        ExitCode: 0
        Stdout:   CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O         BLOCK I/O   PIDS
        7203ab7e8571   nerdctl-test   0.00%     432KiB / 8EiB       0.00%     1.89kB / 472B   0B / 0B     2
        e56aa631fe9d   nerdctl-test   0.00%     288KiB / 8EiB       0.00%     90B / 292B      0B / 0B     1
        
        Stderr:   
        
        Failures:
        Expected stdout to contain "nerdctl-teststats"
```

**Comment by Zheaoli** [comment]
> @Zheaoli test is failing
> 
> ```
>     stats_linux_test.go:44: assertion failed: 
>         Command:  /usr/local/bin/nerdctl --namespace=nerdctl-test stats --no-stream
>         ExitCode: 0
>         Stdout:   CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O         BLOCK I/O   PIDS
>         7203ab7e8571   nerdctl-test   0.00%     432KiB / 8EiB       0.00%     1.89kB / 472B   0B / 0B     2
>         e56aa631fe9d   nerdctl-test   0.00%     288KiB / 8EiB       0.00%     90B / 292B      0B / 0B     1
>         
>         Stderr:   
>         
>         Failures:
>         Expected stdout to contain "nerdctl-teststats"
> ```

Seems odd, the rootless test has been passed

**Comment by Zheaoli** [comment]
> > @Zheaoli test is failing
> > ```
> >     stats_linux_test.go:44: assertion failed: 
> >         Command:  /usr/local/bin/nerdctl --namespace=nerdctl-test stats --no-stream
> >         ExitCode: 0
> >         Stdout:   CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT   MEM %     NET I/O         BLOCK I/O   PIDS
> >         7203ab7e8571   nerdctl-test   0.00%     432KiB / 8EiB       0.00%     1.89kB / 472B   0B / 0B     2
> >         e56aa631fe9d   nerdctl-test   0.00%     288KiB / 8EiB       0.00%     90B / 292B      0B / 0B     1
> >         
> >         Stderr:   
> >         
> >         Failures:
> >         Expected stdout to contain "nerdctl-teststats"
> > ```
> 
> Seems odd, the rootless test has been passed

OK I find the problems here, https://github.com/containerd/nerdctl/blob/main/pkg/statsutil/stats.go#L150-L158

File: cmd/nerdctl/stats_linux_test.go [hunk 8]
```diff
@@ -32,11 +33,17 @@ func TestStats(t *testing.T) {
 		t.Skip("test skipped for rootless containers on cgroup v1")
 	}
 	testContainerName := testutil.Identifier(t)
+	exitedTestContainerName := fmt.Sprintf("%s-exited", testContainerName)
+	if len(testContainerName) > 12 {
+		testContainerName = testContainerName[:12]
```
Comment (fahedouch) [inline cmd/nerdctl/stats_linux_test.go:38]: `t.Parallel()` is a bit risky here, because we are truncating the `testContainerName`, it may accidentally delete other test container

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
https://github.com/containerd/nerdctl/pull/1416/files#r1029303518

**Comment by fahedouch** [comment]
LGTM on green CI

File: cmd/nerdctl/stats_linux_test.go [hunk 9]
```diff
@@ -25,18 +26,23 @@ import (
...
 func TestStats(t *testing.T) {
-	t.Parallel()
 	// this comment is for `nerdctl ps` but it also valid for `nerdctl stats` :
 	// https://github.com/containerd/nerdctl/pull/223#issuecomment-851395178
 	if rootlessutil.IsRootless() && infoutil.CgroupsVersion() == "1" {
 		t.Skip("test skipped for rootless containers on cgroup v1")
 	}
 	testContainerName := testutil.Identifier(t)
+	exitedTestContainerName := fmt.Sprintf("%s-exited", testContainerName)
+	if len(testContainerName) > 12 {
```
Comment (AkihiroSuda) [inline cmd/nerdctl/stats_linux_test.go:36]: Isn't this always true? `len("nerdctl-teststats-exited") = 24`.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
