### PR TITLE
Docker v26 compatibility & test fixes

### LINKED ISSUE #3088: `test-integration-docker-compatibility` began to fail on June 14 (Docker was upgraded from v24 to v26)
https://github.com/containerd/nerdctl/actions/runs/9505243515/job/26199694005

```
=== RUN   TestCreateWithMACAddress
=== RUN   TestCreateWithMACAddress/nerdctl-testcreatewithmacaddress_container:nerdctl-testcreatewithmacaddress_0_network:host_expect:conflicting_options
=== NAME  TestCreateWithMACAddress
    container_create_linux_test.go:117: assertion failed: expression is false: strings.Contains(res.Combined(), s): expected output to contain "conflicting options": "ebae262bcb90e6230c6952f6759421b5a30647086a81bcc270f5f752df514d19\n"
=== NAME  TestCreateWithMACAddress/nerdctl-testcreatewithmacaddress_container:nerdctl-testcreatewithmacaddress_0_network:host_expect:conflicting_options
    testing.go:1576: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
--- FAIL: TestCreateWithMACAddress (0.55s)
    --- FAIL: TestCreateWithMACAddress/nerdctl-testcreatewithmacaddress_container:nerdctl-testcreatewithmacaddress_0_network:host_expect:conflicting_options (0.05s)
```

```
--- FAIL: TestRunContainerWithStaticIP (0.99s)
    --- PASS: TestRunContainerWithStaticIP/{ip:172.0.0.2_shouldSuccess:true_useNetwork:true_checkTheIPAddress:true} (0.46s)
    --- PASS: TestRunContainerWithStaticIP/{ip:192.0.0.2_shouldSuccess:false_useNetwork:true_checkTheIPAddress:false} (0.07s)
    --- FAIL: TestRunContainerWithStaticIP/{ip:10.4.0.2_shouldSuccess:true_useNetwork:false_checkTheIPAddress:false} (0.07s)
```

```
=== RUN   TestRunContainerWithMACAddress
    container_run_network_linux_test.go:487: assertion failed: res.ExitCode is 0
--- FAIL: TestRunContainerWithMACAddress (0.70s)
```

```
=== RUN   TestNetworkInspect
    network_inspect_test.go:48: assertion failed: res.ExitCode is not exitCode: Error response from daemon: invalid network config:
        invalid ip-range 10.24.24.1/25: it should be 10.24.24.0/25
        
--- FAIL: TestNetworkInspect (0.07s)
```

Docker was upgraded from v24 to v26 in https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240609.1

### PR DESCRIPTION
**Pull request by apostasie**
This fix #3088 

So far, the issues were:
- [x] docker is now pickier on ip ranges
- [x] WithMacAddress: both host networking and container networking now  apparently allow passing a mac address, though it is a no-op AFAIK - the docker daemon still disallows it - hypothesis is that the new cli just discard the option silently. Anyhow, nerdctl code has been changed to align with that (somewhat abhorrent) behavior and tests have been adjusted
- [x] TestRunContainerWithStaticIP: see #3101  - I am disabling the test for now (which was already broken by the way, since it wasn't testing anything for docker) - we might re-enable pending discussion in the linked ticket

### CODE REVIEW

File: cmd/nerdctl/container_run_network_linux_test.go [hunk 1]
```diff
@@ -453,42 +458,62 @@ func TestRunContainerWithMACAddress(t *testing.T) {
...
+	defaultMac := cmd.Run().Stdout()
+
+	passedMac := "we expect the generated mac on the output"
 	tests := []struct {
 		Network string
 		WantErr bool
 		Expect  string
 	}{
-		{"host", true, "conflicting options"},
-		{"none", true, "can't open '/sys/class/net/eth0/address'"},
```
Comment (apostasie) [inline cmd/nerdctl/container_run_network_linux_test.go:470]: Testing this is problematic as it does not seem to be there at all with rootless.
Replacing this by calling on `ip addr`.

File: .github/workflows/test.yml [hunk 2]
```diff
@@ -264,10 +263,10 @@ jobs:
...
-          curl -OSL https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce_24.0.9-1~ubuntu.22.04~jammy_amd64.deb
-          curl -OSL https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce-cli_24.0.9-1~ubuntu.22.04~jammy_amd64.deb
-          curl -OSL https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-buildx-plugin_0.13.1-1~ubuntu.22.04~jammy_amd64.deb
-          curl -OSL https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-compose-plugin_2.25.0-1~ubuntu.22.04~jammy_amd64.deb
+          curl -OSL https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce_26.1.4-1~ubuntu.22.04~jammy_amd64.deb
+          curl -OSl https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce-cli_26.1.4-1~ubuntu.22.04~jammy_amd64.deb
+          curl -OSL https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-buildx-plugin_0.14.1-1~ubuntu.22.04~jammy_amd64.deb
+          curl -OSL https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-compose-plugin_2.27.1-1~ubuntu.22.04~jammy_amd64.deb
```
Comment (apostasie) [inline .github/workflows/test.yml:269]: Also updating the plugins

File: cmd/nerdctl/container_create_linux_test.go [hunk 3]
```diff
@@ -57,69 +58,81 @@ func TestCreateWithMACAddress(t *testing.T) {
...
+		Run().Stdout()
+
+	passedMac := "we expect the generated mac on the output"
 	tests := []struct {
 		Network string
 		WantErr bool
 		Expect  string
 	}{
-		{"host", true, "conflicting options"},
-		{"none", true, "can't open '/sys/class/net/eth0/address'"},
```
Comment (apostasie) [inline cmd/nerdctl/container_create_linux_test.go:74]: Using /sys/class/net is problematic as it does not seem to exist for rootless in any case. Replacing with a call to ip addr to retrieve the mac address instead.

File: cmd/nerdctl/container_create_linux_test.go [hunk 4]
```diff
@@ -57,69 +58,81 @@ func TestCreateWithMACAddress(t *testing.T) {
...
 			if !test.WantErr {
-				cmd.AssertOK()
+				assert.Assert(t, res.ExitCode == 0, "Command should have succeeded", res.Combined())
+				// This is currently blocked by: https://github.com/containerd/nerdctl/pull/3104
+				// res = base.Cmd("start", "-i", containerName).
+				//	CmdOption(testutil.WithStdin(strings.NewReader("ip addr show eth0 | grep ether | awk '{printf $2}'"))).Run()
 				base.Cmd("start", containerName).AssertOK()
-				cmd = base.Cmd("logs", containerName)
-				cmd.AssertOK()
-				cmd.AssertOutContains(test.Expect)
```
Comment (apostasie) [inline cmd/nerdctl/container_create_linux_test.go:101]: Removing faulty logic resulting in multiple repeat executions.

**Comment by apostasie** [comment]
Besides a Windows failure that seems unrelated (can you poke it?), the CI is green on this.

As indicated in the initial comment, issues are relatively minor changes in behavior of the docker cli, that we are now aligning with, for better or worse (except for the behavior on ip + bridge which is now documented in #3106).

Tests have also been cleaned up slightly as some assumptions were wrong (availability of /sys/net, and multiple execution through testutil assert helpers), the logic has been simplified a bit, and they are now parallelized.

@AkihiroSuda and crew, PTAL at your convenience.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
