### PR TITLE
ParentMain/nsenter: do not fail if getwd errors

### LINKED ISSUE #3328: getwd: should we really hard fail?
### Description

Investigating https://github.com/rootless-containers/usernetes/pull/327

Current intuition is that the error comes from:
https://github.com/containerd/nerdctl/blob/main/pkg/rootlessutil/parent_linux.go#L87

Do we really need to hard-fail when we have no cwd?

Put otherwise: is it important that nsenter gets `-w` set no matter what (especially in the case where cwd does not exist), or can we just "not set" `-w` when getwd fails?

cc @AkihiroSuda 

### Steps to reproduce the issue

```
mkdir foo
cd foo
rmdir ../foo
nerdctl container run -d --name foo debian sleep Inf
FATA[0000] getwd: no such file or directory
```

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
To fix #3328 

It is not clear to me if there would be side-effects to this.

nsenter specialists opinion highly welcome.

### CODE REVIEW

**Comment by apostasie** [comment]
Definitely not working. Reverting to draft.

File: pkg/rootlessutil/parent_linux.go [hunk 1]
```diff
@@ -84,25 +84,29 @@ func ParentMain(hostGatewayIP string) error {
...
+		"-r/", // root dir (busybox nsenter wants this to be explicitly specified),
+	}
+
+	// Only append wd if we do have a working dir
+	// - https://github.com/rootless-containers/usernetes/pull/327
+	// - https://github.com/containerd/nerdctl/issues/3328
+	wd, err := os.Getwd()
+	if err == nil {
+		args = append(args, "-w"+wd)
+	}
```
Comment (AkihiroSuda) [inline pkg/rootlessutil/parent_linux.go:103]: Non-nil err should be still warned?

File: pkg/rootlessutil/parent_linux.go [hunk 2]
```diff
@@ -84,25 +84,29 @@ func ParentMain(hostGatewayIP string) error {
...
-	}
-
 	// FIXME: remove dependency on `nsenter` binary
 	arg0, err := exec.LookPath("nsenter")
 	if err != nil {
 		return err
 	}
 	// args are compatible with both util-linux nsenter and busybox nsenter
 	args := []string{
-		"-r/",     // root dir (busybox nsenter wants this to be explicitly specified),
```
Comment (AkihiroSuda) [inline pkg/rootlessutil/parent_linux.go:99]: Was this removed?

File: pkg/rootlessutil/parent_linux.go (hunk 1 above)
Comment (apostasie) [reply pkg/rootlessutil/parent_linux.go:105]: Done.

**Comment by apostasie** [comment]
Comment addressed.
CI is green.

File: pkg/rootlessutil/parent_linux.go [hunk 3]
```diff
@@ -84,25 +84,31 @@ func ParentMain(hostGatewayIP string) error {
...
-		"--preserve-credentials",
+		"-r/", // root dir (busybox nsenter wants this to be explicitly specified),
+	}
+
+	// Only append wd if we do have a working dir
+	// - https://github.com/rootless-containers/usernetes/pull/327
+	// - https://github.com/containerd/nerdctl/issues/3328
+	wd, err := os.Getwd()
+	if err != nil {
+		log.L.Warn("unable to determine working directory")
```
Comment (djdongjin) [inline pkg/rootlessutil/parent_linux.go:102]: can we print the err as well in the log?

Comment (AkihiroSuda) [reply pkg/rootlessutil/parent_linux.go:102]: What log?

Comment (djdongjin) [reply pkg/rootlessutil/parent_linux.go]: This part `.WithError(err)`. @apostasie just added in the latest revision.

**Review by djdongjin — COMMENTED** [review]
LGTM, thanks. btw did you verify if this resolves the issue? i.e. the repro in https://github.com/containerd/nerdctl/issues/3328 works now:

```shell
mkdir foo
cd foo
rmdir ../foo
nerdctl container run -d --name foo debian sleep Inf
FATA[0000] getwd: no such file or directory
```

**Comment by apostasie** [comment]
> LGTM, thanks. btw did you verify if this resolves the issue? i.e. the repro in #3328 works now:
> 
> ```shell
> mkdir foo
> cd foo
> rmdir ../foo
> nerdctl container run -d --name foo debian sleep Inf
> FATA[0000] getwd: no such file or directory
> ```

Yes, it does fix the issue.
I am just mildly concerned about the behavior of nsenter in such a condition, but then... this is (somewhat) abnormal to start with.

File: pkg/rootlessutil/parent_linux.go [hunk 4]
```diff
@@ -84,25 +84,31 @@ func ParentMain(hostGatewayIP string) error {
...
+	}
+
+	// Only append wd if we do have a working dir
+	// - https://github.com/rootless-containers/usernetes/pull/327
+	// - https://github.com/containerd/nerdctl/issues/3328
+	wd, err := os.Getwd()
+	if err != nil {
+		log.L.WithError(err).Warn("unable to determine working directory")
+	} else {
+		args = append(args, "-w"+wd)
```
Comment (fahedouch) [inline pkg/rootlessutil/parent_linux.go:104]: IMO we may even set the working directory after nsenter with `--wdns`

**Review by djdongjin — APPROVED** [review]
LGTM, thanks

File: pkg/rootlessutil/parent_linux.go (hunk 4 above)
Comment (apostasie) [reply pkg/rootlessutil/parent_linux.go:104]: To what path?

Comment (apostasie) [reply pkg/rootlessutil/parent_linux.go:104]: ah - you mean, in case getwd does NOT error, right?

Honestly, I would rather focus efforts on re-exec-ing instead of tweaking nsenter.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
