### PR TITLE
Lint for other platforms

### LINKED ISSUE #3382: lint broken on windows and freebsd
### Description

`GOOS=windows make lint` or `GOOS=freebsd make lint` are currently broken.

This is mostly about tests - but some minor stuff in main code as well.

We currently do not tests these on the CI.

Questions:
- should we care?
- if yes, do we want it enabled on the CI as well?

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
Fix #3382 and enforce linting checks for other platforms.

This is trivial changes to appease the linter gods.

### CODE REVIEW

File: cmd/nerdctl/container/container_cp_unix.go [hunk 1]
```diff
@@ -1,3 +1,5 @@
+//go:build unix
```
Comment (AkihiroSuda) [inline cmd/nerdctl/container/container_cp_unix.go]: Isn't this implied by the file name suffix?

**Review by AkihiroSuda — APPROVED** [review]
Thanks

File: cmd/nerdctl/container/container_cp_unix.go (hunk 1 above)
Comment (apostasie) [reply cmd/nerdctl/container/container_cp_unix.go]: I think only GOOS/GOARCH values are recognized as "magic" suffix implying a build tag.

IIRC they tried to introduce the same semantic for `_unix` but it backfired and broke a bunch of projects so they only added the `// go:build unix` directive but not the file matching.
