### PR TITLE
Volume QA, "volume remove" (fixes and tests)

### LINKED ISSUE #3124: docker vs. nerdctl: volume behavior differences
### Description

Repeat create
```
docker volume create foo
docker volume create foo
nerdctl volume create foo
nerdctl volume create foo
```

Multiple remove with non-existent volume
```
docker volume create foo
docker volume remove bar foo
nerdctl volume create foo
nerdctl volume remove bar foo
```

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
This fixes #3124 and a few other discrepancies between docker and nerdctl.

This also expands testing significantly.

Outside of the tests, I will comment inline as to "why" certain changes.

### CODE REVIEW

File: pkg/cmd/volume/rm.go [hunk 1]
```diff
@@ -44,23 +46,28 @@ func Remove(ctx context.Context, client *containerd.Client, volumes []string, op
 
 	var volumenames []string // nolint: prealloc
 	for _, name := range volumes {
-		volume, err := volStore.Get(name, false)
```
Comment (apostasie) [inline pkg/cmd/volume/rm.go:47]: This section serves no purpose, and does make things racy.

File: pkg/cmd/volume/rm.go [hunk 2]
```diff
@@ -44,23 +46,28 @@ func Remove(ctx context.Context, client *containerd.Client, volumes []string, op
...
-		}
-		if _, ok := usedVolumes[volume.Name]; ok {
+		if _, ok := usedVolumes[name]; ok {
 			return fmt.Errorf("volume %q is in use", name)
 		}
 		volumenames = append(volumenames, name)
 	}
-	removedNames, err := volStore.Remove(volumenames)
+	// if err is set, this is a hard filesystem error
+	removedNames, errs, err := volStore.Remove(volumenames)
```
Comment (apostasie) [inline pkg/cmd/volume/rm.go:55]: Note that on such a dramatic error (filesystem failure typically), we do not report whether and which volumes were (possibly) successfully removed.
I think it is fine - the only reason this would happen is if `os.RemoveAll` would err.

File: pkg/cmd/volume/rm.go [hunk 3]
```diff
@@ -44,23 +46,28 @@ func Remove(ctx context.Context, client *containerd.Client, volumes []string, op
...
 	if err != nil {
 		return err
 	}
+	// Otherwise, output on stdout whatever was successful
```
Comment (apostasie) [inline pkg/cmd/volume/rm.go:59]: This and following is to match docker behavior on multi remove:
- first output the list of successfully removed volumes
- then output the errors
- exit 1 if there was any error

File: pkg/mountutil/volumestore/volumestore.go [hunk 4]
```diff
@@ -131,12 +132,11 @@ func (vs *volumeStore) Create(name string, labels []string) (*native.Volume, err
 		return os.WriteFile(volFilePath, labelsJSON, 0644)
 	}
 
-	if err := lockutil.WithDirLock(vs.dir, fn); err != nil {
+	if err := lockutil.WithDirLock(vs.dir, fn); err != nil && !errors.Is(err, os.ErrExist) {
```
Comment (apostasie) [inline pkg/mountutil/volumestore/volumestore.go:135]: This to match docker behavior.
Repeat "create" of the same volume should not error.

File: pkg/mountutil/mountutilmock/volumestore.mock.go [hunk 5]
```diff
@@ -92,12 +92,12 @@ func (m *MockVolumeStoreMockRecorder) List(size any) *gomock.Call {
...
 
 // Remove mocks the Remove method of VolumeStore
-func (m *MockVolumeStore) Remove(names []string) ([]string, error) {
+func (m *MockVolumeStore) Remove(names []string) ([]string, []error, error) {
 	m.ctrl.T.Helper()
 	ret := m.ctrl.Call(m, "Remove", names)
 	ret0, _ := ret[0].([]string)
 	ret1, _ := ret[1].(error)
-	return ret0, ret1
+	return ret0, []error{}, ret1
```
Comment (apostasie) [inline pkg/mountutil/mountutilmock/volumestore.mock.go:100]: @AkihiroSuda I am not familiar with the mock library, and not sure what I should do here.
I did match the signature with the interface, but should I return anything instead of []error{}?

**Comment by apostasie** [comment]
@AkihiroSuda CI is green and linter is happy.

File: pkg/cmd/volume/rm.go (hunk 2 above)
Comment (AkihiroSuda) [inline pkg/cmd/volume/rm.go:55]: Maybe:
```suggestion
	removedNames, warns, err := volStore.Remove(volumenames)
```

File: pkg/mountutil/mountutilmock/volumestore.mock.go [hunk 6]
```diff
@@ -92,12 +92,12 @@ func (m *MockVolumeStoreMockRecorder) List(size any) *gomock.Call {
 }
 
 // Remove mocks the Remove method of VolumeStore
-func (m *MockVolumeStore) Remove(names []string) ([]string, error) {
+func (m *MockVolumeStore) Remove(names []string) ([]string, []error, error) {
```
Comment (AkihiroSuda) [inline pkg/mountutil/mountutilmock/volumestore.mock.go:95]: Maybe:
```suggestion
func (m *MockVolumeStore) Remove(names []string) (removed []string, warns []error, err error) {
```

File: pkg/mountutil/volumestore/volumestore.go [hunk 7]
```diff
@@ -65,7 +66,7 @@ type VolumeStore interface {
 	// Get may return ErrNotFound
 	Get(name string, size bool) (*native.Volume, error)
 	List(size bool) (map[string]native.Volume, error)
-	Remove(names []string) (removedNames []string, err error)
+	Remove(names []string) ([]string, []error, error)
```
Comment (AkihiroSuda) [inline pkg/mountutil/volumestore/volumestore.go:69]:
```suggestion
	Remove(names []string) (removedNames []string, warns []error, err error)
```

File: pkg/mountutil/mountutilmock/volumestore.mock.go (hunk 5 above)
Comment (AkihiroSuda) [reply pkg/mountutil/mountutilmock/volumestore.mock.go:100]: idk, probably just an empty list is fine

File: pkg/mountutil/mountutilmock/volumestore.mock.go (hunk 6 above)
Comment (apostasie) [reply pkg/mountutil/mountutilmock/volumestore.mock.go:95]: Yep, I like it.

**Comment by apostasie** [comment]
@AkihiroSuda your suggestion integrated in and pushed.

I am logging of now.

See you later.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
