### PR TITLE
[CI] new command implementation for tests

### LINKED ISSUE #3883: CI: icmd is not usable to test when binary expect a console
### Description

icmd passes an io.Multiwriter for stdout and stderr of the underlying command.

So (even if stdout is a proper pty), the command will still bail out if it requires a console (because "inappropriate ioctl for device").

That, along with the gymnastic in containerd/console - took me half a day to figure out why the eff I would not get anything on out with attach tests.

I am not sure we should continue using icmd.
The added value of it is rather limited (literally a few dozens lines of code that we are still using) , and I am not particularly interested in going over there to hack on it.

I *will* bypass it so that we can get #3591 in either way, so, might be time to bite the bullet and ditch it.

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### LINKED ISSUE #3996: [CI]: fix commands being stuck problem
Some commands being tested do deadlock sometimes.
This is particularly true for EL8, for yet undiagnosed reasons.

Because we do not timeout on command execution, the runner will just kill everything, and we do not get any information about which command (nor which test) did actually deadlock, and no logs of course.

We should be able to have some command execution default deadline in place at the test tooling level.
That way, commands being stuck for more than say, 5 minutes, should break and we would report a failed "timed-out test" along with appropriate logs.

@AkihiroSuda can you assign this to me please?

### PR DESCRIPTION
**Pull request by apostasie**
Note this is a large PR, though the bulk of the changes are under a couple of files in `mod/tigron/internal`, and probably half of it is just tests.

This PR is a tigron changeset addressing a few important issues:
- fix #3883
- fix #3996
- unlogged issue: dangling processes left behind

In a shell: icmd does not provide value for us. Most of its features we do not use, and the simple wrapping around golang command exec is causing more issues than it solves - icmd does replace the process standard streams with its own buffers, which gets in the way of using ptys, does not provide proper timeout logic for stuck processes, and does not seem to kill process groups properly.

This PR does away with it, and replace it with an internal com.Command that does offer:
- proper timeout
- pty handling
- proper process group termination

... along with absorbing a large part of the logic that was previously baked into test/command.go (env filtering, cloning, command wrapping).

While this should technically be (mostly) transparent for tests, some of the logic changes with timeout and pty / stdin handling required adaptation of some functions signatures.

Specifically:
- `Background(timeout)` is now simply `Background()`, as the new `WithTimeout` helper now applies to any command, and not just the background-ed ones
- `WithPTY` no longer supports the extra "writers" argument. To write to stdin, the same methods can now be used whether or not we are working with a PTY
- the previous `WithStdin` method was ill-named/ill-advised, as it is not setting stdin, but writing to stdin, can be used repeatedly, and lacked flexibility. It has been replaced by `Feed(io.Reader)` for the simpler cases, and `WithFeeder(func()io.Reader)` that allows for more complex logic before writing to stdin (like `Pty(writers)` used to)

Note that we might want to tweak the current default timeout for commands execution (3 minutes rn).

Blocked by:
- #4041 
- #4042
- #4044 
- #4045 
- #4047 
- #4054
- #4058

Preferable to merge after:
- #4048 
- #4051 
- #4062

TODO:
- [x] green CI
- [x] mute the logging from pipes by default

### CODE REVIEW

File: cmd/nerdctl/container/container_inspect_linux_test.go [hunk 1]
```diff
@@ -30,6 +30,7 @@ import (
 
 	"github.com/containerd/nerdctl/mod/tigron/expect"
 	"github.com/containerd/nerdctl/mod/tigron/test"
+
```
Comment (apostasie) [inline cmd/nerdctl/container/container_inspect_linux_test.go:33]: Should disappear once we get the golangci v2 PR in.

**Comment by apostasie** [comment]
@AkihiroSuda I will deal with the rebasing once we get all the dependent PR merged-in, but this is ready for review for all intent and purposes.

I am not sure we can break this down further in individual PRs (I did break it in individual commits though, that should help review), but LMK if you want me to yank something specific out in a separate PR.

**Comment by apostasie** [comment]
Reviewers: all commits except one are mundane.

The _one that matters_ is: https://github.com/containerd/nerdctl/pull/4056/commits/2bc62a52058dd5be66321e9fb4d18c0d3c88c974#diff-66fe4e3b3287c94bcd9942c86d92bb7259988cbc2aa6345a47dc2b56d14f411b - which contains the new command implementation.
Every other commit is to adapt tests to that.

**Comment by apostasie** [comment]
I guess we are having a birthday party today - for ghcr.io/stargz-containers/alpine:3.13-org

CreatedAt: "2021-03-31T17:21:23Z"

So, this is no longer "3 years ago" - it is now "4 years ago"...

Need to do something for that test.

File: Vagrantfile.freebsd [hunk 2]
```diff
@@ -59,7 +59,7 @@ Vagrant.configure("2") do |config|
         set -eux -o pipefail
         daemon -o containerd.out containerd
         sleep 3
-        /root/go/bin/nerdctl run --rm --net=none dougrabson/freebsd-minimal:13 echo "Nerdctl is up and running."
+        /root/go/bin/nerdctl run --rm --quiet --net=none dougrabson/freebsd-minimal:13 echo "Nerdctl is up and running."
```
Comment (AkihiroSuda) [inline Vagrantfile.freebsd:62]: ?

**Review by AkihiroSuda — APPROVED** [review]
Thanks
