### PR TITLE
Harden journald test

### LINKED ISSUE #3839: journald logging and tests
### Description

If the user is _not_ a member of group `adm` (or `systemd-journal`), `journalctl` will refuse to show logs, and bail out with exit code 1.

With nerdctl, we surface journalctl message, as-is: `No journal files were opened due to insufficient permissions`

That part is kinda ok.

But we still exit 0.

Now, in that scenario, all tests involving journald will fail.

I would suggest the following:
- `nerdctl logs foo` should exit 1 as well if journalctl does exit 1
- skip the tests if we lack permissions

Note that docker rootless also suck at it, and just return nothing, exit 0.

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
Fix #3839 - the other part of it - the first part is being fixed in #3841

### CODE REVIEW

File: cmd/nerdctl/container/container_logs_test.go [hunk 1]
```diff
@@ -109,8 +111,14 @@ func TestLogsWithInheritedFlags(t *testing.T) {
 }
 
 func TestLogsOfJournaldDriver(t *testing.T) {
-	t.Parallel()
 	testutil.RequireExecutable(t, "journalctl")
+	journalctl, _ := exec.LookPath("journalctl")
+	res := icmd.RunCmd(icmd.Command(journalctl, "-xe"))
+	if res.ExitCode != 0 {
```
Comment (AkihiroSuda) [inline cmd/nerdctl/container/container_logs_test.go:117]: Can we print stderr here?

Comment (apostasie) [reply cmd/nerdctl/container/container_logs_test.go:117]: Sure. Will do.

Comment (apostasie) [reply cmd/nerdctl/container/container_logs_test.go:117]: Done.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
