### PR TITLE
Image inspect rework

### LINKED ISSUE #2988: docker / nerdctl inconsistent return value from `image inspect --format json`
### Description

Docker returns an array with one or more values.

Nerdctl returns a stream of single values.

### Steps to reproduce the issue

1. sudo ./nerdctl image inspect --format json debian debian
2. docker image inspect --format json debian debian

### Describe the results you received and expected

nerdctl will return multiple lines of objects.

docker returns an array of objects.

### What version of nerdctl are you using?

1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### LINKED ISSUE #3005: nerdctl inspect does not allow inspecting networks, volumes
### Description

docker inspect allows inspecting networks, volumes, images, containers.

nerdctl only allows containers and images

### Steps to reproduce the issue

1. nerdctl inspect bridge
2 docker inspect bridge.

### Describe the results you received and expected

.

### What version of nerdctl are you using?

1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### LINKED ISSUE #3016: nerdctl rmi can be broken by using tag names with repo short sha
### Description

When an image uses a tag that is a short version of another (unrelated) image repo sha, nerdctl rmi will break down.

This is another aspect of one of the many issues with our current image lookup implementation.

### Steps to reproduce the issue

```
nerdctl pull busybox
nerdctl pull alpine
shortid="$(nerdctl inspect busybox | jq -rc .[0].RepoDigests[0])"
shortid="${shortid##*:}"
shortid="${shortid:0:8}"
nerdctl tag alpine "$shortid"
nerdctl rmi "$shortid"
```

### Describe the results you received and expected

```
FATA[0000] 1 errors:
multiple IDs found with provided prefix: 5eef5ed3
```

Should have just worked and removed the tagged version of alpine.

### What version of nerdctl are you using?

1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
Apologies for the big commit here, but I do not believe we can fix image inspect incrementally, as some of the core assumptions are wrong (specifically in the way we walk images, in the returned data types, etc).

Furthermore, there is more work needed here.
Other command which are doing images lookup (rmi) are also faulty.
Fixing these as well would turn this PR into a large monster, and I would rather do that separately as a follow-up once this one is reviewed and accepted.

So, this PR fixes the following:
- image inspect (#3004 among other things):
    - allow querying all sort of references:
        - repo short name
        - repo full name
        - repo with tag and/or digest
        - digest, with or without sha prefix
        - short ids
    - properly populate RepoTags and RepoDigests
    - always return a JSON array, instead of a stream, for example when multiple references are provided (fixes #2988)
- dockercompat:
    - implement Parent (if it has been set on the image - note: I am not sure nerdctl does add the label when committing, but this is a different problem)
    - implement Variant
    - add GraphDriverData struct for future implementation
    - updated Image struct to the latest version at https://github.com/moby/moby/blob/v26.1.2/api/types/types.go#L34-L140
    - implement (deprecated) VirtualSize for compatibility

Obviously, the reworked `image inspect` should be wired into `inspect` at a later point, and the overall revised lookup mechanics should be generalized and used by other methods (like `rmi`) - again, as a follow-up.
Overall the current ImageWalker should either be removed or replaced with the updated workflow here.

Please note that our implementation also diverges from Docker, for good reasons:
For example, when retrieving an image using a digest and a tagged name, we do verify the tag name against the result, unlike Moby which only verifies the image name (because of their use of ParseDockerRef, which should be banned from existence IMHO…).
Because of that, Moby will allow inspecting images using random bogus tag names as long as the digest matches and return a different image than the requested one altogether.
This has had far reaching consequences: specifically, mind-bending bugs for build caching invalidation.
I do believe Moby must fix it, but it’s not my problem.

What is left overall:
- #3011 is a problem - we need to look into it and this might have consequences for the lookup implementation here - specifically wrt ContentStore
- generalizing the lookup method so that other commands can leverage it (will fix #3016 for example)
- rewrite overall `inspect` to fix #3005, #3006

Also, this PR adds a bunch of integration tests on the above.

PTAL

cc @AkihiroSuda

### CODE REVIEW

File: pkg/referenceutil/referenceutil.go [hunk 1]
```diff
@@ -32,6 +32,20 @@ type Reference interface {
...
+	if scheme, ref, err := ParseIPFSRefWithScheme(rawRef); err == nil {
+		return Reference(stringRef{scheme: scheme, s: ref}), nil
+	}
+	if c, err := cid.Decode(rawRef); err == nil {
+		return c, nil
+	}
+	return refdocker.ParseAnyReference(rawRef)
+}
+
+// Deprecated
```
Comment (apostasie) [inline pkg/referenceutil/referenceutil.go:48]: Propose that we stop using ParseDockerRef in favor of ParseAnyReference. The former has some nasty side effects by dropping the tag in case there is a digest AFAIK.

File: pkg/inspecttypes/dockercompat/dockercompat.go [hunk 2]
```diff
@@ -294,48 +305,51 @@ func ContainerFromNative(n *native.Container) (*Container, error) {
 	return c, nil
 }
 
-func ImageFromNative(n *native.Image) (*Image, error) {
-	i := &Image{}
-
-	imgoci := n.ImageConfig
+func ImageFromNative(nativeImage *native.Image) (*Image, error) {
```
Comment (apostasie) [inline pkg/inspecttypes/dockercompat/dockercompat.go:308]: Light cleanup:
- improve variable name readability
- introduce variant and virtual size
- populate repodigest

File: pkg/inspecttypes/dockercompat/dockercompat.go [hunk 3]
```diff
@@ -47,28 +47,39 @@ import (
...
+	// TODO: GraphDriver	GraphDriverData
+
 	RootFS   RootFS
 	Metadata ImageMetadata
+
+	// Deprecated: TODO: Container   string
+	// Deprecated: TODO: ContainerConfig *container.Config
+}
+
+// From: https://github.com/moby/moby/blob/v26.1.2/api/types/graph_driver_data.go
```
Comment (apostasie) [inline pkg/inspecttypes/dockercompat/dockercompat.go:79]: Provisional for future implementation

File: pkg/inspecttypes/dockercompat/dockercompat.go [hunk 4]
```diff
@@ -47,28 +47,39 @@ import (
 	"github.com/tidwall/gjson"
 )
 
-// Image mimics a `docker image inspect` object.
-// From https://github.com/moby/moby/blob/v20.10.1/api/types/types.go#L340-L374
+// From https://github.com/moby/moby/blob/v26.1.2/api/types/types.go#L34-L140
 type Image struct {
```
Comment (apostasie) [inline pkg/inspecttypes/dockercompat/dockercompat.go:51]: Updated with latest definition and reordered a but for readability.
- moved down deprecated fields
- added VirtualSize, Parent, Variant

File: pkg/inspecttypes/dockercompat/dockercompat.go [hunk 5]
```diff
@@ -37,7 +37,7 @@ import (
 
 	"github.com/containerd/containerd"
 	"github.com/containerd/containerd/runtime/restart"
-	gocni "github.com/containerd/go-cni"
```
Comment (apostasie) [inline pkg/inspecttypes/dockercompat/dockercompat.go:40]: Unnecessary.

File: README.md [hunk 6]
```diff
@@ -268,6 +268,10 @@ docker build -t test-integration --target test-integration .
 docker run -t --rm --privileged test-integration
 ```
 
+To run a single integration test (in this case, `image_inspect_test`):
```
Comment (apostasie) [inline README.md:271]: Just a note for newcomers.

File: cmd/nerdctl/image_inspect_test.go [hunk 7]
```diff
@@ -33,15 +37,137 @@ func TestImageInspectContainsSomeStuff(t *testing.T) {
...
 	base.Cmd("pull", testutil.CommonImage).AssertOK()
+
 	// test RawFormat support
 	base.Cmd("image", "inspect", testutil.CommonImage, "--format", "{{.Id}}").AssertOK()
 
 	// test typedFormat support
 	base.Cmd("image", "inspect", testutil.CommonImage, "--format", "{{.ID}}").AssertOK()
 }
+
+func inspectImageHelper(base *testutil.Base, identifier ...string) []dockercompat.Image {
```
Comment (apostasie) [inline cmd/nerdctl/image_inspect_test.go:55]: Cannot use the one in testutil, as it assumes single entry array.

File: cmd/nerdctl/image_inspect_test.go [hunk 8]
```diff
@@ -39,9 +43,132 @@ func TestImageInspectWithFormat(t *testing.T) {
...
+	assert.Equal(base.T, cmdResult.ExitCode, 0)
+	var dc []dockercompat.Image
+	if err := json.Unmarshal([]byte(cmdResult.Stdout()), &dc); err != nil {
+		base.T.Fatal(err)
+	}
+	return dc
+}
+
+func TestImageInspectDifferentValidReferencesForTheSameImage(t *testing.T) {
+	testutil.DockerIncompatible(t)
```
Comment (apostasie) [inline cmd/nerdctl/image_inspect_test.go:66]: If really necessary, I could split this in two parts - the part that is docker compatible and the part that is not.

Either way we need first to resolve #3011

**Comment by apostasie** [comment]
Reviewer:

I don't want to introduce churn here by regularly adding more fixes.
The PR in its current state may have some minor issues (specifically there is one: Docker Hub names are not shortened properly before being added to RepoTags).
In the name of keeping our sanity, and if these minor issues are not a big deal for you, I will fix these in a follow-up once this is merged.

**Comment by apostasie** [comment]
Windows CI failure is on me.
Will try to fix it.

**Comment by apostasie** [comment]
Note this is likely fixing issues like #2061

**Comment by Zheaoli** [comment]
I will convert this PR to a draft before we solve the Windows issue together. I will help to figure out what happened.

**Comment by apostasie** [comment]
> https://github.com/containerd/nerdctl/blob/main/cmd/nerdctl/image_save_test.go#L35C22-L35C44
> 
> You can output the inspect.RepoDigests[0] in test during the debug, I think there one more `:` char in the string

Thanks @Zheaoli 

I believe the failure on save_test (TestSaveById) are unrelated, and are just flakyness.

The actual test failing is the one I introduced, and the issue here is that I am using test images that do not have a Windows version, so, pull fails on windows: https://github.com/containerd/nerdctl/actions/runs/9133230483/job/25136088395?pr=3017#step:8:569

**Comment by apostasie** [comment]
More accurately, the issue is:
`time="2024-05-18T17:41:26Z" level=fatal msg="failed to extract layer sha256:d4fc045c9e3a848011de66f34b81f052d4f2c15a17bb196d637e526349601820: hcsshim::ProcessBaseLayer \\\\?\\C:\\ProgramData\\containerd\\root\\io.containerd.snapshotter.v1.windows\\snapshots\\106: The system cannot find the path specified.: unknown"`

And I know nothing about `hcsshim`, or why it would fail extracting an image.

**Comment by apostasie** [comment]
@Zheaoli @AkihiroSuda 
CI is green.
I disabled the test on window for now.
Will revisit soon when I get a Windows environment to test on.

File: README.md (hunk 6 above)
Comment (ktock) [inline README.md:271]: can be a separated PR

File: cmd/nerdctl/image_inspect_test.go [hunk 9]
```diff
@@ -39,9 +44,136 @@ func TestImageInspectWithFormat(t *testing.T) {
...
+			base.Cmd("rmi", "-f", id).Run()
+		}
+	}
+
+	base.Cmd("pull", "alpine", "--platform", "linux/amd64").AssertOK()
+	base.Cmd("pull", "busybox", "--platform", "linux/amd64").AssertOK()
+	base.Cmd("pull", "busybox:stable", "--platform", "linux/amd64").AssertOK()
+	base.Cmd("pull", "registry-1.docker.io/library/busybox", "--platform", "linux/amd64").AssertOK()
+	base.Cmd("pull", "registry-1.docker.io/library/busybox:stable", "--platform", "linux/amd64").AssertOK()
+
```
Comment (ktock) [inline cmd/nerdctl/image_inspect_test.go:92]: Could you use/update https://github.com/containerd/nerdctl/blob/c0adea84eb9aa77e8eeb4b0f73fbfe5455bacf57/pkg/testutil/testutil_linux.go#L32-L59

File: cmd/nerdctl/image_inspect_test.go [hunk 10]
```diff
@@ -39,9 +44,136 @@ func TestImageInspectWithFormat(t *testing.T) {
...
+	// Build reference values for comparison
+	reference := inspectImageHelper(base, "busybox")
+	assert.Equal(base.T, 1, len(reference))
+	// Extract image sha
+	sha := strings.TrimPrefix(reference[0].RepoDigests[0], "busybox@sha256:")
+
+	differentReference := inspectImageHelper(base, "alpine")
+	assert.Equal(base.T, 1, len(differentReference))
+	// Extract image sha
+	// differentSha := strings.TrimPrefix(differentReference[0].RepoDigests[0], "alpine@sha256:")
```
Comment (ktock) [inline cmd/nerdctl/image_inspect_test.go:114]: Unneeded line?

File: cmd/nerdctl/image_inspect_test.go [hunk 11]
```diff
@@ -39,9 +44,136 @@ func TestImageInspectWithFormat(t *testing.T) {
...
+	for _, id := range []string{"doesnotexist", "doesnotexist:either", "busybox:bogustag"} {
+		t.Logf("Testing %s", id+"@"+sha)
+		args := append([]string{"image", "inspect"}, id+"@"+sha)
+		cmdResult := base.Cmd(args...).Run()
+		assert.Equal(base.T, cmdResult.ExitCode, 0)
+		assert.Equal(base.T, cmdResult.Stdout(), "")
+	}
+
+	// Prove that invalid reference return no result without crashing
+	for _, id := range []string{"∞∞∞∞∞∞∞∞∞∞", "busybox:∞∞∞∞∞∞∞∞∞∞"} {
```
Comment (ktock) [inline cmd/nerdctl/image_inspect_test.go:163]: Can we use more readable string like `!` or a very long tag?

FYI: https://docs.docker.com/reference/cli/docker/image/tag/#description

> The tag must be valid ASCII and can contain lowercase and uppercase letters, digits, underscores, periods, and hyphens. It can't start with a period or hyphen and must be no longer than 128 characters.

File: pkg/cmd/image/inspect.go [hunk 12]
```diff
@@ -19,58 +19,182 @@ package image
...
-	walker := &imagewalker.ImageWalker{
-		Client: client,
-		OnFound: func(ctx context.Context, found imagewalker.Found) error {
-			ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
-			defer cancel()
 
-			n, err := imageinspector.Inspect(ctx, client, found.Image, options.GOptions.Snapshotter)
+	// Set a timeout
+	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
+	defer cancel()
```
Comment (ktock) [inline pkg/cmd/image/inspect.go:103]: Rather than hard-coded timeout, it should be cancellable from the user with a signal.

File: cmd/nerdctl/image_inspect_test.go (hunk 11 above)
Comment (apostasie) [reply cmd/nerdctl/image_inspect_test.go:163]: I prefer something outside of the ASCII range if you don't mind, as this tends to uncover issues not necessarily seen without.

File: pkg/cmd/image/inspect.go (hunk 12 above)
Comment (apostasie) [reply pkg/cmd/image/inspect.go:103]: The timeout was there already, hard-coded, with the same value.
I do agree we should do better, but maybe as a follow-up PR?

LMK your thoughts.

File: cmd/nerdctl/image_inspect_test.go (hunk 10 above)
Comment (apostasie) [reply cmd/nerdctl/image_inspect_test.go:114]: Yes. Apologies.
Will fix.

File: cmd/nerdctl/image_inspect_test.go (hunk 9 above)
Comment (apostasie) [reply cmd/nerdctl/image_inspect_test.go:92]: I need to be able to test shortnames and other variants that resolve to Docker Hub, not just the fully qualified (ghcr) names.

I can of course add them as well to `testutil_linux`.
Should I?

File: pkg/referenceutil/referenceutil.go (hunk 1 above)
Comment (ktock) [reply pkg/referenceutil/referenceutil.go:48]: I don't think it doesn't need to be `Deprecated` as it's still used in the codebase. But I agree with ParseAnyReference should be used for necessary places.

File: pkg/cmd/image/inspect.go (hunk 12 above)
Comment (ktock) [reply pkg/cmd/image/inspect.go:103]: OK, can be a following up.

File: cmd/nerdctl/image_inspect_test.go (hunk 9 above)
Comment (ktock) [reply cmd/nerdctl/image_inspect_test.go:92]: > I need to be able to test shortnames and other variants that resolve to Docker Hub, not just the fully qualified (ghcr) names.

:+1:

> I can of course add them as well to testutil_linux.
> Should I?

Then I think it's OK as is.

**Review by ktock — APPROVED** [review]
LGTM on green

File: pkg/referenceutil/referenceutil.go (hunk 1 above)
Comment (apostasie) [reply pkg/referenceutil/referenceutil.go:48]: Let me remove the deprecated tag.

Thanks a lot for your review @ktock 
Really appreciated!

**Review by Zheaoli — APPROVED** [review]
LGTM

**Comment by AkihiroSuda** [comment]
@ktock @Zheaoli You can merge PRs
