### PR TITLE
[fix] fix image filter with nonexist image

### LINKED ISSUE #3511: `images --filter=non-existent` inconsistent (docker vs. nerdctl)
### Description

```
docker images --filter since=non-exists-image; echo $?
Error response from daemon: No such image: non-exists-image:latest
1
```

```
nerdctl images --filter since=non; echo $?
REPOSITORY    TAG    IMAGE ID    CREATED    PLATFORM    SIZE    BLOB SIZE
0
```

This recently got fixed because of a panic - in #3469 - though the tests being currently disabled for Docker made this go under the radar.

Tagging @xyz-li in case you are interested in revisiting. 

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by xyz-li**
Fix #3511

This commit does not cover this situation `nerdctl images -f since=IMAGE_ID`

### CODE REVIEW

File: pkg/imgutil/filtering.go [hunk 1]
```diff
@@ -145,18 +145,34 @@ func FilterByCreatedAt(ctx context.Context, client *containerd.Client, before []
 			maxTime = time.Now()
 		)
 
+		parseImageName := func(names []string) string {
+			var name string
+			if len(names) > 1 {
+				name = names[1]
+			} else {
+				name = names[0]
+			}
```
Comment (djdongjin) [inline pkg/imgutil/filtering.go:154]: can you explain why we use `names[1]` (not 0, not >1) if len(names) > 1?

Comment (xyz-li) [reply pkg/imgutil/filtering.go:154]: If you run command `nerdctl images -f since=nginx`. Then the first item is `docker.io/library/nginx:latest`, and the second item is `nginx`

https://github.com/containerd/nerdctl/blob/427f1cb6697af2a5c8d17550fb58d9f09aaa0a9e/pkg/imgutil/filtering.go#L96-L97

Comment (djdongjin) [reply pkg/imgutil/filtering.go:154]: how about lets just use `strings.Join(names, ",")`? given this is what we're actually doing.

File: pkg/imgutil/filtering.go [hunk 2]
```diff
@@ -145,18 +145,34 @@ func FilterByCreatedAt(ctx context.Context, client *containerd.Client, before []
...
 			}
-			if len(beforeImages) > 0 {
-				maxTime = beforeImages[0].CreatedAt
-				for _, image := range beforeImages {
-					if image.CreatedAt.After(maxTime) {
-						maxTime = image.CreatedAt
-					}
+			if len(beforeImages) == 0 {
+				//nolint:stylecheck
+				return []images.Image{}, fmt.Errorf("No such image: %s", parseImageName(before))
```
Comment (djdongjin) [inline pkg/imgutil/filtering.go:170]: why do we need `nolint` here?

Comment (xyz-li) [reply pkg/imgutil/filtering.go:170]: "No such image: aaaa:latest" is the output of docker. If don't add this `nolint`, then golint-ci won't pass, or we can change the output.

File: pkg/imgutil/filtering.go (hunk 1 above)
Comment (xyz-li) [reply pkg/imgutil/filtering.go]: `FATA[0000] No such image: docker.io/library/aaaa:latest,aaaa:latest`. I don't know if this is better or not?

File: pkg/imgutil/filtering.go (hunk 2 above)
Comment (djdongjin) [reply pkg/imgutil/filtering.go]: >  If don't add this nolint, then golint-ci won't pass

what's the error message from golint-ci? (Or you mean `"No such image: aaaa:latest" is the output of docker.` is the error message from golint-ci?)

Comment (xyz-li) [reply pkg/imgutil/filtering.go]:
```
 Running [/home/runner/golangci-lint-1.61.0-linux-amd64/golangci-lint run  --verbose] in [/home/runner/work/nerdctl/nerdctl] ...
  Error: pkg/imgutil/filtering.go:163:30: ST1005: error strings should not be capitalized (stylecheck)
  				return []images.Image{}, fmt.Errorf("No such image: %s", fetchImageNames(before))
  				                         ^
  Error: pkg/imgutil/filtering.go:179:30: ST1005: error strings should not be capitalized (stylecheck)
  				return []images.Image{}, fmt.Errorf("No such image: %s", fetchImageNames(since))
  	
```

**Review by djdongjin — APPROVED** [review]
