### PR TITLE
nerdctl version: skip inspecting rootless daemon if the daemon is not running

### LINKED ISSUE #2455: nerdctl version requires rootless containerd
### Description

I don't know if this is intended, but `nerdctl version` requires rootless containerd to be running, is that the expected behavior?:

```bash
~ ❯ nerdctl --version
nerdctl version 1.5.0
~ ❯ nerdctl version
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): stat /run/user/1000/containerd-rootless: no such file or directory

```

### Steps to reproduce the issue

1. Run `nerdctl version`, without rootless containerd

### Describe the results you received and expected

I would expect that `nerdctl version` shows the version of whatever it is I'm running

### What version of nerdctl are you using?

1.5.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

Surprisingly, `nerctl info` also requires rootless containerd:

```bash
~   nerdctl info
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): stat /run/user/1000/containerd-rootless: no such file or directory
```
FWIW, I'm using Arch Linux, but even building from the tip of main, the error persists.

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #2455

### CODE REVIEW

File: cmd/nerdctl/version.go [hunk 1]
```diff
@@ -66,7 +67,17 @@ func versionAction(cmd *cobra.Command, args []string) error {
 		}
 	}
 
-	v, vErr := versionInfo(cmd, globalOptions)
+	address := globalOptions.Address
+	// rootless `nerdctl version` runs in the host namespaces, so the address is different
```
Comment (fahedouch) [inline cmd/nerdctl/version.go:71]:
```suggestion
	// rootless `nerdctl version` runs in the host namespaces (parent), so the address is different
```

File: cmd/nerdctl/version.go [hunk 2]
```diff
@@ -66,7 +67,17 @@ func versionAction(cmd *cobra.Command, args []string) error {
...
+	if rootlessutil.IsRootless() {
+		address, err = rootlessutil.RootlessContainredSockAddress()
+		if err != nil {
+			logrus.WithError(err).Warning("failed to inspect the rootless containerd socket address")
+			address = ""
```
Comment (fahedouch) [inline cmd/nerdctl/version.go:76]: `address = ""` is useless

File: cmd/nerdctl/version.go [hunk 3]
```diff
@@ -102,13 +113,16 @@ func versionAction(cmd *cobra.Command, args []string) error {
 	return vErr
 }
 
-// versionInfo may return partial VersionInfo on error
-func versionInfo(cmd *cobra.Command, globalOptions types.GlobalCommandOptions) (dockercompat.VersionInfo, error) {
-
+// versionInfo may return partial VersionInfo on error.
+// Address can be empty to skip inspecting the server.
```
Comment (fahedouch) [inline cmd/nerdctl/version.go:117]: Nice to have; Address can be a ptr type to avoid allocating usless memory space when empty

File: cmd/nerdctl/version.go (hunk 1 above)
Comment (AkihiroSuda) [reply cmd/nerdctl/version.go:71]: "host namespaces" should be already enough

File: cmd/nerdctl/version.go (hunk 3 above)
Comment (AkihiroSuda) [reply cmd/nerdctl/version.go:117]: The overhead is negligible

File: cmd/nerdctl/version.go (hunk 2 above)
Comment (AkihiroSuda) [reply cmd/nerdctl/version.go:76]: This is added because a future version of `RootlessContainredSockAddress` may potentially return a non-empty address with a non-nil err.

Comment (fahedouch) [reply cmd/nerdctl/version.go:76]: Why ?

**Review by fahedouch — APPROVED** [review]
LGTM

**Review by ktock — APPROVED** [review]
