### PR TITLE
Fix apparmor test not running

### LINKED ISSUE #3859: TestRunApparmor does not seem to ever run on the CI
### Description

Rootful:
https://github.com/containerd/nerdctl/actions/runs/13000786746/job/36258878338?pr=3853#step:8:430

Rootless:
https://github.com/containerd/nerdctl/actions/runs/13000786746/job/36258878879?pr=3853#step:9:613

In both cases:

```
=== SKIP: cmd/nerdctl/container TestRunApparmor (0.00s)
    container_run_security_linux_test.go:176: needs to be able to apply "nerdctl-default" profile
```

I don't know why, and this does not make much sense.

Maybe for rootless - although https://github.com/containerd/nerdctl/blob/main/Dockerfile.d/test-integration-rootless.sh#L21 needs a serious review then - as it seems bizarre that a script named "-rootless" would do certain things when `uid = 0`.

For rootful though, we should certainly be able to load the profile and apply it.

This is related to #3858 : our current testing rig is hard to reason about, and more importantly, is hiding issues and non-running tests.

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
Fix #3859 

This PR addresses two underlying issues:
- our test rig did not mount securityfs
- the containerd/pkg hostsupport method is not usable here, as it was specifically designed to not work inside a container

### CODE REVIEW

File: Dockerfile.d/test-integration-rootless.sh [hunk 1]
```diff
@@ -16,6 +16,8 @@
 
 set -eux -o pipefail
 if [[ "$(id -u)" = "0" ]]; then
+  # Ensure securityfs is mounted for apparmor to work
+  mount -tsecurityfs securityfs /sys/kernel/security
```
Comment (fahedouch) [inline Dockerfile.d/test-integration-rootless.sh:20]:
```suggestion
if ! mountpoint -q /sys/kernel/security; then
  mount -tsecurityfs securityfs /sys/kernel/security
fi
```

Comment (apostasie) [reply Dockerfile.d/test-integration-rootless.sh:20]: Good one. Thanks. Will amend.

Comment (apostasie) [reply Dockerfile.d/test-integration-rootless.sh]: Done.

**Review by fahedouch — APPROVED** [review]
LGTM. Thanks :)
