### PR TITLE
Disable default hostname when container network mode is enabled

### LINKED ISSUE #1670: how to debug `nerdctl compose up`
### Description

get error `FATA[0000] error while creating container coredns: exit status 1` when using `nerdctl compose up`

### Steps to reproduce the issue

1. create a compose.yml like this:
```
services:
  nginx:
    image: nginx:1.23.2
    container_name: nginx
    restart: always
  coredns:
    image: coredns/coredns:1.10.0
    container_name: coredns
    restart: always
    network_mode: "container:nginx"
```
2. run `nerdctl compose up -d` and get the error
```
INFO[0000] Ensuring image nginx:1.23.2
INFO[0000] Ensuring image coredns/coredns:1.10.0
INFO[0000] Creating container coredns
INFO[0000] Re-creating container nginx
FATA[0000] error while creating container coredns: exit status 1
```

### Describe the results you received and expected

without error

### What version of nerdctl are you using?

v1.1.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information
```
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.12
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.14.0-162.6.1.el9_1.0.1.x86_64
 Operating System: Rocky Linux 9.1 (Blue Onyx)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 93.79GiB
 Name: headq
 ID: 4643dd54-7788-488d-a450-7468458b2f92

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### PR DESCRIPTION
**Pull request by djdongjin**
Fix #1670.

We should not add default hostname flag when network mode is container.

This PR only adds minimum check so we're not adding some default conflicting flags. Other confliects due to user config/input will still pass the serviceparser step and error while running the command. (e.g., those conflicts defined [here](https://github.com/containerd/nerdctl/blob/c2c648c5ef7bad5ebbcb05dcdef9247f31892efe/cmd/nerdctl/run_network.go#L300)).

While debugging, I did notice a difficulty as shown in #1670. When `-d` is enabled (`compose up -d`), the error/warning from subcommand (here, `nerdctl run`) won't be printed and only the `cmd` error message is returned/printed (`exit status 1`):

https://github.com/containerd/nerdctl/blob/main/pkg/composer/up_service.go#L168-L176

Signed-off-by: Jin Dong <jindon@amazon.com>

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
> Disable default hostname when network mode is enabled

Perhaps s/enabled/set to "container" mode/ ?

**Comment by djdongjin** [comment]
> Perhaps s/enabled/set to "container" mode/ ?

fixed

File: pkg/composer/serviceparser/serviceparser.go [hunk 1]
```diff
@@ -570,7 +564,11 @@ func newContainer(project *types.Project, parsed *Service, i int) (*Container, e
 	if err != nil {
 		return nil, err
 	}
+	netTypeContainer := false
 	for _, net := range networks {
+		if strings.HasPrefix(net.fullName, "container") {
```
Comment (fahedouch) [inline pkg/composer/serviceparser/serviceparser.go:569]: may be `strings.HasPrefix(net.fullName, "container:")` to avoid misuse of `container*`

File: pkg/composer/serviceparser/serviceparser_test.go [hunk 2]
```diff
@@ -348,6 +348,10 @@ services:
   foo:
     image: nginx:alpine
     network_mode: host
+    container_name: nginx
+  bar:
+    image: alpine
+    network_mode: container:nginx
 `
```
Comment (fahedouch) [inline pkg/composer/serviceparser/serviceparser_test.go:355]:
```suggestion
	const dockerComposeYAML = fmt.Sprintf(`
services:
  foo:
    image: %s
    network_mode: host
    container_name: nginx
  bar:
    image: %s
    network_mode: container:nginx
`, testutil.NginxAlpineImage,  testutil.AlpineImage)
```

File: pkg/composer/serviceparser/serviceparser.go (hunk 1 above)
Comment (djdongjin) [reply pkg/composer/serviceparser/serviceparser.go]: fixed

File: pkg/composer/serviceparser/serviceparser_test.go (hunk 2 above)
Comment (djdongjin) [reply pkg/composer/serviceparser/serviceparser_test.go]: fixed

Comment (djdongjin) [reply pkg/composer/serviceparser/serviceparser_test.go:355]: Hi @fahedouch, I have to change it back. `testutil.NginxAlpineImage,  testutil.AlpineImage` are defined in `testutil_linux.go` which will fail the FreeBSD test. Not sure if it can be moved to the common `testutil.go`. So I will use `alpine:3.14` as other tests in the file.

https://github.com/containerd/nerdctl/blob/a04a4e5645065b91a063cfb2a8de46f56cde88b3/pkg/testutil/testutil_linux.go.

**Comment by fahedouch** [comment]
LGTM on green CI

**Review by fahedouch — APPROVED** [review]

**Review by AkihiroSuda — APPROVED** [review]
Thanks
