### PR TITLE
Make the ServerAddress optional for the main docker registry.

### LINKED ISSUE #1308: Nerdctl client sometimes wants both a populated `auths` field when `credsStore` gives credentials
### Description

A Rancher Desktop user can get into a state where when they run `nerdctl run SOME_IMAGE`, they see the error message 
```
FATA[0000] expected ac.ServerAddress ("") to be "https://index.docker.io/v1/"
```

This was exposed when PR #1270 was merged into master.

### Steps to reproduce the issue

1. Run Rancher Desktop 1.5.0 after an install or FactoryReset (or delete /root/.docker/config.json on the VM)
2. Choose moby/docker mode
3. docker login
4. Switch to containerd/nerdctl
6. nerdctl pull busybox

This triggers the above error message

### Describe the results you received and expected

I expected to see an image get pulled.

```
FATA[0000] expected ac.ServerAddress ("") to be "https://index.docker.io/v1/"
```

### What version of nerdctl are you using?

0.22.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Rancher Desktop for macOS

### Host information

```
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: v1.6.6
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.57-0-virt
 Operating System: Alpine Linux v3.16
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.846GiB
 Name: lima-rancher-desktop
 ID: d28cfc71-d41b-4077-891c-c78648e76494
```

### PR DESCRIPTION
**Pull request by ericpromislow**
Fixes #1308

Signed-off-by: Eric Promislow <epromislow@suse.com>

### CODE REVIEW

**Comment by ericpromislow** [comment]
The `FreeBSD` test failure looks like a flake -- image-pulling timed out

File: pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go [hunk 1]
```diff
@@ -201,7 +201,7 @@ func NewAuthCreds(refHostname string) (AuthCreds, error) {
 			// - ac.ServerAddress:         "https://index.docker.io/v1/".
 			if !isAuthConfigEmpty(ac) {
 				if authConfigHostname == registry.IndexServer {
-					if ac.ServerAddress != registry.IndexServer {
+					if ac.ServerAddress != "" && ac.ServerAddress != registry.IndexServer {
```
Comment (fahedouch) [inline pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go:204]: I think we should enforce the default registry `ac.ServerAddress = registry.IndexServer`  when it is empty for all `refHostname`

File: pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go [hunk 2]
```diff
@@ -201,7 +201,7 @@ func NewAuthCreds(refHostname string) (AuthCreds, error) {
 			// - ac.ServerAddress:         "https://index.docker.io/v1/".
 			if !isAuthConfigEmpty(ac) {
 				if authConfigHostname == registry.IndexServer {
```
Comment (fahedouch) [inline pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go:203]: `ac.ServerAddress = registry.IndexServer`

I think we should enforce the default registry   when it is empty for all `refHostname`

File: pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go (hunk 1 above)
Comment (ktock) [inline pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go:204]: nit: To preserve the behaviour of printing the debug log on `ac.ServerAddress == ""`, I think the `if` logic should be something like:

```go
if ac.ServerAddress == "" {
	// This can happen with Amazon ECR: https://github.com/containerd/nerdctl/issues/733
	logrus.Debugf("failed to get ac.ServerAddress for authConfigHostname=%q (refHostname=%q)",
		authConfigHostname, refHostname)
} else if authConfigHostname == registry.IndexServer {
	if ac.ServerAddress != registry.IndexServer {
		return nil, fmt.Errorf("expected ac.ServerAddress (%q) to be %q", ac.ServerAddress, registry.IndexServer)
	}
} else {
	acsaHostname := credentials.ConvertToHostname(ac.ServerAddress)
	if acsaHostname != authConfigHostname {
		return nil, fmt.Errorf("expected the hostname part of ac.ServerAddress (%q) to be authConfigHostname=%q, got %q",
			ac.ServerAddress, authConfigHostname, acsaHostname)
	}
}
```

**Review by ktock — COMMENTED** [review]
Overall looks good to me.
Left a nit.

**Comment by AkihiroSuda** [comment]
@ericpromislow Could you take a look at comments? 🙏

File: pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go (hunk 1 above)
Comment (AkihiroSuda) [reply pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go:204]: @ericpromislow @jandubois ↑ LGTY?

Comment (jandubois) [reply pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go:204]: @AkihiroSuda Yes, LGTM, and I've tested that it fixes the repro case specified in https://github.com/containerd/nerdctl/issues/1308#issuecomment-1213554489

Comment (jandubois) [reply pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go:204]: BTW, @ericpromislow is still away, so you won't get any feedback from him for at least another 10 days.

Comment (AkihiroSuda) [reply pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go:204]: @jandubois Thanks for testing and providing the info

@ktock Please add your commit to this PR (or just open a new PR)?

**Review by AkihiroSuda — APPROVED** [review]
Thanks
