### PR TITLE
Fix journald logger exit and wait behavior

### LINKED ISSUE #3840: nerdctl logs with log-driver journald does not `wait` on journalctl
### Description

`nerdctl logs -f foo`

will launch `journalctl SYSLOG_IDENTIFIER=44c10dfcf2c6 --output=cat -f` and just returns.

We should `cmd.Wait()`.

### Steps to reproduce the issue

_No response_

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
This should fix #3840 and part of #3839

### CODE REVIEW

File: pkg/logging/journald_logger.go [hunk 1]
```diff
@@ -173,12 +173,21 @@ func FetchLogs(stdout, stderr io.Writer, journalctlArgs []string, stopChannel ch
...
 		<-stopChannel
+		killed = true
 		log.L.Debugf("killing journalctl logs process with PID: %#v", cmd.Process.Pid)
 		cmd.Process.Kill()
 	}()
 
+	err = cmd.Wait()
+	if exitError, ok := err.(*exec.ExitError); ok {
+		if !killed && exitError.ExitCode() != 0 {
+			return errors.New("journalctl command exited with non-zero exit code")
```
Comment (djdongjin) [inline pkg/logging/journald_logger.go:187]: suggest:

`return fmt.Errorf("journalctl command exited with non-zero exit code (%d): %w", exitError.ExitCode(), exitError)`

Comment (apostasie) [reply pkg/logging/journald_logger.go:187]: Thanks. Will do.

Comment (apostasie) [reply pkg/logging/journald_logger.go]: Done.

**Review by djdongjin — APPROVED** [review]
LGTM, thanks

File: pkg/logging/journald_logger.go [hunk 2]
```diff
@@ -173,12 +173,21 @@ func FetchLogs(stdout, stderr io.Writer, journalctlArgs []string, stopChannel ch
 	}
 
 	// Setup killing goroutine:
+	killed := false
 	go func() {
 		<-stopChannel
+		killed = true
```
Comment (AkihiroSuda) [inline pkg/logging/journald_logger.go:179]: This should be set after killing the process?

Comment (AkihiroSuda) [reply pkg/logging/journald_logger.go:179]: Also, this one should have a mutex

Comment (apostasie) [reply pkg/logging/journald_logger.go:179]: > This should be set after killing the process?

But then, wouldn't `Wait()` return before `killed` is set?

Comment (apostasie) [reply pkg/logging/journald_logger.go:179]: > Also, this one should have a mutex

I am not sure I understand why. `Wait()` will not return until the process is killed, right?

**Review by AkihiroSuda — APPROVED** [review]
Thanks
