### PR TITLE
Fix images output check bug

### LINKED ISSUE #1997: Testutil images cannot be directly used to validate `nerdctl images` output
### Description

Some integration tests need to check if an image (mostly in [testutil](https://github.com/containerd/nerdctl/blob/cffdf87ff4d648a5344eea1406bb95ca3ad7eaa4/pkg/testutil/testutil_linux.go#L27-L43) exist in `nerdctl images` output to validate some opeartions (e.g. `nerdctl rmi`).

However, integration tests use different ways to do this and some have bugs:

1. [Use `images --names`](https://github.com/containerd/nerdctl/blob/cffdf87ff4d648a5344eea1406bb95ca3ad7eaa4/cmd/nerdctl/image_list_test.go#L36-L37): this works since the output combines repo and tag.
2. [Split `testutil.xxxImage`](https://github.com/containerd/nerdctl/blob/cffdf87ff4d648a5344eea1406bb95ca3ad7eaa4/cmd/nerdctl/image_load_linux_test.go#L47) and only check repo: this works but it's too manual.
3. [`Cmd("images").AssertOutContains(testutil.xxxImage)`](https://github.com/containerd/nerdctl/blob/cffdf87ff4d648a5344eea1406bb95ca3ad7eaa4/cmd/nerdctl/image_remove_linux_test.go#L40): this is bug because the output has repo and tag separated but not the image var.

For the 3rd one, if check `AssertOutNo` then it always return true because of the format; if check `AssertOutContains` then it bug is surfaced:

```shell
=== RUN   TestRemovePausedImage
    image_remove_linux_test.go:65: assertion failed: 
        Command:  /usr/local/bin/nerdctl --namespace=nerdctl-test images
        ExitCode: 0
        Stdout:   REPOSITORY                          TAG         IMAGE ID        CREATED                   PLATFORM       SIZE       BLOB SIZE
        ghcr.io/stargz-containers/alpine    3.13-org    ec14c7992a97    Less than a second ago    linux/amd64    5.6 MiB    2.7 MiB
        
        Stderr:   
        
        Failures:
        Expected stdout to contain "ghcr.io/stargz-containers/alpine:3.13-org"
--- FAIL: TestRemovePausedImage (1.68s)
```

### Steps to reproduce the issue

_No response_

### Describe the results you received and expected

Make images check in tests no bug and consistent.

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by djdongjin**
Fix #1997

Signed-off-by: Jin Dong <jindon@amazon.com>

### CODE REVIEW

**Review by manugupt1 — APPROVED** [review]
Thanks!

File: pkg/testutil/testutil.go [hunk 1]
```diff
@@ -450,17 +450,6 @@ func (c *Cmd) AssertOutStreamsExactly(stdout, stderr string) {
...
-	c.Base.T.Helper()
-	fn := func(stdout string) error {
-		if strings.Contains(stdout, s) {
-			return fmt.Errorf("expected not to contain %q, got %q", s, stdout)
-		}
-		return nil
-	}
-	c.AssertOutWithFunc(fn)
-}
-
```
Comment (AkihiroSuda) [inline pkg/testutil/testutil.go:463]: Is this change relevant to the bug?
Otherwise please consider splitting the commit

File: pkg/testutil/testutil_linux.go [hunk 2]
```diff
@@ -16,7 +16,9 @@
 
 package testutil
 
-import "fmt"
+import (
+	"fmt"
+)
```
Comment (AkihiroSuda) [inline pkg/testutil/testutil_linux.go:21]: Not necessary

File: pkg/testutil/testutil.go [hunk 3]
```diff
@@ -684,3 +684,9 @@ func Identifier(t testing.TB) string {
 	}
 	return s
 }
+
+// ImageRepo is a test helper that simply splits a full image name (i.e., not id/digest)
+// by `:` and returns the 1st part.
+func ImageRepo(s string) string {
+	return strings.Split(s, ":")[0]
```
Comment (AkihiroSuda) [inline pkg/testutil/testutil.go:691]: Doesn't seem to work when the image name contains a registry port number, e.g., `example.com:8080/example`

Comment (manugupt1) [reply pkg/testutil/testutil.go:691]: I think we can use imgutil.ParseRepoTag and return the first part.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
