### PR TITLE
Fix -t/--time flag for restart command is not working

### LINKED ISSUE #1485: -t/--time flag for restart command is not working (`trying to get int value of flag of type string`)
### Description

-t/--time flag for `restart` command is not working

### Steps to reproduce the issue

1. create a running container: `nerdctl run --name ctr-name -d alpine sleep infinity`
2. restart the container by specifying -t/--time flag: `nerdctl restart -t 1 ctr-name` 

### Describe the results you received and expected

Expected: The running container should be restart around 1s
Received: `FATA[0000] trying to get int value of flag of type string`

### What version of nerdctl are you using?

v1.0.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

_No response_

### Host information

Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### PR DESCRIPTION
**Pull request by yuchanns**
Fix #1485

- [x] Add an integration test

Signed-off-by: Hanchin Hsieh <me@yuchanns.xyz>

### CODE REVIEW

**Review by manugupt1 — APPROVED** [review]

**Comment by manugupt1** [comment]
Can you add an Integ test please?

**Comment by yuchanns** [comment]
I'll add it late today

**Review by manugupt1 — APPROVED** [review]

File: cmd/nerdctl/restart_linux_test.go [hunk 1]
```diff
@@ -43,6 +43,12 @@ func TestRestart(t *testing.T) {
 	newInspect := base.InspectContainer(tID)
 	newPid := newInspect.State.Pid
 	assert.Assert(t, pid != newPid)
+
+	base.Cmd("restart", "-t", "5", tID).AssertOK()
+	base.EnsureContainerStarted(tID)
+	timeInspect := base.InspectContainer(tID)
+	timePid := timeInspect.State.Pid
+	assert.Assert(t, pid != timePid)
```
Comment (fahedouch) [inline cmd/nerdctl/restart_linux_test.go:51]: You are test does not highlight the grace period

File: cmd/nerdctl/restart.go [hunk 2]
```diff
@@ -35,7 +35,7 @@ func newRestartCommand() *cobra.Command {
 		SilenceUsage:      true,
 		SilenceErrors:     true,
 	}
-	restartCommand.Flags().StringP("time", "t", "10", "Seconds to wait for stop before killing it")
+	restartCommand.Flags().IntP("time", "t", 10, "Seconds to wait for stop before killing it")
```
Comment (fahedouch) [inline cmd/nerdctl/restart.go:38]: `uintP`

File: cmd/nerdctl/restart_linux_test.go (hunk 1 above)
Comment (yuchanns) [reply cmd/nerdctl/restart_linux_test.go]: SGTM

File: cmd/nerdctl/restart_linux_test.go [hunk 3]
```diff
@@ -69,3 +72,33 @@ func TestRestartPIDContainer(t *testing.T) {
...
+	// receiving the SIGTERM signal with ignoring the time specified
+	base.Cmd("run", "-d", "--name", tID, testutil.AlpineImage, "sleep", "infinity").AssertOK()
+	defer base.Cmd("rm", "-f", tID).AssertOK()
+	base.EnsureContainerStarted(tID)
+
+	inspect := base.InspectContainer(tID)
+	pid := inspect.State.Pid
+
+	// random time in the interval of [1, 20] to restart
+	rand.Seed(time.Now().UnixNano())
```
Comment (manugupt1) [inline cmd/nerdctl/restart_linux_test.go:91]: Can you keep the time as constant rather than a random time please?

Comment (yuchanns) [reply cmd/nerdctl/restart_linux_test.go:91]: Sure.

File: cmd/nerdctl/restart_linux_test.go [hunk 4]
```diff
@@ -69,3 +71,31 @@ func TestRestartPIDContainer(t *testing.T) {
 
 	assert.Equal(t, baseOutput, sharedOutput)
 }
+
+func TestRestartWithTime(t *testing.T) {
```
Comment (AkihiroSuda) [inline cmd/nerdctl/restart_linux_test.go:75]: Failing

```
=== CONT  TestRestartWithTime
    restart_linux_test.go:93: container nerdctl-testrestartwithtime is now running
    restart_linux_test.go:100: assertion failed: timeEnd.Sub(timeStart).Round(time.Second) is not time.Second * time.Duration(sec)
--- FAIL: TestRestartWithTime (6.36s)
```

File: cmd/nerdctl/restart_linux_test.go [hunk 5]
```diff
@@ -69,3 +71,31 @@ func TestRestartPIDContainer(t *testing.T) {
...
+
+	base.Cmd("restart", "-t", strconv.Itoa(sec), tID).AssertOK()
+	base.EnsureContainerStarted(tID)
+	timeEnd := time.Now()
+
+	newInspect := base.InspectContainer(tID)
+	newPid := newInspect.State.Pid
+	assert.Assert(t, pid != newPid)
+	// accurate the duration to seconds
+	assert.Assert(t, timeEnd.Sub(timeStart).Round(time.Second) == time.Second*time.Duration(sec))
```
Comment (AkihiroSuda) [inline cmd/nerdctl/restart_linux_test.go:100]: assert.Equal

Comment (AkihiroSuda) [inline cmd/nerdctl/restart_linux_test.go:100]: Just asserting `timeEnd.Sub(timeStart) < time.Second` might be ok

File: cmd/nerdctl/restart_linux_test.go [hunk 6]
```diff
@@ -69,3 +70,29 @@ func TestRestartPIDContainer(t *testing.T) {
...
 	assert.Equal(t, baseOutput, sharedOutput)
 }
+
+func TestRestartWithTime(t *testing.T) {
+	t.Parallel()
+	base := testutil.NewBase(t)
+	tID := testutil.Identifier(t)
+
+	// here we do not use nginx-alpine because it restarts immediately after
+	// receiving the SIGTERM signal with ignoring the time specified
```
Comment (fahedouch) [inline cmd/nerdctl/restart_linux_test.go:80]: Sorry but I don't understand the comment!

File: cmd/nerdctl/restart_linux_test.go [hunk 7]
```diff
@@ -69,3 +70,29 @@ func TestRestartPIDContainer(t *testing.T) {
...
+	base.Cmd("run", "-d", "--name", tID, testutil.AlpineImage, "sleep", "infinity").AssertOK()
+	defer base.Cmd("rm", "-f", tID).AssertOK()
+	base.EnsureContainerStarted(tID)
+
+	inspect := base.InspectContainer(tID)
+	pid := inspect.State.Pid
+
+	timeStart := time.Now()
```
Comment (fahedouch) [inline cmd/nerdctl/restart_linux_test.go:88]: `timePreRestart` 
`timePostRestart`

File: cmd/nerdctl/restart_linux_test.go [hunk 8]
```diff
@@ -69,3 +70,29 @@ func TestRestartPIDContainer(t *testing.T) {
...
+	base.Cmd("restart", "-t", "5", tID).AssertOK()
+	base.EnsureContainerStarted(tID)
+	timeEnd := time.Now()
+
+	newInspect := base.InspectContainer(tID)
+	newPid := newInspect.State.Pid
+	assert.Assert(t, pid != newPid)
+	// The wait time cost may float within +1 second
+	assert.Assert(t, timeEnd.Sub(timeStart).Round(time.Second) <= time.Second*6)
```
Comment (fahedouch) [inline cmd/nerdctl/restart_linux_test.go:97]: You have to ensure that stop took at least 5s.

**Review by fahedouch — CHANGES_REQUESTED** [review]

File: cmd/nerdctl/restart_linux_test.go (hunk 6 above)
Comment (yuchanns) [reply cmd/nerdctl/restart_linux_test.go:80]: That is to ensure the stop takes at least 5 seconds. If I use the Nginx Alpine image, it will stop immediately once it receives a SIGTERM signal. Then it couldn't be tested as it should be (to be killed after 5 seconds).

File: cmd/nerdctl/restart_linux_test.go (hunk 7 above)
Comment (yuchanns) [reply cmd/nerdctl/restart_linux_test.go]: SGTM

File: cmd/nerdctl/restart_linux_test.go (hunk 8 above)
Comment (yuchanns) [reply cmd/nerdctl/restart_linux_test.go]: SGTM

File: cmd/nerdctl/restart_linux_test.go (hunk 6 above)
Comment (yuchanns) [reply cmd/nerdctl/restart_linux_test.go]: Looks like the comment is redundant here and will make people get confused. Removed it.

File: cmd/nerdctl/restart_linux_test.go [hunk 9]
```diff
@@ -69,3 +70,29 @@ func TestRestartPIDContainer(t *testing.T) {
...
+	base.Cmd("run", "-d", "--name", tID, testutil.AlpineImage, "sleep", "infinity").AssertOK()
+	defer base.Cmd("rm", "-f", tID).AssertOK()
+	base.EnsureContainerStarted(tID)
+
+	inspect := base.InspectContainer(tID)
+	pid := inspect.State.Pid
+
+	timePreRestart := time.Now()
+	base.Cmd("restart", "-t", "5", tID).AssertOK()
+	base.EnsureContainerStarted(tID)
```
Comment (fahedouch) [inline cmd/nerdctl/restart_linux_test.go:88]: Container starting is already ensured by `AssertOK()`  , so this is useless here.

File: cmd/nerdctl/restart_linux_test.go [hunk 10]
```diff
@@ -69,3 +70,28 @@ func TestRestartPIDContainer(t *testing.T) {
...
 }
+
+func TestRestartWithTime(t *testing.T) {
+	t.Parallel()
+	base := testutil.NewBase(t)
+	tID := testutil.Identifier(t)
+
+	base.Cmd("run", "-d", "--name", tID, testutil.AlpineImage, "sleep", "infinity").AssertOK()
+	defer base.Cmd("rm", "-f", tID).AssertOK()
+	base.EnsureContainerStarted(tID)
```
Comment (fahedouch) [inline cmd/nerdctl/restart_linux_test.go:81]: Sorry, but same here this is useless too

Comment (yuchanns) [reply cmd/nerdctl/restart_linux_test.go]: Thanks :)

**Comment by fahedouch** [comment]
Test is failing
```
restart_linux_test.go:95: assertion failed: timePostRestart.Sub(timePreRestart).Round(time.Second) is greater than time.Second * 6
```

**Comment by yuchanns** [comment]
The test case of a maximum restart time assertion seems unstable. I think ensuring the least time is enough. So I'm gonna remove the assertion.

**Comment by fahedouch** [comment]
Some flaky test(s) related to log drivers are disturbing the CI but not releated to this PR

**Review by fahedouch — APPROVED** [review]

**Comment by fahedouch** [comment]
Thanks

**Review by AkihiroSuda — APPROVED** [review]
Thanks
