### PR TITLE
fix: prevent panic in nydus snapshotter inspect

### LINKED ISSUE #3755: nerdctl panic when run inspect --type=image xxxxx with nydus snapshotter
### Description

nerdctl panic on running the command to inspect an image on the host with nydus snapshotter enabled.  The issue exists in the latest release version.   There is no problem if the nydus snapshotter not enabled.

root@xtao7:~# nerdctl inspect --type=image --mode dockercompat registry.servicemgr.xtao:5000/nydus/ubuntu22.04-cuda12.05-torch2.4-huggingface
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd55373]

goroutine 1 [running]:
github.com/containerd/nerdctl/pkg/inspecttypes/dockercompat.ImageFromNative(0xc0001ef080)
	/go/src/github.com/containerd/nerdctl/pkg/inspecttypes/dockercompat/dockercompat.go:296 +0x253
github.com/containerd/nerdctl/pkg/cmd/image.Inspect.func1({0x13b33a0?, _}, {{{0xc0005aa000, 0x55}, 0x0, {{0xc000590040, 0x34}, {0xc0005ac000, 0x47}, 0xbc7, ...}, ...}, ...})
	/go/src/github.com/containerd/nerdctl/pkg/cmd/image/inspect.go:52 +0x205
github.com/containerd/nerdctl/pkg/idutil/imagewalker.(*ImageWalker).Walk(0xc000679568, {0x13b33a0, 0xc00054c000}, {0x7fffc40cd4bb, 0x4e})
	/go/src/github.com/containerd/nerdctl/pkg/idutil/imagewalker/imagewalker.go:81 +0x666
github.com/containerd/nerdctl/pkg/idutil/imagewalker.(*ImageWalker).WalkAll(0x0?, {0x13b33a0, 0xc00054c000}, {0xc0006797c0?, 0x1, 0xedeeb7e7b?}, 0x1)
	/go/src/github.com/containerd/nerdctl/pkg/idutil/imagewalker/imagewalker.go:98 +0xea
github.com/containerd/nerdctl/pkg/cmd/image.Inspect({_, _}, _, {_, _, _}, {{0x13ab7a0, 0xc0001ae008}, {0x0, 0x0, ...}, ...})
	/go/src/github.com/containerd/nerdctl/pkg/cmd/image/inspect.go:64 +0x1a6
main.inspectAction(0xc0011e0300, {0xc0012d8040, 0x1, 0x4?})
	/go/src/github.com/containerd/nerdctl/cmd/nerdctl/inspect.go:147 +0xb7c
github.com/spf13/cobra.(*Command).execute(0xc0011e0300, {0xc0001b0140, 0x4, 0x4})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.xmain()
	/go/src/github.com/containerd/nerdctl/cmd/nerdctl/main.go:136 +0x9f
main.main()
	/go/src/github.com/containerd/nerdctl/cmd/nerdctl/main.go:119 +0x19

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

the nerdctl inspect should work on nydus snapshotter enabled, or provide some alternative solution

### What version of nerdctl are you using?

nerdctl version 2.0.1

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by SpiffyEight77**
## Description

- fix: prevent panic in nydus snapshotter inspect
- close #3755

### CODE REVIEW

File: pkg/inspecttypes/dockercompat/dockercompat.go [hunk 1]
```diff
@@ -340,8 +340,10 @@ func ImageFromNative(nativeImage *native.Image) (*Image, error) {
 
 	if len(imgOCI.History) > 0 {
 		image.Comment = imgOCI.History[len(imgOCI.History)-1].Comment
-		image.Created = imgOCI.History[len(imgOCI.History)-1].Created.Format(time.RFC3339Nano)
-		image.Author = imgOCI.History[len(imgOCI.History)-1].Author
+		if !imgOCI.History[len(imgOCI.History)-1].Created.IsZero() {
+			image.Created = imgOCI.History[len(imgOCI.History)-1].Created.Format(time.RFC3339Nano)
+			image.Author = imgOCI.History[len(imgOCI.History)-1].Author
```
Comment (apostasie) [inline pkg/inspecttypes/dockercompat/dockercompat.go:345]: Does `Author` have to be inside the if test?

**Review by apostasie — CHANGES_REQUESTED** [review]

File: pkg/inspecttypes/dockercompat/dockercompat.go (hunk 1 above)
Comment (SpiffyEight77) [reply pkg/inspecttypes/dockercompat/dockercompat.go]: > Does `Author` have to be inside the if test?

Oops, nice catch! The Author doesn't have to be inside the if test.🙇

**Review by apostasie — APPROVED** [review]

**Comment by apostasie** [comment]
LGTM

@fahedouch if you are around for a review ^

File: pkg/inspecttypes/dockercompat/dockercompat.go [hunk 2]
```diff
@@ -340,7 +340,9 @@ func ImageFromNative(nativeImage *native.Image) (*Image, error) {
 
 	if len(imgOCI.History) > 0 {
 		image.Comment = imgOCI.History[len(imgOCI.History)-1].Comment
-		image.Created = imgOCI.History[len(imgOCI.History)-1].Created.Format(time.RFC3339Nano)
+		if !imgOCI.History[len(imgOCI.History)-1].Created.IsZero() {
+			image.Created = imgOCI.History[len(imgOCI.History)-1].Created.Format(time.RFC3339Nano)
```
Comment (fahedouch) [inline pkg/inspecttypes/dockercompat/dockercompat.go:344]: Is it possible to have `len(imgOCI.History) = 0`?
if yes we need an additional check to avoid slice out-of-range error

Comment (apostasie) [reply pkg/inspecttypes/dockercompat/dockercompat.go:344]: We are already testing for that: `if len(imgOCI.History) > 0 {`

Comment (fahedouch) [reply pkg/inspecttypes/dockercompat/dockercompat.go:344]: cool. Sorry I was reviewing with my phone. 

LGTM

**Review by fahedouch — APPROVED** [review]
Thanks
