### PR TITLE
Fix unstable sort of container list in compose

### LINKED ISSUE #2500: The `--index` in compose command is not  index in container name
### Description

The `--index` in compose command works in error.
The index is not in the container name, and not compatible with docker.

And it works fine in the docker :-)

### Steps to reproduce the issue

1. Use compose file ` /tmp/c.yaml`
```
version: '3.1'

services:
  svc0:
    image: docker.m.daocloud.io/busybox
    command: "sleep infinity"
    deploy:
      replicas: 3
```

2. nerdctl compose -f /tmp/c.yaml up -d
3. nerdctl compose -f /tmp/c.yaml exec --index 1  -it svc0 cat /etc/hosts

```
# <nerdctl>
127.0.0.1       localhost localhost.localdomain
::1             localhost localhost.localdomain
10.4.2.14       svc0 svc0.tmp_default tmp-svc0-3 tmp-svc0-3.tmp_default
10.4.2.12       svc0 svc0.tmp_default tmp-svc0-1 tmp-svc0-1.tmp_default
10.4.2.13       svc0 svc0.tmp_default tmp-svc0-2 tmp-svc0-2.tmp_default
# </nerdctl>
```
4. Show the Ip address by index
``` 
root@kay201:~/oss/nerdctl# nerdctl compose -f /tmp/c.yaml exec --index 1  -it svc0 ip add |grep 10.4.2
    inet 10.4.2.14/24 brd 10.4.2.255 scope global eth0
root@kay201:~/oss/nerdctl# nerdctl compose -f /tmp/c.yaml exec --index 2  -it svc0 ip add |grep 10.4.2
    inet 10.4.2.12/24 brd 10.4.2.255 scope global eth0
root@kay201:~/oss/nerdctl# nerdctl compose -f /tmp/c.yaml exec --index 3  -it svc0 ip add |grep 10.4.2
    inet 10.4.2.13/24 brd 10.4.2.255 scope global eth0
```

We can find that

- The `exec --index 1` is tmp-svc0-3
- The `exec --index 2` is tmp-svc0-1
- The `exec --index 3` is tmp-svc0-2

It's not compatible with docker.

### Describe the results you received and expected

- The `exec --index 1` is tmp-svc0-1
- The `exec --index 2` is tmp-svc0-2
- The `exec --index 3` is tmp-svc0-3

### What version of nerdctl are you using?

Client:
 Version:       v1.5.0-96-ga54ebe00.m
 OS/Arch:       linux/amd64
 Git commit:    a54ebe008057e68d9a5ead5d675bdf6e9f20a569
 buildctl:
  Version:      v0.12.1
  GitCommit:    bb857a0d49f45aa0ce9cd554b78d4075553e20f9

Server:
 containerd:
  Version:      v1.7.1
  GitCommit:    1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc:
  Version:      1.1.7
  GitCommit:    v1.1.7-0-g860f061b

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by yuchanns**
fix #2500

### CODE REVIEW

File: cmd/nerdctl/compose_exec_linux_test.go [hunk 1]
```diff
@@ -207,3 +211,83 @@ services:
...
+    image: %s
+    command: "sleep infinity"
+    deploy:
+      replicas: 3
+`, testutil.CommonImage)
+
+	comp := testutil.NewComposeDir(t, dockerComposeYAML)
+	t.Cleanup(func() {
+		comp.CleanUp()
+	})
```
Comment (djdongjin) [inline cmd/nerdctl/compose_exec_linux_test.go:232]: what's the difference compared to call `defer comp.CleanUp()` directly?

File: cmd/nerdctl/compose_exec_linux_test.go [hunk 2]
```diff
@@ -207,3 +211,83 @@ services:
...
+	t.Logf("projectName=%q", projectName)
+
+	base.ComposeCmd("-f", comp.YAMLFullPath(), "up", "-d", "svc0").AssertOK()
+	t.Cleanup(func() {
+		base.ComposeCmd("-f", comp.YAMLFullPath(), "down", "-v").AssertOK()
+	})
+
+	// try random 5~10 times to ensure that results are stable
+	r, _ := rand.Int(rand.Reader, big.NewInt(5))
+	for i := 0; i < int(r.Int64()+5); i++ {
```
Comment (djdongjin) [inline cmd/nerdctl/compose_exec_linux_test.go:243]: can we just use a fixed number? e.g., 5 times or 10 times

Comment (djdongjin) [inline cmd/nerdctl/compose_exec_linux_test.go:243]: can we just use a fixed number? e.g., 5 times or 10 times

File: cmd/nerdctl/compose_exec_linux_test.go [hunk 3]
```diff
@@ -207,3 +211,83 @@ services:
...
+	var ip string
+	lines := strings.Split(output, "\n")
+	for _, line := range lines {
+		if !strings.Contains(line, "inet ") {
+			continue
+		}
+		fields := strings.Fields(line)
+		if len(fields) <= 1 {
+			continue
+		}
```
Comment (djdongjin) [inline cmd/nerdctl/compose_exec_linux_test.go:288]: should we do the same check in line 259?

File: pkg/composer/exec.go [hunk 4]
```diff
@@ -54,9 +58,29 @@ func (c *Composer) Exec(ctx context.Context, eo ExecOptions) error {
...
+	for _, container := range containers {
+		info, err := container.Info(ctx, containerd.WithoutRefreshedMetadata)
+		if err != nil {
+			if errdefs.IsNotFound(err) {
+				continue
+			}
+			return fmt.Errorf("fail to get container info for service: %s: %s", eo.ServiceName, err)
+		}
+		name := info.Labels[labels.Name]
+		segs := strings.Split(name, "-")
```
Comment (djdongjin) [inline pkg/composer/exec.go:75]: nit: uses the const instead of plain string `"-"`

https://github.com/containerd/nerdctl/blob/0fbf4967b3bea2a1f8bc7212aa3390abae091bf8/pkg/composer/serviceparser/serviceparser.go#L52

File: cmd/nerdctl/compose_exec_linux_test.go [hunk 5]
```diff
@@ -207,3 +211,83 @@ services:
...
+			base.ComposeCmd(append(cmds, "ip", "addr", "show", "dev", "eth0")...).
+				AssertOutWithFunc(func(stdout string) error {
+					ip := findIP(stdout)
+					if ip == nil {
+						return errors.New("fail to get the real ip address")
+					}
+					realIP = ip.String()
+					return nil
+				})
+			assert.Equal(t, realIP, expectIP)
```
[the remark this answers is not in the document]
Comment (yuchanns) [reply cmd/nerdctl/compose_exec_linux_test.go:273]: There are wide uses of `gotest.tools/v3/assert` in nerdctl already. It's better to keep the consistency IMO.

File: pkg/composer/exec.go (hunk 4 above)
Comment (yuchanns) [reply pkg/composer/exec.go:75]: make sense

File: cmd/nerdctl/compose_exec_linux_test.go (hunk 3 above)
Comment (yuchanns) [reply cmd/nerdctl/compose_exec_linux_test.go:288]: make sense

File: cmd/nerdctl/compose_exec_linux_test.go (hunk 2 above)
Comment (yuchanns) [reply cmd/nerdctl/compose_exec_linux_test.go:243]: Done.

File: cmd/nerdctl/compose_exec_linux_test.go (hunk 1 above)
Comment (yuchanns) [reply cmd/nerdctl/compose_exec_linux_test.go:231]: `t.CleanUp` ensures resources clean up after all subtests are done, which is useful when subtests enable `t.Parallel`
FYI: https://github.com/golang/go/issues/37333

File: cmd/nerdctl/compose_exec_linux_test.go [hunk 6]
```diff
@@ -207,3 +209,85 @@ services:
...
+						fields := strings.Fields(line)
+						if len(fields) == 0 {
+							continue
+						}
+						expectIP = fields[0]
+						return nil
+					}
+					return errors.New("fail to get the expected ip address")
+				})
+			base.ComposeCmd(append(cmds, "ip", "addr", "show", "dev", "eth0")...).
```
Comment (AkihiroSuda) [inline cmd/nerdctl/compose_exec_linux_test.go:264]: Can we use `hostname -i` ?

File: pkg/composer/exec.go [hunk 7]
```diff
@@ -54,9 +59,29 @@ func (c *Composer) Exec(ctx context.Context, eo ExecOptions) error {
 		return fmt.Errorf("index (%d) out of range: only %d running instances from service %s",
 			eo.Index, len(containers), eo.ServiceName)
 	}
-	container := containers[eo.Index-1]
+	if len(containers) == 1 {
+		return c.exec(ctx, containers[0], eo)
+	}
+	// The sort of containers is not stable
+	// so we compare the index by its name
```
Comment (AkihiroSuda) [inline pkg/composer/exec.go:66]: Can't we use https://pkg.go.dev/sort#SliceStable ?

File: cmd/nerdctl/compose_exec_linux_test.go [hunk 8]
```diff
@@ -207,3 +209,85 @@ services:
 	base.ComposeCmdWithHelper(unbuffer, "-f", comp.YAMLFullPath(), "exec", "-t=false", "svc0", "stty").AssertFail()                         // `-i`
 	base.ComposeCmdWithHelper(unbuffer, "-f", comp.YAMLFullPath(), "exec", "-i=false", "-t=false", "svc0", "stty").AssertFail()
 }
+
+func TestComposeExecWithIndex(t *testing.T) {
+	testutil.DockerIncompatible(t)
```
Comment (AkihiroSuda) [inline cmd/nerdctl/compose_exec_linux_test.go:214]: Why?

Comment (yuchanns) [reply cmd/nerdctl/compose_exec_linux_test.go:214]: Oops! Just a copy. Removing.

File: cmd/nerdctl/compose_exec_linux_test.go (hunk 6 above)
Comment (yuchanns) [reply cmd/nerdctl/compose_exec_linux_test.go:264]: I tried it. and found another inconsistent behavior. When using `hostname -i` for docker, I got only one IP respect with the index. While nerdctl just give me all the three IPs.
I think this is unrelated to the current issue. So let me keep this unchanged.

File: pkg/composer/exec.go (hunk 7 above)
Comment (yuchanns) [reply pkg/composer/exec.go:66]: Make sense

File: cmd/nerdctl/compose_exec_linux_test.go (hunk 6 above)
Comment (Zheaoli) [reply cmd/nerdctl/compose_exec_linux_test.go:264]: I think `docker compose` has different DNS behavior from `nerdctl compose`. I think `ip addr` would be better during the test

**Review by AkihiroSuda — APPROVED** [review]
Thanks

File: cmd/nerdctl/compose_exec_linux_test.go (hunk 8 above)
Comment (AkihiroSuda) [reply cmd/nerdctl/compose_exec_linux_test.go]: > I am wondering if it still keeps v1.

No
