### PR TITLE
Prevent reference filter from failing on dangling images

### LINKED ISSUE #3852: `nerdctl images --filter` is broken with dangling untagged images
### Description

```
nerdctl pull busybox
nerdctl run --name foo -d busybox sleep inf
nerdctl rmi -f busybox
nerdctl images
nerdctl images --filter reference="test*"
```

`FATA[0000] unable to parse image name: : while filtering by reference because of invalid reference format`

The issue is in the way we handle dangling images (`<none>`).

Went back to august to see if it was a recent regression and seems to be alreadt there, if I am not mistaken.

Will do more tests with older versions.

### Steps to reproduce the issue

_No response_

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
Fix #3852 

It seems likely that the same problem exists in other places.

Solutions:
a. review every code location where we manipulate the result of `imagesservice.List` and account for ":"
b. modify referenceutil to account for it

Thoughts?

~~Also 🍿 on the CI to see if that was a change in containerd 2.0.~~

### CODE REVIEW

**Comment by apostasie** [comment]
Also if somebody wants to add a test for that, that would be nice.
I don't have much energy for that right now - just bug-fixing drive-by.

**Comment by apostasie** [comment]
Note: this is definitely affecting rmi as well.

Confusing message reads: `Stderr:   time="2025-01-27T16:21:20-08:00" level=fatal msg="1 errors:\nimage \":\": already exists"`

File: pkg/imgutil/filtering.go [hunk 1]
```diff
@@ -325,6 +325,11 @@ func matchesAllLabels(imageCfgLabels map[string]string, filterLabels map[string]
 func matchesReferences(image images.Image, referencePatterns []string) (bool, error) {
 	var matches int
 
+	// Containerd returns ":" for dangling untagged images
+	if image.Name == ":" {
+		return false, nil
+	}
+
```
Comment (fahedouch) [inline pkg/imgutil/filtering.go:332]: Should we consider fixing the dangling untagged image representation from `:` to `<none>` on the containerd side for better clarity ?

File: pkg/imgutil/filtering.go [hunk 2]
```diff
@@ -325,6 +325,11 @@ func matchesAllLabels(imageCfgLabels map[string]string, filterLabels map[string]
 func matchesReferences(image images.Image, referencePatterns []string) (bool, error) {
 	var matches int
 
+	// Containerd returns ":" for dangling untagged images
```
Comment (fahedouch) [inline pkg/imgutil/filtering.go:328]: Please add the issue link as this may evolve

File: pkg/imgutil/filtering.go (hunk 1 above)
Comment (apostasie) [reply pkg/imgutil/filtering.go:332]: Maybe. Problem is that `<none>` is not a valid image name, so, this has to be carefully done and figuring out everywhere we are manipulating these.

File: pkg/imgutil/filtering.go (hunk 2 above)
Comment (apostasie) [reply pkg/imgutil/filtering.go:328]: Sure.

Comment (apostasie) [reply pkg/imgutil/filtering.go]: Done.

File: pkg/imgutil/filtering.go (hunk 1 above)
Comment (apostasie) [reply pkg/imgutil/filtering.go:332]: Of course ":" is not a valid image name either...

Comment (fahedouch) [reply pkg/imgutil/filtering.go:332]: at least we can stick with docker naming convention which is `<none>`.
let me open an issue ticket on containerd to gather their input."

**Review by fahedouch — APPROVED** [review]
Thanks
