### PR TITLE
Fix `operation not permitted` with systemd-homed

### LINKED ISSUE #2056: [Rootless] Issues when using systemd-homed (`FATA[0000] operation not permitted`)
### Discussed in https://github.com/containerd/nerdctl/discussions/2017

<div type='discussions-op-text'>

<sup>Originally posted by **thomascft** February 15, 2023</sup>
I have a few machines running Arch Linux and one of them I decided to try out systemd-homed.  I followed the guide on https://rootlesscontaine.rs/ and have a working rootless containerd instance running on my non-homed laptop. During diagnosis I created a regular account on problematic system and everything worked fine. I creted a fresh homed and it showed the same symptoms. Below are some of the problematic commands and their respective debug outputs. 

`nerdctl run --debug-full --rm hello-world`
```
DEBU[0000] stateDir: /run/user/60121/containerd-rootless
DEBU[0000] rootless parent main: executing "/usr/bin/nsenter" with [-r/ -w/ --preserve-credentials -m -n -U -t 737 -F nerdctl run --debug-full --rm hello-world]
DEBU[0000] verification process skipped
FATA[0000] operation not permitted
```
After that I tried running the alpine image. 
`nerdctl run --debug --rm -it alpine`
Here's the resulting error: 
```
DEBU[0000] stateDir: /run/user/60121/containerd-rootless
DEBU[0000] rootless parent main: executing "/usr/bin/nsenter" with [-r/ -w/ --preserve-credentials -m -n -U -t 27415 -F nerdctl --debug-full run --rm -it alpine]
DEBU[0000] verification process skipped
FATA[0000] operation not permitted
```
I decided to try the archlinux image and it worked without any errors. </div>

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #2056

Note: in addition to this PR, the subid ranges in`/etc/subuid` and `/etc/subgid` have to begin from 524288
e.g.,
```
test:524288:65536
```

Otherwise running most images will fail with `value too large for defined data type`

```console
$ ./nerdctl run -it --rm alpine:3.17.0
docker.io/library/alpine:3.17.0:                                                  resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:c0d488a800e4127c334ad20d61d7bc21b4097540327217dfab52262adc02380c: waiting        |--------------------------------------|
config-sha256:49176f190c7e9cdb51ac85ab6c6d5e4512352218190cd69b08e6fd803ffbf3da:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:c158987b05517b6f2c5913f3acef1f2182a32345a304fe357e3ace5fadcad715:    downloading    |+++++++++++++++++++++++---------------|  2.0 MiB/3.2 MiB
elapsed: 10.4s                                                                    total:  2.0 Mi (197.1 KiB/s)
FATA[0010] failed to extract layer sha256:ded7a220bb058e28ee3254fbba04ca90b679070424424761a53a043b93b612bf: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount762573051:
failed to Lchown "/var/lib/containerd/tmpmounts/containerd-mount762573051/etc/shadow" for UID 0, GID 42: lchown /var/lib/containerd/tmpmounts/containerd-mount762573051/etc/shadow: value too large for defined data type: unknown
```

### CODE REVIEW

File: cmd/nerdctl/container_run_mount.go [hunk 1]
```diff
@@ -189,6 +191,25 @@ func generateMountOpts(ctx context.Context, cmd *cobra.Command, client *containe
 					return nil, nil, nil, err
 				}
 			}
+		} else if runtime.GOOS == "linux" {
+			for _, m := range mounts {
+				m := m
+				defer unmounter(m.Source)
+				if m.Type == "bind" && userns.RunningInUserNS() {
+					// For https://github.com/containerd/nerdctl/issues/2056
+					unpriv, err := mountutil.UnprivilegedMountFlags(m.Source)
```
Comment (manugupt1) [inline cmd/nerdctl/container_run_mount.go:200]: Should we have an integ or an unit test for this that the unpriv mount flags are carried over?
If my understanding is correct; a user will still have to ensure that the right subuid and subgid ranges are specified.

Comment (AkihiroSuda) [reply cmd/nerdctl/container_run_mount.go:200]: Ideally yes, but not sure how to do that

**Review by manugupt1 — APPROVED** [review]

File: cmd/nerdctl/container_run_mount.go [hunk 2]
```diff
@@ -189,6 +190,25 @@ func generateMountOpts(ctx context.Context, cmd *cobra.Command, client *containe
...
+					if err != nil {
+						return nil, nil, nil, err
+					}
+					m.Options = strutil.DedupeStrSlice(append(m.Options, unpriv...))
+				}
+				if err := m.Mount(tempDir); err != nil {
+					if rmErr := s.Remove(ctx, tempDir); rmErr != nil && !errdefs.IsNotFound(rmErr) {
```
Comment (fahedouch) [inline cmd/nerdctl/container_run_mount.go:206]: not sure! but why not appending the layerID to the root as done [before](https://github.com/containerd/nerdctl/pull/2064/files#diff-60fca3f0ed2e71d0b9fa79615032aa480ba6df95734d5835e971d87888f43211L184).

Comment (AkihiroSuda) [reply cmd/nerdctl/container_run_mount.go:206]: IIUC it was never appended for linux
