### PR TITLE
Fix broken TestImageInspectDifferentValidReferencesForTheSameImage

### LINKED ISSUE #3479: [URGENT] TestImageInspectDifferentValidReferencesForTheSameImage is broken on main
### Description

Test assumes busybox from Hub would not change semantics (eg: that `stable` and `latest` would always be the same image).
This changed a few hours ago.

All builds will be broken until we land a fix.

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

@AkihiroSuda am on it.
Can you assign this to me?

### PR DESCRIPTION
**Pull request by apostasie**
Fix #3479

Reviewers: since the official `busybox` is a moving target, and has just shifted under our feet, I replaced it with a copy under `apostasie/busybox`.

This is a short term fix so that the CI does not stay bust - but I do not like the idea of having images in my personal account.

(Part of) the current intent of this test was apparently to test variants of image names only available on the hub.

To get rid of my images here, here are our options:
- trash the test, and reduce the scope to not use short names
- implement hosts.toml properly, so that we can start using ghcr with authentication as a mirror to Hub (in progress, but will take time)
- #3480

### CODE REVIEW

**Comment by apostasie** [comment]
cc @AkihiroSuda

Tagging @manugupt1 

Review at your convenience.
CI failures are a Github Actions fluke, and the usual IPFSCompose.

File: cmd/nerdctl/image/image_inspect_test.go [hunk 1]
```diff
@@ -94,16 +90,16 @@ func TestImageInspectDifferentValidReferencesForTheSameImage(t *testing.T) {
 			nerdtest.Private,
 		),
 		Setup: func(data test.Data, helpers test.Helpers) {
-			helpers.Ensure("pull", "alpine", "--platform", platform)
-			helpers.Ensure("pull", "busybox", "--platform", platform)
-			helpers.Ensure("pull", "busybox:stable", "--platform", platform)
-			helpers.Ensure("pull", "registry-1.docker.io/library/busybox", "--platform", platform)
-			helpers.Ensure("pull", "registry-1.docker.io/library/busybox:stable", "--platform", platform)
```
Comment (AkihiroSuda) [inline cmd/nerdctl/image/image_inspect_test.go:101]: Can we just remove this line and then keep using the official image?

Comment (apostasie) [reply cmd/nerdctl/image/image_inspect_test.go:101]: Sure, we can.
That is not just this line though - stable is used throughout.

File: cmd/nerdctl/image/image_inspect_test.go [hunk 2]
```diff
@@ -71,16 +70,12 @@ func TestImageInspectSimpleCases(t *testing.T) {
 func TestImageInspectDifferentValidReferencesForTheSameImage(t *testing.T) {
 	nerdtest.Setup()
 
-	platform := runtime.GOOS + "/" + runtime.GOARCH
```
Comment (apostasie) [inline cmd/nerdctl/image/image_inspect_test.go:74]: Earlier version of this test was using linux/amd64, because it was hardcoding the sha.
When I rewrote the test a few weeks ago, I removed the static sha and replaced by a lookup, allowing to use whatever platform - though I did not remove the platform mechanism itself for some reason.
It is unnecesary.

**Comment by AkihiroSuda** [comment]
Could you update the commit message to explain why `:stable` is no longer testable?

**Comment by apostasie** [comment]
CI is green-ish (Docker failure is unrelate and will get fixed in #3464).

**Comment by apostasie** [comment]
> Could you update the commit message to explain why `:stable` is no longer testable?

Doing now.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
