### PR TITLE
[P0] Fix #3513 (`[MAJOR] content digest not found`)

### LINKED ISSUE #3513: [MAJOR] content digest not found
This is meant to collect more information about the issue known as "content digest not found".

While #3435 (and follow-up for IPFS) did address the most obvious cases, we obviously have more.

Here is the currently know list:
- #3509
- #3510
- #3512

The gist of it appears to be, at this point:
- seems like containerd `converter.Convert` (calling on imageservice.Create) may return an image with missing content in some circumstances
- seems like any call to `content.ReadBlob` (specifically as seen inside imgutil) may fail and should be gated by an operation to first force fetch the blob in question

At this point, above is speculative, although it seems consistent with the debugging info in the tickets.

### PR DESCRIPTION
**Pull request by apostasie**
### Current status

Discussion and patch upstream: https://github.com/containerd/containerd/pull/11628

TL;DR here: this PR here on nerdctl _does seem to fix our issues_ (many runs of the CI with no issue), because it entirely bypasses `converter.Convert` `Delete` logic which _seems to trigger some underlying containerd issue related to lease and deletion_ (<- my opinion, unverified).

My patch upstream does ALSO fix our issue, with a clear reproducer, although it probably just avoids the underlying containerd problem.

-------------------------------------------------------------
### Original post below

It looks like containerd `imagestore.Delete` is asynchronous by default.

If you want a synchronous delete, you have to pass an additional opt.

Of course, this seems to be a problem when you:
- check if the image exist
- delete it (async) if it does
- create a new version of it

This seem to be the case (actually, it is worse) for https://github.com/containerd/containerd/blob/af013606262f9df1de4cc80688725a15a375fb3a/core/images/converter/converter.go#L120-L121
... where convert.Convert just forcefully delete, whether or not the image existed, async...

This of course is also something we are doing internally.

This PR addresses these issues:
- ensure we delete SYNCHRONOUSLY where it matters
- honor the async option when there is one
- wrap / workaround containerd (* maybe) faulty implementation of convert

At this point, this is still a hunch - but for the first time I feel confident that we may be reaching the bottom of it, as this explanation closely matches the soul-destroying symptoms we have witnessed in eg: https://github.com/containerd/nerdctl/issues/3509#issuecomment-2398236766 

and more generally, with anything touching containerd `Convert` (see #3513).

I will close an open this PR many times and confirm that the infamous #3513 is finally gone, but I would like the expert opinion of @lingdie on this - if you have time for a quick review.

Upstream PR: https://github.com/containerd/containerd/pull/11628

Note that this PR here does not try to do more than that - there MAY still be places where we would need to `EnsureContent`.

EDIT: looks like containerd maintainer disagree with this, so, maybe I am misreading this.
Anyhow, I will keep closing / opening and run the CI - we are currently at:
- four runs without failure
- fifth run failed on Github cache
- sixth run failure is #4046

### CODE REVIEW

**Comment by apostasie** [comment]
Green once.

File: pkg/cmd/builder/build.go [hunk 1]
```diff
@@ -127,7 +127,7 @@ func Build(ctx context.Context, client *containerd.Client, options types.Builder
 			if _, err := imageService.Create(ctx, image); err != nil {
 				// if already exists; skip.
 				if errors.Is(err, errdefs.ErrAlreadyExists) {
-					if err = imageService.Delete(ctx, targetRef); err != nil {
+					if err = imageService.Delete(ctx, targetRef, images.SynchronousDelete()); err != nil {
```
Comment (apostasie) [inline pkg/cmd/builder/build.go:130]: This _may_ explain some of the "internal: not found" errrors we sometimes see when building.

**Comment by apostasie** [comment]
Green twice. 😓

File: pkg/imgutil/converter/convert.go [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+
+	"github.com/containerd/containerd/v2/core/images"
+	"github.com/containerd/containerd/v2/core/images/converter"
+)
+
+// It looks like containerd converter.Convert is faulty.
+// When dstRef != srcRef, convert will first forcefully delete dstRef,
+// apparently *asynchronously*, then create the image.
+// This is racy, and the deletion may kick in after the creation.
+// This here is to workaround the bug, by manually creating the image first,
```
Comment (AkihiroSuda) [inline pkg/imgutil/converter/convert.go:30]: Could you add a link to the issue ticket?

Comment (apostasie) [reply pkg/imgutil/converter/convert.go:30]: Done.
Massaged the text a bit too.

File: pkg/imgutil/converter/convert.go [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+	"context"
+
+	"github.com/containerd/containerd/v2/core/images"
+	"github.com/containerd/containerd/v2/core/images/converter"
+)
+
+// Something seems wrong in converter.Convert.
+// When dstRef != srcRef, convert will first forcefully delete dstRef,
+// *asynchronously*, then create the image.
+// This seems to cause a race conditions, and the deletion may kick in after the creation.
```
Comment (fahedouch) [inline pkg/imgutil/converter/convert.go:29]: the lease is not maintained during the creation ? 🤔

File: pkg/imgutil/converter/convert.go [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+	imageService := client.ImageService()
+
+	img, err := imageService.Get(ctx, srcRef)
+	if err != nil {
+		return nil, err
+	}
+
+	img.Name = dstRef
+
+	_ = imageService.Delete(ctx, img.Name, images.SynchronousDelete())
```
[the remark this answers is not in the document]
Comment (apostasie) [reply pkg/imgutil/converter/convert.go:48]: It does not seem like we do need to do it (note that I am not 100% familiar with it yet).

Indeed, my containerd patch does away with the delete (which is the source of the problem), and instead tries to `update`, then if it fails tries to `create`.

This patch here is opting for the least amount of change, but of course happy to clean-up a bit more if we want.

lmk your preference.

File: pkg/imgutil/converter/convert.go (hunk 3 above)
Comment (apostasie) [reply pkg/imgutil/converter/convert.go:29]: No clue.

My gut intuition is that this thing faceplants when the old ref is actually exactly the same image as new ref.

Note that patching containerd to also use a **sync** delete does NOT fix the issue. 🤔

Anyhow, for me the bottom-line really is:
- do not use leases + delete - clealy buggy
- do not use async delete - counter-intuitive

File: pkg/imgutil/converter/convert.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (fahedouch) [reply pkg/imgutil/converter/convert.go:48]: LGTM to unblock the situation. But in the short and medium term, I don't want to move the containerd logic to nerdctl.

**Review by fahedouch — APPROVED** [review]
lgtm to fix these problems that have been going on for a long time but the real fix should be done on the containerd side

**Comment by apostasie** [comment]
> lgtm to fix these problems that have been going on for a long time but the real fix should be done on the containerd side

Purely for the `converter.Convert` part, proposal is there: https://github.com/containerd/containerd/pull/11628 if you feel like it is right.

I will _eventually_ get to the true bottom of this pit and figure out if there is indeed a bug / race in the deletion mechanism (which I do believe there is), but I need time and motivation...

**Comment by apostasie** [comment]
Suggesting we merge this soon.

I would like to get as much CI watching time with that patch merged-in before it gets into the general audience with the next patch release.

**Comment by fahedouch** [comment]
> Suggesting we merge this soon.
> 
> I would like to get as much CI watching time with that patch merged-in before it gets into the general audience with the next patch release.

I would have preferred to see @AkihiroSuda 's opinion on this, but he is certainly busy with KubeCon. We will merge this and roll back later if needed.

**Review by fahedouch — APPROVED** [review]
I believe that the real fix should be done on the daemon side, but to unblock multiple issues we have on the CLI, let's merge the fix and see what the patch on the containerd side will bring.

**Comment by AkihiroSuda** [comment]
Thanks, LGTM
