### PR TITLE
[Design Review] StartedAt for containers

### LINKED ISSUE #3002: container inspect finishedAt date set to zero
### Description

If a container has not exited yet, the FinishedAt time on inspect will be set to "0001-01-01T00:00:00Z"

This does not make much sense IMHO.

Suggesting to test `if ExitTime.IsZero()` and only set FinishedAt if not zero.

Let me know if you are ok with this and I ll batch that into my dockercompat cleanup work.

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

FinishedAt to not display a bogus date is expected.

### What version of nerdctl are you using?

1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
This is a proposal to implement StartedAt (see #2335).

Short of containerd exposing this, the right place to implement is likely inside `ocihook.onStart` (to account for containers with a restart policy).

I do not know how or if it is possible to modify annotations from inside ocihooks. If it is, that would be a better solution and would love to see an example of how to do that.

So, instead, I am maintaining a new state file inside the stateDir.
For that, there is a `LifecycleState` struct that we can leverage in the future to store more information that has to be updated inside ocihooks.

This PR also contains a two lines minor change to fix #3002.

Let me know what you folks think.
As usual, happy to adapt to feedback on the right way to do this.

### CODE REVIEW

**Comment by apostasie** [comment]
I did bust a few tests - at least `TestContainerFromNative` which expect these 0 dates.

If the design here is fine with you folks, I will fix the tests.

File: pkg/ocihook/ocihook.go [hunk 1]
```diff
@@ -284,7 +286,7 @@ func getNetNSPath(state *specs.State) (string, error) {
 		return netNsPath, nil
 	}
 
-	if state.Pid == 0 && !netNsFound {
```
Comment (apostasie) [inline pkg/ocihook/ocihook.go:287]: This is unnecessary (always true)

File: pkg/ocihook/state/state.go [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+	err := lockutil.WithDirLock(lf.stateDir, fun)
+	if err != nil {
+		return fmt.Errorf("failed to lock state dir: %w", err)
+	}
+
+	return nil
+}
+
+func (lf *LifecycleState) Read() error {
+	data, err := os.ReadFile(filepath.Join(lf.stateDir, "lifecycle.json"))
```
Comment (AkihiroSuda) [inline pkg/ocihook/state/state.go:61]: "lifecycle.json" should be a `const`, and should be documented in https://github.com/containerd/nerdctl/blob/main/docs/dir.md

File: pkg/ocihook/state/state.go [hunk 3]
```diff
@@ -0,0 +1,85 @@
...
+// This is meant to store stateful informations about containers that we receive from ocihooks
+// We are storing them inside the container statedir
+// Note that you MUST use WithLock to perform any operation (like Read or Write).
+// Typically:
+// lf.WithLock(func ()error {
+//   lf.Read()
+//   // Modify something on the object
+//   lf.StartedAt = ...
+//   lf.Write()
+// })
```
Comment (AkihiroSuda) [inline pkg/ocihook/state/state.go:38]: `Read()` and `Write()` should be named like `Load()` and `Store()` ?

Comment (apostasie) [reply pkg/ocihook/state/state.go:38]: Ok.
Opting for Load / Save.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

File: pkg/ocihook/state/state.go [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+
+func NewLifecycleState(stateDir string) *LifecycleState {
+	return &LifecycleState{
+		stateDir: stateDir,
+	}
+}
+
+type LifecycleState struct {
+	stateDir  string
+	StartedAt int64 `json:"started_at"`
```
Comment (AkihiroSuda) [inline pkg/ocihook/state/state.go:52]:
```suggestion
	StartedAt time.Time `json:"started_at"`
```

Comment (apostasie) [reply pkg/ocihook/state/state.go]: Ok.
Last version now serializes and unserialize `time.Time` instead of timestamp.

@AkihiroSuda PTAL

**Comment by apostasie** [comment]
Reviewers: moby seems really inconsistent with their use of UTC vs. Local.

I personally think we should be consistent (and always display local) - we might want to review that across the entire codebase.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
