### PR TITLE
Pass https://index.docker.io/v1/ to GetAuthConfig() for Docker Hub

### LINKED ISSUE #1263: `nerdctl pull` calls `docker-credential-xxx get` with hostname instead of ServerURL
### Description

`nerdctl login` stores Docker Hub credentials under the ServerURL `https://index.docker.io/v1/`.

But when pushing an image to the registry, it tries to fetch the credentials using just the registry hostname, i.e. `index.docker.io`. For some credential helpers (e.g. `docker-credential-osxkeychain`) this works, but for others (e.g. `docker-credential-pass`, and probably `docker-credential-secretservice`) it doesn't.

See https://github.com/rancher-sandbox/rancher-desktop/issues/2553 for some testing with the mock `docker-credential-none` helper.

### Steps to reproduce the issue

1. nerdctl login
2. nerdctl pull busybox
3. nerdctl tag busybox my-id/busybox:latest
4. nerdctl push my-id/busybox:latest

### Describe the results you received and expected

I expect to be able to push to the Docker Hub after logging in, while using the Linux credential helpers. They work correctly with the `docker` cli, so that one seems to query credentials with the full ServerURL.

### What version of nerdctl are you using?

0.22.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Rancher Desktop for macOS

### Host information

$ nerdctl info
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: v1.6.6
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.55-0-virt
 Operating System: Alpine Linux v3.16
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.809GiB
 Name: lima-rancher-desktop
 ID: 55b121a9-8fc0-4c62-8e30-672de557dfab

### PR DESCRIPTION
**Pull request by jandubois**
This is an exception; other registries are stored by hostname alone.

The same thing is done in the docker-cli in `ResolveAuthConfig` from `cli/command/registry.go`:

```go
	if index.Official {
		configKey = registry.IndexServer
	}
	a, _ := cli.ConfigFile().GetAuthConfig(configKey)
```

Where `registry.IndexServer` comes from `docker/registry/config.go`:

```go
	// IndexHostname is the index hostname, used for authentication and image search.
	IndexHostname = "index.docker.io"
	// IndexServer is used for user auth and image search
	IndexServer = "https://" + IndexHostname + "/v1/"
```

Fixes #1263

### CODE REVIEW

File: pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go [hunk 1]
```diff
@@ -196,14 +197,14 @@ func NewAuthCreds(refHostname string) (AuthCreds, error) {
...
-			// - authConfigHostname:       "index.docker.io"
+			// - authConfigHostname:       "https://index.docker.io/v1/" (registry.IndexServer)
 			// - ac.ServerAddress:         "https://index.docker.io/v1/".
 			if !isAuthConfigEmpty(ac) {
 				if ac.ServerAddress == "" {
 					// This can happen with Amazon ECR: https://github.com/containerd/nerdctl/issues/733
 					logrus.Debugf("failed to get ac.ServerAddress for authConfigHostname=%q (refHostname=%q)",
 						authConfigHostname, refHostname)
-				} else {
+				} else if authConfigHostname != registry.IndexServer {
```
Comment (manugupt1) [inline pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go:207]: What happens in the default case now?

Comment (jandubois) [reply pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go:207]: Nothing. The whole block is just an assertion anyways.

We could check that `ac.ServerAddress == registry.IndexServer` and return an error if it isn't. I guess I'm going to add it; it doesn't hurt.

Comment (jandubois) [reply pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go]: Done this now; makes the diff easier to understand too, so is a good thing.

Comment (jandubois) [reply pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go]: Sorry, I did one more change to move the check for `authConfigHostname == registry.IndexServer` all the way to the top to make sure it fails when `ac.ServerAddress == ""`, which should never happen for the IndexServer.

**Review by junnplus — APPROVED** [review]
LGTM, thank!

**Review by Zheaoli — APPROVED** [review]
LGTM!

**Review by AkihiroSuda — APPROVED** [review]
Thanks
