### PR TITLE
Ensure all layers are here when tagging, committing, saving, or converting

### LINKED ISSUE #827: Cannot commit and push container image from Kubernetes pods
Hello folks! :wave:

I'm experiencing a strange behavior while committing a container (from Kubernetes pod) and pushing it to some container registry after. I always get the same error from the push command: `content digest sha256:898c46f3b1a1f39827ed135f020c32e2038c87ae0690a8fe73d94e5df9e6a2d6: not found`.

I'm filing this issue here but there's a chance the problem is on containerd side because I've already seen it working in an earlier version. I'm trying to find out which version it stopped to work.

I'm still investigating but no idea so far... suggestions are welcome. 

### Steps to reproduce:

1. Create an arbitrary Kubernetes pod (for simplicity w/ just one container).
```
$ kubectl run --image tsuru/go:latest my-app -- sleep Inf
```

2. Execute arbitrary commands to generate changes in the container image (to be committed):
```
$ kubectl exec my-app -- mkdir -p /tmp/foo/bar
```

3. Commit the container to a local image:
```bash
$ CONTAINER_ID=$(kubectl get pods my-app -o 'jsonpath={ .status.containerStatuses[0].containerID }' | sed -E 's|(.+)://||g')
$ nerdctl --namespace k8s.io commit ${CONTAINER_ID} registry.example.com/my-app:v1
```
4. Push to local registry (no credentials needed):
```
$ nerdctl --namespace k8s.io push registry.example.com/my-app:v1
FATA[0000] failed to create a tmp single-platform image "registry.example.com/my-app:v1-tmp-reduced-platform": content digest sha256:898c46f3b1a1f39827ed135f020c32e2038c87ae0690a8fe73d94e5df9e6a2d6: not found
```

### Environment information: 

* nerdctl:  `0.17.0`
* containerd: `v1.4.12 7b11cfaabd73bb80907dd23182b9347b4245eb5d`
* OS: `Buildroot 2021.02.4` (from minikube)
* Kernel: `4.19.202`
* Kubernetes version: `v1.20.6`
* kubectl version: `v1.20.6`
* Minikube: `v1.25.1`

### LINKED ISSUE #2327: flaky test: `content digest sha256:xxx: not found` in CI
## Description

There are often some test errors in the CI,

It seems the image is not pulled.

Log:
```
2023-06-23T10:00:28.6954646Z === RUN   TestRunCustomRootfs
2023-06-23T10:00:28.6956107Z     container_run_linux_test.go:57: assertion failed: res.ExitCode is not exitCode: time="2023-06-23T10:00:28Z" level=fatal msg="failed to get reader: content digest sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15: not found"
2023-06-23T10:00:28.6956612Z         
2023-06-23T10:00:28.6956905Z --- FAIL: TestRunCustomRootfs (0.30s)
2023-06-23T10:00:28.6957247Z FAIL github.com/containerd/nerdctl/cmd/nerdctl.TestRunCustomRootfs (0.30s)
2023-06-23T10:03:31.0098479Z === RUN   TestImageConvertNydus
2023-06-23T10:03:31.0099449Z     image_convert_linux_test.go:41: assertion failed: res.ExitCode is not exitCode: time="2023-06-23T10:03:31Z" level=fatal msg="content digest sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15: not found"
2023-06-23T10:03:31.0099954Z         
2023-06-23T10:03:31.0100273Z --- FAIL: TestImageConvertNydus (0.37s)
2023-06-23T10:03:31.0100643Z FAIL github.com/containerd/nerdctl/cmd/nerdctl.TestImageConvertNydus (0.37s)
2023-06-23T10:03:31.4190709Z === RUN   TestImageConvertZstdChunked
2023-06-23T10:03:31.4197555Z     image_convert_test.go:52: assertion failed: res.ExitCode is not exitCode: time="2023-06-23T10:03:31Z" level=fatal msg="content digest sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15: not found"
2023-06-23T10:03:31.4203446Z         
2023-06-23T10:03:31.4209424Z --- FAIL: TestImageConvertZstdChunked (0.41s)
2023-06-23T10:03:31.4215481Z FAIL github.com/containerd/nerdctl/cmd/nerdctl.TestImageConvertZstdChunked (0.41s)
2023-06-23T10:03:31.7625504Z PASS github.com/containerd/nerdctl/cmd/nerdctl.TestImageInspectContainsSomeStuff (0.30s)
```

## Describe the results you received and expected

The CI can pass successfully

### LINKED ISSUE #2357: layer is not pulled when using the 'nerdctl pull'
### Description

Relate to the https://github.com/containerd/nerdctl/issues/2327

The content digest sha256:xxx: not found is becuase of the nerdctl does not pull the layer.

In my environment:

```
/usr/local/bin/nerdctl --namespace=nerdctl-test  save -o /tmp/haha.tar ghcr.io/stargz-containers/alpine:3.13-org
FATA[0000] failed to get reader: content digest sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15: not found
```

And try to pull with  nerdctl

```
root@kay201:~/oss/containerd# nerdctl  -n nerdctl-test pull ghcr.io/stargz-containers/alpine:3.13
-org
ghcr.io/stargz-containers/alpine:3.13-org:                                        resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:ec14c7992a97fc11425907e908340c6c3d6ff602f5f13d899e6b7027c9b4133a:    exists         |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:e103c1b4bf019dc290bcc7aca538dc2bf7a9d0fc836e186f5fa34945c5168310: exists         |++++++++++++++++++++++++++++++++++++++|
config-sha256:49f356fa4513676c5e22e3a8404aad6c7262cc7aaed15341458265320786c58c:   exists         |++++++++++++++++++++++++++++++++++++++|
elapsed: 2.9 s                                                                    total:   0.0 B (0.0 B/s)
```

It skips the layer file.  And the content digest is still not found.

And then try to pull with ctrctl
```
root@kay201:~/oss/containerd#  ctr  -n nerdctl-test i pull ghcr.io/stargz-containers/alpine:3.13-org
ghcr.io/stargz-containers/alpine:3.13-org:                                        resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:ec14c7992a97fc11425907e908340c6c3d6ff602f5f13d899e6b7027c9b4133a:    exists         |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:e103c1b4bf019dc290bcc7aca538dc2bf7a9d0fc836e186f5fa34945c5168310: exists         |++++++++++++++++++++++++++++++++++++++|
config-sha256:49f356fa4513676c5e22e3a8404aad6c7262cc7aaed15341458265320786c58c:   exists         |++++++++++++++++++++++++++++++++++++++|
layer-sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 1.7 s                                                                    total:  2.7 Mi (1.6 MiB/s)
unpacking linux/amd64 sha256:ec14c7992a97fc11425907e908340c6c3d6ff602f5f13d899e6b7027c9b4133a...
done: 9.968427ms
```

The layer file can be pulled and the content digest can be found. 

### Steps to reproduce the issue

1. nerdctl -n nerdctl-test pull ghcr.io/stargz-containers/alpine:3.13-org
2. ctr -n nerdctl-test content rm sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15
3. nerdctl -n nerdctl-test pull ghcr.io/stargz-containers/alpine:3.13-org
4. nerdctl --namespace=nerdctl-test save -o /tmp/haha.tar ghcr.io/stargz-containers/alpine:3.13-org

FATA[0000] failed to get reader: content digest sha256:ca3cd42a7c9525f6ce3d64c1a70982613a8235f0cc057ec9244052921853ef15: not found

### Describe the results you received and expected

The content digest exist, like using the ctrctl

### What version of nerdctl are you using?

root@kay201:~/oss/containerd# nerdctl version
Client:
 Version:       v1.4.0-82-g5195b20.m
 OS/Arch:       linux/amd64
 Git commit:    5195b2096db36d7ca6e09ae8028d7e018d2d83ff.m
 buildctl:
  Version:      v0.11.6
  GitCommit:    2951a28cd7085eb18979b1f710678623d94ed578

Server:
 containerd:
  Version:      v1.7.1
  GitCommit:    1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc:
  Version:      1.1.7
  GitCommit:    v1.1.7-0-g860f061b

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### LINKED ISSUE #2506: nerdctl push command not working when using minikube with containerd (`invalid checksum digest format`)
### Description

I currently use the `nerdctl` tool and a minikube cluster. I have a specific use case where I must commit an image and push it to a Docker Hub registry. However, every time I attempt to do this, I encounter the following error:

`
FATA[0001] failed commit on ref "index-sha256:8ee9676e710295f2ed187f72de413b4fe71e00587b4b069ae3e12777b7b9f01d": invalid content digest in response: invalid checksum digest format
`
I attempted to pull and push official docker images, tagged them with my personal account but was unable to push them to my repository.

### Steps to reproduce the issue

1. I installed minikube cluster with cotnainerd

`minikube start --ports=443 --ports=80 --container-runtime=containerd --cni=cilium --kubernetes-version=1.27`

2. Installed nerdctl 

`wget https://github.com/containerd/nerdctl/releases/download/v1.5.0/nerdctl-1.5.0-linux-amd64.tar.gz`
`tar -xvf nerdctl-1.5.0-linux-amd64.tar.gz`
`mv nerdctl /usr/local/bin`

3. sudo nerdctl login
4. sudo nerdctl pull <private image>
5. sudo nerdctl tag <private_image> <private_image_with_new_tag>
6. sudo nerdctl push <private_image_with_new_tag>

### Describe the results you received and expected

The result I received:

**initial error**: 

docker@minikube:~$ sudo nerdctl -n k8s.io push USERNAME/nginx_nerdctl --all-platforms --debug 
DEBU[0000] Found hosts dir "/etc/containerd/certs.d"
DEBU[0000] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0000] pushing                                       digest="sha256:c2be4b8e4cdfsdsd71cb4e565f1bb83582d2841a0a8300509d079c92460734b11" image="docker.io/USERNAME/nginx_nerdctl:latest"
DEBU[0000] loading host directory                        dir=/etc/containerd/certs.d/docker.io
ERRO[0000] failed to decode hosts.toml                   error="invalid `host` tree"
manifest-sha256:c2be4b8e4cdf04f71cb4e565f1bb83582d2841a0a8300509d079c92460734b11: waiting        |--------------------------------------|
elapsed: 0.1 s                                                                    total:   0.0 B (0.0 B/s)
FATA[0000] content digest sha256:360eba32sdsda65016e0d558c6af176db31a202e9a6071666f9b629cb8ba6ccedf0: not found

I was able to resolve host and dir errors by creating dir and hosts.toml file.

**Second**:

FATA[0001] failed commit on ref "index-sha256:8ee9676e710295f2ed187f72de413b4fe71e00587b4b069ae3e12777b7b9f01d": invalid content digest in response: invalid checksum digest format

### What version of nerdctl are you using?

1.5.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: 1.6.21
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: aufs native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-82-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 7
 Total Memory: 6.001GiB
 Name: minikube
 ID: 1bef4b81-eeb8-4454-8c2f-f590c6267fd3

### LINKED ISSUE #3026: nerdctl push  level=fatal msg="content digest sha256:xxx: not found"
### Description

nerdctl push  level=fatal msg=content digest sha256:xxx: not found

### Steps to reproduce the issue

command :  
1. nerdctl commit --namespace xxx "${CONTAINER_ID}" "${_IMAGE_INFO}"

2. nerdctl push --namespace xxx "${_IMAGE_INFO}" --all-platforms --insecure-registry --hosts-dir /etc/cert/certs.d/

### Describe the results you received and expected

1.return msg:
 level=warning msg="Image lacks label "nerdctl/platform", assuming the platform to be "linux/arm64/v8""
sha256:91d29b450fd577c6178932589d82d6605cfba904b7d16b75d6e81bbf00426057

2.return msg:
level=warning msg="skipping verifying HTTPS certs for "harbor address""
manifest-sha256:0ec2084b9ea28247e6039d3a4d4a1dc7303283a2d026dbc136d1bc52b488278c: waiting        |--------------------------------------|
config-sha256:91d29b450fd577c6178932589d82d6605cfba904b7d16b75d6e81bbf00426057:   waiting        |--------------------------------------|
elapsed: 0.1 s                                                                    total:   0.0 B (0.0 B/s)
manifest-sha256:0ec2084b9ea28247e6039d3a4d4a1dc7303283a2d026dbc136d1bc52b488278c: waiting        |--------------------------------------|
config-sha256:91d29b450fd577c6178932589d82d6605cfba904b7d16b75d6e81bbf00426057:   waiting        |--------------------------------------|
elapsed: 0.2 s                                                                    total:   0.0 B (0.0 B/s)

level=fatal msg="content digest sha256:cd25eaaf6be54ee842ccee9897790061be5fc8f83a04a3766fe9b94c14669855: not found"

### What version of nerdctl are you using?

 1.5.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### LINKED ISSUE #3420: Build fail with "parent snapshot does not exist"
### Description

Build will fail with 

```
FATA[0000] apply layer error for "docker.io/library/test:latest": failed to prepare extraction snapshot "extract-810343375-eUiw sha256:2f8da9dda8e00a45de9a98ebd2dbc4394149baf8686dbda33d20899c797c9f5f": parent snapshot sha256:e644ff0c302d7de4c3e03dc718bc4b77ebeb324f7c8f5483b463fa230027b02c does not exist: not found
```

This is random and may take some time.

To repro:
```
while true; do nerdctl build --debug-full --no-cache -t test .; done
```

### Steps to reproduce the issue

na

### Describe the results you received and expected

```
Loaded image: docker.io/library/test:latest
DEBU[0000] stateDir: /run/user/501/containerd-rootless
DEBU[0000] RootlessKit detach-netns mode: true
DEBU[0000] rootless parent main: executing "/usr/bin/nsenter" with [-r/ -w/tmp --preserve-credentials -m -U -t 972422 -F nerdctl build --debug-full --no-cache -t test .]
DEBU[0000] Choosing the buildkit host "unix:///run/user/501/buildkit-default/buildkitd.sock", candidates=[unix:///run/user/501/buildkit-default/buildkitd.sock unix:///run/user/501/buildkit/buildkitd.sock]
DEBU[0000] Choosing the buildkit host "unix:///run/user/501/buildkit/buildkitd.sock", candidates=[unix:///run/user/501/buildkit-default/buildkitd.sock unix:///run/user/501/buildkit/buildkitd.sock]
DEBU[0000] Chosen buildkit host "unix:///run/user/501/buildkit/buildkitd.sock"
DEBU[0000] worker labels: map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:lima-v2 org.mobyproject.buildkit.worker.network:cni org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.selinux.enabled:false org.mobyproject.buildkit.worker.snapshotter:overlayfs]
DEBU[0000] running /usr/local/bin/buildctl [--addr=unix:///run/user/501/buildkit/buildkitd.sock build --progress=auto --frontend=dockerfile.v0 --local=context=. --output=type=docker,name=docker.io/library/test:latest --local=dockerfile=/tmp --opt=filename=Dockerfile --no-cache]
[+] Building 0.5s (6/6)
[+] Building 0.5s (6/6) FINISHED
 => [internal] load build definition from Dockerfile                                                                     0.0s
 => => transferring dockerfile: 124B                                                                                     0.0s
 => [internal] load metadata for docker.io/library/nginx:latest                                                          0.1s
 => [internal] load .dockerignore                                                                                        0.0s
 => => transferring context: 2B                                                                                          0.0s
 => CACHED [1/2] FROM docker.io/library/nginx:latest@sha256:04ba374043ccd2fc5c593885c0eacddebabd5ca375f9323666f28dfd5a9  0.0s
 => => resolve docker.io/library/nginx:latest@sha256:04ba374043ccd2fc5c593885c0eacddebabd5ca375f9323666f28dfd5a9710e3    0.0s
 => [2/2] RUN echo 'Hello Nerdctl From Containerd' > /usr/share/nginx/html/index.html                                    0.0s
 => exporting to docker image format                                                                                     0.3s
 => => exporting layers                                                                                                  0.0s
 => => exporting manifest sha256:2cab31a5770a6e4b1b883e12003f7db13dbec31f1453ffd9c5cf40f595786007                        0.0s
 => => exporting config sha256:d17d7567c3198103f72ee65d06acb0b63a5bc524a9afcef847fd647fb6eeec83                          0.0s
 => => sending tarball                                                                                                   0.3s
FATA[0000] apply layer error for "docker.io/library/test:latest": failed to prepare extraction snapshot "extract-153144429-zNRp sha256:29099085e37cb571e3c6e6f499df323f4965d1bd7cd8139415fc03fedb121077": parent snapshot sha256:3b487b874707d138c99a5dc4c6ffdb9a19b45937998141fa43aefab26d607347 does not exist: not found
fail
```

### What version of nerdctl are you using?

```
Client:
 Version:	v2.0.0-rc.1-132-g814418aa.m
 OS/Arch:	linux/arm64
 Git commit:	814418aa3becd4231ca39e400832bc86dc5481d1.m
 buildctl:
  Version:	v0.15.2
  GitCommit:	9e14164a1099d3e41b58fc879cbdd6f2b2edb04e

Server:
 containerd:
  Version:	v2.0.0-rc.3-211-g7b948faa0.m
  GitCommit:	7b948faa084506e72967d88b5d35423211f13b07.m
 runc:
  Version:	1.2.0-rc.3+dev
  GitCommit:	v1.2.0-rc.3-1-g961b8031
```

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### LINKED ISSUE #3425: Issues related to missing layer (likely caused by https://github.com/containerd/containerd/issues/8973 )
### Description

This here is to collect issues that _may_ be caused by https://github.com/containerd/containerd/issues/8973

* #3420
* #827 
* #2588
* #3415
* #2506
* #2327
* #2357

How to solve it is unclear at this point.

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
See #3425 and linked issues for context.

- fix #3425
- fix #827 (commit)
- fix #2357 (save)
- fix #2327 (convert)
- fix #2506 (tag)
- fix #3026 (commit)

Unconfirmed (no test), but cannot reproduce anymore with the patch:
- fix #3420

Unconfirmed, but probably fixed as well:
- #2588 (untested)

Reviewers, most of this is test wrangling:
- enabling Kube test which was missing a few bits
- fixing broken image inspect tests that are now more likely to show leftovers

### CODE REVIEW

File: cmd/nerdctl/container/container_commit_linux_test.go [hunk 1]
```diff
@@ -35,7 +35,7 @@ It will regularly succeed or fail, making random PR fail the Kube check.
 func TestKubeCommitPush(t *testing.T) {
 	t.Parallel()
 
-	t.Skip("Test that confirm that #827 is still broken is too flaky")
+	// t.Skip("Test that confirm that #827 is still broken is too flaky")
```
Comment (apostasie) [inline cmd/nerdctl/container/container_commit_linux_test.go:38]: Will remove once CI is green.

File: pkg/imgutil/imgutil.go [hunk 2]
```diff
@@ -102,6 +103,44 @@ func GetExistingImage(ctx context.Context, client *containerd.Client, snapshotte
...
 }
 
+func EnsureAllContent(ctx context.Context, client *containerd.Client, rawRef string, platform string, options types.GlobalCommandOptions) error {
+	named, err := distributionref.ParseDockerRef(rawRef)
+	if err != nil {
+		return err
+	}
+	refDomain := distributionref.Domain(named)
+
+	// Get a resolver
```
Comment (apostasie) [inline pkg/imgutil/imgutil.go:113]: We should put that away somewhere with the login code refactor. Resolver is repetitive and error prone...

**Comment by apostasie** [comment]
Note that the Kube failure is expected - as registry.example does not exist.

What matters here is that we get to the point we are talking with the registry (and do not fail anymore while creating the single platform image).

Will change that test soon.

**Comment by apostasie** [comment]
@AkihiroSuda can you poke the CI?

File: pkg/cmd/image/tag.go [hunk 3]
```diff
@@ -59,17 +60,23 @@ func Tag(ctx context.Context, client *containerd.Client, options types.ImageTagO
...
 		return err
 	}
-	image.Name = target.String()
-	if _, err = imageService.Create(ctx, image); err != nil {
+	img.Name = target.String()
+
+	err = imgutil.EnsureAllContent(ctx, client, srcName, img.Target, "", options.GOptions)
+	if err != nil {
+		return err
+	}
```
Comment (lingdie) [inline pkg/cmd/image/tag.go:72]: When tagging, do we need to return errors for failed pulls? This might not meet expectations.

Comment (apostasie) [reply pkg/cmd/image/tag.go:72]: Yes, that is a valid concern.
Then if at a later point we try to push it, it will fail…
Not sure how to deal with that…

Comment (apostasie) [reply pkg/cmd/image/tag.go:72]: I do not like any of the code involved in there.
The "single-platform tmp-reduced-platform image" gymnastic / convert intermediary step on push just smells fishy.
Then again, this is containerd design issues here.

Comment (lingdie) [reply pkg/cmd/image/tag.go:72]: We could introduce a new flag called `ensure-image` for both the `tag` and `commit` commands. 

When this flag is set, we would attempt to pull any missing layers. If any errors occur during this process, they would be returned.

Comment (apostasie) [reply pkg/cmd/image/tag.go:72]: The thing that is bugging me with the new flag approach is that it would leave the default behavior broken, which I don't think is right.

So, what about this: instead of _hard error_ when the fetch fail, we just print a loud warning but we continue?
wdyt @lingdie ?

Comment (apostasie) [reply pkg/cmd/image/tag.go]: Latest push implements this.
We no longer hard error, but warn the user.
PTAL at your convenience @lingdie

Comment (lingdie) [reply pkg/cmd/image/tag.go]: look good to me.

**Review by lingdie — APPROVED** [review]

File: pkg/imgutil/imgutil.go [hunk 4]
```diff
@@ -102,6 +103,52 @@ func GetExistingImage(ctx context.Context, client *containerd.Client, snapshotte
...
+		resolver, err := dockerconfigresolver.New(ctx, refDomain, dOpts...)
+		if err != nil {
+			return err
+		}
+
+		opts := []containerd.RemoteOpt{
+			containerd.WithResolver(resolver),
+			containerd.WithPlatformMatcher(platformComparer),
+		}
+		_, err = client.Fetch(ctx, rawRef, opts...)
```
Comment (lingdie) [inline pkg/imgutil/imgutil.go:145]: Is there any output when fetching layers?

Comment (lingdie) [reply pkg/imgutil/imgutil.go:145]: Do we want this 'processing' outputs?

Comment (apostasie) [reply pkg/imgutil/imgutil.go:145]: There probably is output.
I don't know if it is desirable to show it or not... if we do show it, it will change behavior on the output of commands and diverge from docker (especially since it is supposed to go to stdout - #3395) - if we do not show it, it might appear to the user as if it is hanging...

wdyt?

Comment (apostasie) [reply pkg/imgutil/imgutil.go]: Last push does show the output.
Still not sure if we want it or not :-), but at least that gives us options.

**Comment by apostasie** [comment]
@AkihiroSuda your opinion welcome at your convenience.

File: pkg/imgutil/imgutil.go (hunk 4 above)
Comment (lingdie) [reply pkg/imgutil/imgutil.go]: no idea :-).

**Comment by apostasie** [comment]
@AkihiroSuda rebased.

Kube failure is the regression from #3446 - presumably fixed with #3460

The other failure seems random / flaky. Will investigate it soon as I am rewriting the `image` tests now.

Ready for review otherwise.

**Comment by apostasie** [comment]
Rewrote the offending test as part of #3461 (<- PR not ready yet).

The test was not isolated, and it clearly requires a blank slate with no other image in it.
https://github.com/containerd/nerdctl/blob/main/cmd/nerdctl/image/image_inspect_test.go#L75-L85

My guess is that with the current version of the test, some leftover from a previous test prevents the (busybox or alpine) images from being rmi-ed - not a problem on amd64, but obviously not on arm64.
As to why this is kicking now with this patch here: my guess is that now that we are forcing download of layers on `tag`, leftovers are more likely.

Anyhow, the rewritten test will provide much better isolation for that test, so, I would suggest we either ignore the problem here, or first merge the two testing-rewrite PRs and rebase if we want "stronger green".

**Comment by apostasie** [comment]
CI is green (save for the windows regression #3437).

@AkihiroSuda This is how far I will go with this.

I already hate this PR, and there are still glaring issues to fix in all that stuff, especially the whole `tmp-reduced-platform` contorsions, and overall most things touching platform code (which definitely stems from containerd btw - just staring at stevvooe's 10 years old code and comments in that regard make my eyes bleed).

Anyhow, I still believe this PR here will help a lot, as the issue being fixed has been one of our most pervasive and egregious.

Credits for this fix should go to @lingdie who did the research and correctly identified the underlying containerd issue, then pointed me in the right direction.

PTAL at your convenience.

File: cmd/nerdctl/container/container_commit_linux_test.go [hunk 5]
```diff
@@ -35,12 +33,11 @@ It will regularly succeed or fail, making random PR fail the Kube check.
 func TestKubeCommitPush(t *testing.T) {
 	t.Parallel()
 
-	t.Skip("Test that confirm that #827 is still broken is too flaky")
-
 	base := testutil.NewBaseForKubernetes(t)
 	tID := testutil.Identifier(t)
 
 	var containerID string
+	// var registryIP string
```
Comment (AkihiroSuda) [inline cmd/nerdctl/container/container_commit_linux_test.go:40]: ?

File: cmd/nerdctl/container/container_commit_linux_test.go [hunk 6]
```diff
@@ -55,26 +52,45 @@ func TestKubeCommitPush(t *testing.T) {
 		cmd := testutil.KubectlHelper(base, "get", "pods", tID, "-o", "jsonpath={ .status.containerStatuses[0].containerID }")
 		cmd.Run()
 		containerID = strings.TrimPrefix(cmd.Out(), "containerd://")
+
+		// This below is missing configuration to allow for plain http communication
```
Comment (apostasie) [inline cmd/nerdctl/container/container_commit_linux_test.go:56]: Was not able / interested enough to finish setting up a cluster registry.
This here is a start, and can be completed later on, either by me or someone else.

File: cmd/nerdctl/container/container_commit_linux_test.go [hunk 7]
```diff
@@ -55,26 +52,45 @@ func TestKubeCommitPush(t *testing.T) {
...
+					host: "%s:5000"
+					help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
+			`, registryIP))
+		*/
+
 	}
 
 	tearDown := func() {
-		testutil.KubectlHelper(base, "delete", "pod", "-f", tID).Run()
+		testutil.KubectlHelper(base, "delete", "pod", "--all").Run()
```
Comment (apostasie) [inline cmd/nerdctl/container/container_commit_linux_test.go:85]: For some reason that escapes me, kubectl was not cleaning up with the pod name

File: cmd/nerdctl/container/container_commit_linux_test.go [hunk 8]
```diff
@@ -55,26 +52,45 @@ func TestKubeCommitPush(t *testing.T) {
...
-			"change the expectation to 'success'.")
-
-		base.Cmd("commit", containerID, "registry.example.com/my-app:v1").AssertOK()
-		// See note above.
-		base.Cmd("push", "registry.example.com/my-app:v1").Assert(icmd.Expected{
-			ExitCode: 1,
-			Err:      "failed to create a tmp single-platform image",
-		})
+		base.Cmd("commit", containerID, "testcommitsave").AssertOK()
+		base.Cmd("save", "testcommitsave").AssertOK()
```
Comment (apostasie) [inline cmd/nerdctl/container/container_commit_linux_test.go:94]: This correctly reproduce issue #827 I believe.

File: cmd/nerdctl/image/image_inspect_test.go [hunk 9]
```diff
@@ -26,69 +26,52 @@ import (
 
 	"github.com/containerd/nerdctl/v2/pkg/inspecttypes/dockercompat"
 	"github.com/containerd/nerdctl/v2/pkg/testutil"
+	"github.com/containerd/nerdctl/v2/pkg/testutil/nerdtest"
+	"github.com/containerd/nerdctl/v2/pkg/testutil/test"
 )
 
-func TestImageInspectContainsSomeStuff(t *testing.T) {
```
Comment (apostasie) [inline cmd/nerdctl/image/image_inspect_test.go:31]: This turned out flaky as I was debugging this new code.
Rewriting against the new toolkit to fix that.

File: cmd/nerdctl/image/image_inspect_test.go [hunk 10]
```diff
@@ -26,69 +26,52 @@ import (
...
+		},
 	}
-	return dc
+
+	testCase.Run(t)
 }
 
 func TestImageInspectDifferentValidReferencesForTheSameImage(t *testing.T) {
-	testutil.DockerIncompatible(t)
+	nerdtest.Setup()
```
Comment (apostasie) [inline cmd/nerdctl/image/image_inspect_test.go:72]: Same as the other test.

File: cmd/nerdctl/image/image_list_test.go [hunk 11]
```diff
@@ -125,7 +125,8 @@ func TestImagesFilterDangling(t *testing.T) {
 	testutil.RequiresBuild(t)
 	testutil.RegisterBuildCacheCleanup(t)
 	base := testutil.NewBase(t)
-	base.Cmd("images", "prune", "--all").AssertOK()
```
Comment (apostasie) [inline cmd/nerdctl/image/image_list_test.go:128]: This (obviously?) was doing nothing and leftovers from other tests were having an impact here.
Because we depend on build here, we cannot use a private namespace, so, making sure we clean house.

File: hack/build-integration-kubernetes.sh [hunk 12]
```diff
@@ -23,6 +23,7 @@ readonly root
 
 GO_VERSION=1.23
 KIND_VERSION=v0.24.0
+CNI_PLUGINS_VERSION=v1.5.1
```
Comment (apostasie) [inline hack/build-integration-kubernetes.sh:26]: Somehow when I came up with the Kube tooling, I did not test networking.
We (obviously?) do need cni here for nerdctl to work outside of kube itself.

File: pkg/cmd/image/tag.go [hunk 13]
```diff
@@ -31,7 +32,7 @@ import (
 func Tag(ctx context.Context, client *containerd.Client, options types.ImageTagOptions) error {
 	imageService := client.ImageService()
 	var srcName string
-	imagewalker := &imagewalker.ImageWalker{
+	walker := &imagewalker.ImageWalker{
```
Comment (apostasie) [inline pkg/cmd/image/tag.go:35]: Do not shadow the package name.

File: pkg/cmd/image/tag.go [hunk 14]
```diff
@@ -59,17 +60,25 @@ func Tag(ctx context.Context, client *containerd.Client, options types.ImageTagO
 	}
 	defer done(ctx)
 
-	image, err := imageService.Get(ctx, srcName)
+	// Ensure all the layers are here: https://github.com/containerd/nerdctl/issues/3425
+	err = EnsureAllContent(ctx, client, srcName, options.GOptions)
+	if err != nil {
+		log.G(ctx).Warn("Unable to fetch missing layers before committing. " +
```
Comment (apostasie) [inline pkg/cmd/image/tag.go:66]: On tag, we do not hard error if we fail to retrieve the missing layers.
This is to preserve the previous behavior, in case we are offline.
Warn the user instead, and point it to a special purpose ticket that provides explanations.

File: pkg/imgutil/commit/commit.go [hunk 15]
```diff
@@ -126,6 +127,13 @@ func Commit(ctx context.Context, client *containerd.Client, container containerd
 		return emptyDigest, err
 	}
 
+	// Ensure all the layers are here: https://github.com/containerd/nerdctl/issues/3425
+	err = image.EnsureAllContent(ctx, client, baseImg.Name(), globalOptions)
+	if err != nil {
```
Comment (apostasie) [inline pkg/imgutil/commit/commit.go:132]: Same as tag, we do not hard error on commit.

File: pkg/cmd/image/convert.go [hunk 16]
```diff
@@ -75,6 +75,12 @@ func Convert(ctx context.Context, client *containerd.Client, srcRawRef, targetRa
 	}
 	convertOpts = append(convertOpts, converter.WithPlatform(platMC))
 
+	// Ensure all the layers are here: https://github.com/containerd/nerdctl/issues/3425
+	err = EnsureAllContent(ctx, client, srcRawRef, options.GOptions)
+	if err != nil {
+		return err
```
Comment (apostasie) [inline pkg/cmd/image/convert.go:81]: Convert and Save DO hard error, since the operation cannot complete if there is missing content.

**Comment by apostasie** [comment]
Added some inline comments to ease review.

**Comment by apostasie** [comment]
@AkihiroSuda with containerd rc5 just out - it would be nice to have this one in for the next nerdctl rc so that we can get it some soak time.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by ChrisBr** [comment]
@apostasie we seem to run into this issue when using the GKE [image streaming snapshotter](https://cloud.google.com/kubernetes-engine/docs/how-to/image-streaming). When we commit an image locally (e.g. with docker) and don't push it, the converter tries to pull the image from remote. Is this expected?

Example
```
> docker run --name foo alpine
> docker commit foo gcr.io/$repo/cbruckmayer:foo

# I can use the image with nerdctl
> nerdctl --address /var/run/docker/containerd/containerd.sock --namespace moby --snapshotter gcfs run -it --network none gcr.io/$repo/cbruckmayer:foo

# However, when trying to convert the image, it will try to pull it from remote which fails with not found

> nerdctl --address /var/run/docker/containerd/containerd.sock --namespace moby --snapshotter gcfs image convert --zstd --oci gcr.io/$repo/cbruckmayer:foo gcr.io/$repo/cbruckmayer:foo-zstd
gcr.io/$repo/cbruckmayer:foo: resolving      |--------------------------------------|
elapsed: 0.1 s                                total:   0.0 B (0.0 B/s)
INFO[0000] fetch failed after status: 404 Not Found      host=gcr.io
FATA[0000] failed to resolve reference "gcr.io/$repo/cbruckmayer:foo": gcr.io/$repo/cbruckmayer:foo: not found
root@docker-daemon-rzhtc:/app# nerdctl --debug-full --address /var/run/docker/containerd/containerd.sock --namespace moby --snapshotter gcfs image convert --zstd --oci gcr.io/$repo/cbruckmayer:foo gcr.io/$repo/cbruckmayer:foo-zstd
DEBU[0000] fetching                                      image="gcr.io/$repo/cbruckmayer:foo"
DEBU[0000] resolving                                     host=gcr.io
DEBU[0000] do request                                    host=gcr.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/2.0.0+unknown request.method=HEAD url="https://gcr.io/v2/$repo/cbruckmayer/manifests/foo"
DEBU[0000] fetch response received                       host=gcr.io response.header.accept-ranges=none response.header.content-type=application/json response.header.date="Fri, 13 Dec 2024 13:10:25 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.server="Docker Registry" response.header.vary=Accept-Encoding response.header.www-authenticate="Bearer realm=\"https://gcr.io/v2/token\",service=\"gcr.io\",scope=\"repository:$repo/cbruckmayer:pull\"" response.header.x-frame-options=SAMEORIGIN response.header.x-xss-protection=0 response.status="401 Unauthorized" url="https://gcr.io/v2/$repo/cbruckmayer/manifests/foo"
DEBU[0000] Unauthorized                                  header="Bearer realm=\"https://gcr.io/v2/token\",service=\"gcr.io\",scope=\"repository:$repo/cbruckmayer:pull\"" host=gcr.io
DEBU[0000] do request                                    host=gcr.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/2.0.0+unknown request.method=HEAD url="https://gcr.io/v2/$repo/cbruckmayer/manifests/foo"
DEBU[0000] fetch response received                       host=gcr.io response.header.accept-ranges=none response.header.content-type=application/json response.header.date="Fri, 13 Dec 2024 13:10:25 GMT" response.header.docker-distribution-api-version=registry/2.0 response.header.server="Docker Registry" response.header.vary=Accept-Encoding response.header.x-frame-options=SAMEORIGIN response.header.x-xss-protection=0 response.status="404 Not Found" url="https://gcr.io/v2/$repo/cbruckmayer/manifests/foo"
INFO[0000] fetch failed after status: 404 Not Found      host=gcr.io
FATA[0000] failed to resolve reference "gcr.io/$repo/cbruckmayer:foo": gcr.io/shopify-docker-images/cbruckmayer:foo: not found
```

**Comment by apostasie** [comment]
@ChrisBr 
Unfortunately, yes, this is expected, as it is necessary to mitigate the unforeseen effects of containerd "lazy" pulling.

Though, in this case, maybe we can relax to a soft error if the pull fails.

Do you mind opening a new issue with these details?
I'll look into it ASAP.
