### PR TITLE
Remove duplicate host record when update the DNS

### LINKED ISSUE #1149: All services use the same network(external) but some service can't find the correct address of another address
### Description

```~/.local/share/nerdctl/1935db59/etchosts/default/b3571ed508bb30a1598eb9f782ff49d134bccbe500dcbf34ef15bfd41641a743/hosts``` have multiple lines of the same service

image

and dns results for different services are different which cause ping error （The service can not use the correct ip）
image

the correct is ：
image

### Steps to reproduce the issue

I don't know how it happens 

### Describe the results you received and expected

All services use the same external network can communicate with each other。

### What version of nerdctl are you using?

nerdctl version 0.20.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

_No response_

### Host information

_No response_

### PR DESCRIPTION
**Pull request by Zheaoli**
Fix #1149 #1242 

In the future, we may use the https://github.com/containers/dnsname project to maintain the DNS record

Signed-off-by: Zheao.Li <me@manjusaka.me>

### CODE REVIEW

File: pkg/testutil/compose.go [hunk 1]
```diff
@@ -50,15 +50,15 @@ func (cd *ComposeDir) CleanUp() {
 	os.RemoveAll(cd.dir)
 }
 
-func NewComposeDir(t testing.TB, dockerComposeYAML string) *ComposeDir {
+func NewComposeDir(t testing.TB, dockerComposeYAML string, yamlName string) *ComposeDir {
```
Comment (manugupt1) [inline pkg/testutil/compose.go:53]: maybe this variable can be namedm as yamlBasePath

Comment (Zheaoli) [reply pkg/testutil/compose.go:53]: LGTM

File: pkg/testutil/compose.go [hunk 2]
```diff
@@ -50,15 +50,15 @@ func (cd *ComposeDir) CleanUp() {
 	os.RemoveAll(cd.dir)
 }
 
-func NewComposeDir(t testing.TB, dockerComposeYAML string) *ComposeDir {
+func NewComposeDir(t testing.TB, dockerComposeYAML string, yamlFileName string) *ComposeDir {
```
Comment (AkihiroSuda) [inline pkg/testutil/compose.go:53]: I don't think we need this change

Comment (Zheaoli) [reply pkg/testutil/compose.go:53]: Because I want to test two different compose file as the same file. I think change this method signature will help me to reuse the code as most as I can

Comment (AkihiroSuda) [reply pkg/testutil/compose.go:53]: The filename  (`docker-compose.yaml`) can be still same as long as we use different directories?

Comment (Zheaoli) [reply pkg/testutil/compose.go]: Ops, I have not seen the tmp file system has been used here

Comment (Zheaoli) [reply pkg/testutil/compose.go]: Done

File: cmd/nerdctl/compose_up_linux_test.go [hunk 3]
```diff
@@ -437,3 +437,54 @@ services:
...
+  test:
+    external: true
+`, testutil.NginxAlpineImage, containerName2)
+	comp1 := testutil.NewComposeDir(t, dockerComposeYaml1)
+	defer comp1.CleanUp()
+	comp2 := testutil.NewComposeDir(t, dockerComposeYaml2)
+	defer comp2.CleanUp()
+	base := testutil.NewBase(t)
+	// Create the test network
+	base.Cmd("network", "create", "test").AssertOK()
```
Comment (AkihiroSuda) [inline cmd/nerdctl/compose_up_linux_test.go:478]: The network name has to be `testutil.Identifier(t)` and has to be removed with `defer`

File: cmd/nerdctl/compose_up_linux_test.go [hunk 4]
```diff
@@ -437,3 +437,54 @@ services:
 	base.ComposeCmd("-f", comp.YAMLFullPath(), "down").AssertOK()
 
 }
+
+func TestComposeUpWithExternalNetwork(t *testing.T) {
+	containerName1 := "nginx-1"
```
Comment (AkihiroSuda) [inline cmd/nerdctl/compose_up_linux_test.go:442]: Has to be prefixed with `testutil.Identifier(t)`

File: cmd/nerdctl/compose_up_linux_test.go [hunk 5]
```diff
@@ -437,3 +437,56 @@ services:
 	base.ComposeCmd("-f", comp.YAMLFullPath(), "down").AssertOK()
 
 }
+
+func TestComposeUpWithExternalNetwork(t *testing.T) {
+	containerName1 := testutil.Identifier(t)
+	containerName2 := testutil.Identifier(t)
```
Comment (AkihiroSuda) [inline cmd/nerdctl/compose_up_linux_test.go:443]: You have to append some suffixes like "-1" and "-2"

File: pkg/dnsutil/hostsstore/updater.go [hunk 6]
```diff
@@ -146,17 +146,26 @@ func (u *updater) phase2() error {
 		if err != nil {
 			return err
 		}
+		serviceHosts := make(map[string]string)
+		for ip, host := range hosts {
+			if ip == "127.0.0.1" || ip == ":1" {
```
[the remark this answers is not in the document]
Comment (AkihiroSuda) [reply pkg/dnsutil/hostsstore/updater.go:151]: This seems actually a typo of `::1`

[the remark this answers is not in the document]
Comment (AkihiroSuda) [reply pkg/dnsutil/hostsstore/updater.go:151]: (Can be fixed in another PR)

[the remark this answers is not in the document]
Comment (Zheaoli) [reply pkg/dnsutil/hostsstore/updater.go]: Yes, I have already fixed this

**Review by AkihiroSuda — APPROVED** [review]
Thanks
