### PR TITLE
CI/test fixing

### LINKED ISSUE #3403: rootlesskit / apparmor output inconsistent w/wo root?
### Description

```
sudo nerdctl run --rm --privileged alpine cat /proc/self/attr/apparmor/current
unconfined

nerdctl run --rm --privileged alpine cat /proc/self/attr/apparmor/current
/usr/local/bin/rootlesskit (unconfined)
```

Is this expected?

This is making tests fail locally on my rig - as `TestRunApparmor` does `AssertOutExactly("unconfined\n")` (and that test technically is not restricted to rootful)

### Steps to reproduce the issue

_No response_

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

_No response_

### PR DESCRIPTION
**Pull request by apostasie**
Tiny commits enhancing our test situation - making sure we do cleanup resources once done, to avoid polluting other tests expecting a clean slate.

Fix #3403

@AkihiroSuda can we get this in? (see question inline though)

### CODE REVIEW

File: cmd/nerdctl/image/image_load_linux_test.go [hunk 1]
```diff
@@ -32,23 +32,35 @@ import (
...
 
+	setup := func() {
+		base.Cmd("pull", testutil.CommonImage).AssertOK()
+		base.Cmd("tag", testutil.CommonImage, img).AssertOK()
+		base.Cmd("save", img, "-o", filepath.Join(tmp, "common.tar")).AssertOK()
+		base.Cmd("rmi", "-f", img).AssertOK()
+	}
+
+	tearDown := func() {
+		base.Cmd("rmi", "-f", img).AssertOK()
```
Comment (apostasie) [inline cmd/nerdctl/image/image_load_linux_test.go:47]: Make sure we cleanup the image once done.

File: cmd/nerdctl/image/image_load_linux_test.go [hunk 2]
```diff
@@ -32,23 +32,35 @@ import (
...
+
+	loadCmd := strings.Join(base.Cmd("load").Command, " ")
 	combined, err := exec.Command("sh", "-euxc", fmt.Sprintf("`cat %s/common.tar | %s > %s`", tmp, loadCmd, output)).CombinedOutput()
 	assert.NilError(t, err, "failed with error %s and combined output is %s", err, string(combined))
+
 	fb, err := os.ReadFile(output)
 	assert.NilError(t, err)
 
 	assert.Assert(t, strings.Contains(string(fb), fmt.Sprintf("Loaded image: %s:latest", img)))
-	base.Cmd("images").AssertOutContains(testutil.ImageRepo(testutil.CommonImage))
```
Comment (apostasie) [inline cmd/nerdctl/image/image_load_linux_test.go:51]: I do not understand what that was supposed to test.
It makes much more sense to me that we testing the fact the loaded image (with custom tag) is there, instead of testing what we know is there already...

Am I missing something here?

**Comment by apostasie** [comment]
CI failures are:
- IPFSCompose - ping @ktock 
- random network fluke breaking go / dockerfile build

**Comment by AkihiroSuda** [comment]
Thanks, but commit messages should explain what failure was fixed

**Comment by apostasie** [comment]
> Thanks, but commit messages should explain what failure was fixed

Fair enough.
Latest push makes it a bit better.

**Review by AkihiroSuda — APPROVED** [review]
Thanks
